server.port=9099
spring.application.name=acc-secure

other.web.unSafeUrlChars=null
other.web.enableLogRequestInFilter=true
other.web.enableBodyCacheFilter=true
other.web.enableLogTakeTimesInInterceptor=true

knife4j.production=true

service.token.url=
service.token.openLogger=true

server.tomcat.basedir=/Users/zhoucong/logs
logging.file.path=/Users/zhoucong/logs

service.route.mapping.default=

acc.secure.base-url=http://127.0.0.1:8080
acc.secure.provider-id=06
acc.secure.charset=UTF-8
acc.secure.format=json
acc.secure.device-id=ITP-ACC-SECURE
acc.secure.sign-type=00
acc.secure.sign-key=
acc.secure.paths.request-qr-logic-num-list=/ci/itp/requestQrLoigcNumList
acc.secure.paths.request-ca-key=/ci/itp/requestCaKey
acc.secure.paths.request-user-sm2-key=/ci/itp/requestUserSm2Key
acc.secure.paths.request-sign-pubkey=/ci/itp/requestSignPubkey
acc.secure.paths.request-export-user-pri-key=/ci/itp/requestExportUserPriKey
acc.secure.paths.request-sign-ins-data=/ci/itp/requestSignInsData
acc.secure.paths.request-dpk=/ci/itp/requestDPK
acc.secure.paths.request-hec-card-date=/ci/itp/requestHecCardDate
