package com.chinasofti.huateng.acc.es.server.model;

import java.io.Serializable;
import lombok.Data;

/**
 * @author rxwnc
 * @TableName TBL_STL_ES_ACCOUNT
 */
@Data
public class TblTktEsAccount implements Serializable {
    /**
     * 用户名
     *
     * @mbg.generated Mon Jan 18 16:21:16 CST 2021
     */
    private String username;

    /**
     * 密码
     *
     * @mbg.generated Mon Jan 18 16:21:16 CST 2021
     */
    private String password;

    /**
     * 操作员：1；管理员2
     *
     * @mbg.generated Mon Jan 18 16:21:16 CST 2021
     */
    private Short userType;

    /**
     * 
     *
     * @mbg.generated Mon Jan 18 16:21:16 CST 2021
     */
    private String remark;

    /**
     * 账户添加时间
     */
    private String addDate;

    /**
     * 最后账户修改时间
     */
    private String updateDate;

    /**
     * 账户添加或者修改账户
     */
    private String lastUpdateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_STL_ES_ACCOUNT
     *
     * @mbg.generated Mon Jan 18 16:21:16 CST 2021
     */
    private static final long serialVersionUID = 1L;
}