CREATE TABLE ACC_SIM_EMPLOYEE_CARD (
    CARD_NO VARCHAR2(32 CHAR) NOT NULL,
    PHONE VARCHAR2(64 CHAR),
    CARD_STATUS NUMBER(1) NOT NULL,
    EMPLOYEE_NAME VARCHAR2(256 CHAR),
    ID_CARD_NO VARCHAR2(128 CHAR),
    COMPANY VARCHAR2(256 CHAR),
    CENTER VARCHAR2(256 CHAR),
    DEPARTMENT VARCHAR2(256 CHAR),
    POSITION VARCHAR2(256 CHAR),
    PHOTO CLOB,
    CREATE_TMS TIMESTAMP(6) NOT NULL,
    UPDATE_TMS TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_ACC_SIM_EMP_CARD PRIMARY KEY (CARD_NO),
    CONSTRAINT CK_ACC_SIM_EMP_STATUS CHECK (CARD_STATUS IN (1, 2, 3, 4))
);

CREATE TABLE ACC_SIMULATION_HISTORY (
    ID NUMBER(19) NOT NULL,
    OPERATION VARCHAR2(64 CHAR) NOT NULL,
    TARGET_URL VARCHAR2(512 CHAR),
    TRANSPORT_SUCCESS NUMBER(1) NOT NULL,
    HTTP_STATUS NUMBER(3),
    REQUEST_BODY CLOB,
    RESPONSE_BODY CLOB,
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    CREATED_AT TIMESTAMP(6) NOT NULL,
    ELAPSED_MS NUMBER(19),
    CONSTRAINT PK_ACC_SIM_HISTORY PRIMARY KEY (ID)
);
CREATE SEQUENCE ACC_SIM_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_ACC_SIM_HISTORY_CREATED ON ACC_SIMULATION_HISTORY (CREATED_AT DESC, ID DESC);
