-- 日票退款运营页面索引迁移。
-- 在已创建 DAILY_TICKET_ORDER、DAILY_TICKET_REFUND 表的环境中执行一次。
-- 执行前请确认 DAILY_TICKET_REFUND.ORDER_NO 不存在重复记录。

ALTER TABLE DAILY_TICKET_REFUND ADD PLATFORM_REFUND_NO VARCHAR2(128);
COMMENT ON COLUMN DAILY_TICKET_REFUND.PLATFORM_REFUND_NO IS '支付平台退款单号';
CREATE INDEX IDX_DAILY_TICKET_ORDER_PAYMENT ON DAILY_TICKET_ORDER (PAYMENT_ORDER_NO);
CREATE INDEX IDX_DAILY_TICKET_ORDER_CREATE ON DAILY_TICKET_ORDER (CREATE_TIME);
CREATE UNIQUE INDEX UK_DAILY_TICKET_REFUND_ORDER ON DAILY_TICKET_REFUND (ORDER_NO);
CREATE INDEX IDX_DAILY_TICKET_REFUND_CREATE ON DAILY_TICKET_REFUND (CREATE_TIME);
CREATE INDEX IDX_DAILY_TICKET_REFUND_ORDER_NO ON DAILY_TICKET_REFUND (REFUND_ORDER_NO);
CREATE INDEX IDX_DAILY_TICKET_REFUND_PLATFORM_NO ON DAILY_TICKET_REFUND (PLATFORM_REFUND_NO);
