/*
 * 旅游票主子单闭环增量迁移。
 * 适用于已经执行 daily-ticket-server-schema.sql 的存量库。
 * Oracle 环境请按顺序执行；若某列/索引已存在，跳过对应语句。
 */

ALTER TABLE TRAVEL_TICKET_ORDER ADD (
    THIRD_USER_ID      VARCHAR2(64),
    PAY_AMOUNT         NUMBER(12),
    PAY_CHANNEL_CODE   VARCHAR2(16),
    CHANNEL_TYPE       VARCHAR2(8),
    PAY_SCENE          VARCHAR2(16),
    TRADE_NO           VARCHAR2(128),
    PAYMENT_ORDER_NO   VARCHAR2(128),
    PAY_DATE           TIMESTAMP
);

CREATE INDEX IDX_TRAVEL_TICKET_ORDER_PAYMENT
    ON TRAVEL_TICKET_ORDER (PAYMENT_ORDER_NO);

ALTER TABLE DAILY_TICKET_REFUND ADD (
    ORDER_TYPE         VARCHAR2(8) DEFAULT '1' NOT NULL,
    REFUND_SCOPE       VARCHAR2(16),
    PARENT_ORDER_NO    VARCHAR2(64),
    REFUND_REASON      VARCHAR2(256),
    OPERATOR           VARCHAR2(64)
);

CREATE INDEX IDX_DAILY_TICKET_REFUND_PARENT
    ON DAILY_TICKET_REFUND (PARENT_ORDER_NO);

CREATE TABLE DAILY_TICKET_REFUND_DETAIL (
    ID                 VARCHAR2(64) PRIMARY KEY,
    REFUND_ORDER_NO    VARCHAR2(64) NOT NULL,
    PARENT_ORDER_NO    VARCHAR2(64) NOT NULL,
    SUB_ORDER_NO       VARCHAR2(64) NOT NULL,
    REFUND_AMOUNT      NUMBER(12) NOT NULL,
    REFUND_STATUS      VARCHAR2(32) NOT NULL,
    CREATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE UNIQUE INDEX UK_DAILY_TICKET_REFUND_DETAIL
    ON DAILY_TICKET_REFUND_DETAIL (REFUND_ORDER_NO, SUB_ORDER_NO);
CREATE INDEX IDX_DAILY_TICKET_REFUND_DETAIL_PARENT
    ON DAILY_TICKET_REFUND_DETAIL (PARENT_ORDER_NO);
