CREATE SEQUENCE SEQ_DAILY_TICKET_USAGE_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE DAILY_TICKET_USAGE_LOG (
    ID               NUMBER(22) NOT NULL,
    CARD_NUM         VARCHAR2(64 CHAR) NOT NULL,
    ORDER_NO         VARCHAR2(128 CHAR),
    TXN_DATE         VARCHAR2(8 CHAR) NOT NULL,
    IN_STATION       VARCHAR2(32 CHAR),
    OUT_STATION      VARCHAR2(32 CHAR),
    TIMES_BEFORE     NUMBER(8),
    TIMES_AFTER      NUMBER(8),
    TICKET_STATUS    VARCHAR2(32 CHAR),
    CREATE_TIME      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DAILY_TICKET_USAGE_LOG PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_DTUL_ORDER ON DAILY_TICKET_USAGE_LOG (ORDER_NO);
CREATE INDEX IDX_DTUL_CARD ON DAILY_TICKET_USAGE_LOG (CARD_NUM, CREATE_TIME);

COMMENT ON TABLE DAILY_TICKET_USAGE_LOG IS '日票/计次票扣次使用明细表';
COMMENT ON COLUMN DAILY_TICKET_USAGE_LOG.ID IS '主键（SEQ_DAILY_TICKET_USAGE_LOG.NEXTVAL）';
COMMENT ON COLUMN DAILY_TICKET_USAGE_LOG.CARD_NUM IS '日票虚拟卡号';
COMMENT ON COLUMN DAILY_TICKET_USAGE_LOG.ORDER_NO IS '关联GATE_TXN_PAY.ORDER_NO，唯一索引做幂等';
COMMENT ON COLUMN DAILY_TICKET_USAGE_LOG.TXN_DATE IS '交易日期YYYYMMDD';
COMMENT ON COLUMN DAILY_TICKET_USAGE_LOG.IN_STATION IS '进站编码';
COMMENT ON COLUMN DAILY_TICKET_USAGE_LOG.OUT_STATION IS '出站编码';
COMMENT ON COLUMN DAILY_TICKET_USAGE_LOG.TIMES_BEFORE IS '扣前剩余次数';
COMMENT ON COLUMN DAILY_TICKET_USAGE_LOG.TIMES_AFTER IS '扣后剩余次数';
COMMENT ON COLUMN DAILY_TICKET_USAGE_LOG.TICKET_STATUS IS '扣后票状态';
COMMENT ON COLUMN DAILY_TICKET_USAGE_LOG.CREATE_TIME IS '创建时间';
