BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE DAILY_TICKET_REFUND ADD (
    NOTIFY_STATUS VARCHAR2(16),
    NOTIFY_TIMES  NUMBER(3),
    NOTIFY_TIME   TIMESTAMP(6),
    NOTIFY_MSG    VARCHAR2(500)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_DAILY_TICKET_REFUND_NOTIFY ON DAILY_TICKET_REFUND (NOTIFY_STATUS)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

COMMENT ON COLUMN DAILY_TICKET_REFUND.NOTIFY_STATUS IS 'IF8B-04退款结果通知APP的投递状态：PENDING待发/SUCCESS已受理/GIVEUP放弃重投，空表示无需通知';
COMMENT ON COLUMN DAILY_TICKET_REFUND.NOTIFY_TIMES IS '通知已投递次数，达到daily-ticket.notify.app.max-notify-times即置GIVEUP';
COMMENT ON COLUMN DAILY_TICKET_REFUND.NOTIFY_TIME IS '最近一次通知投递时刻';
COMMENT ON COLUMN DAILY_TICKET_REFUND.NOTIFY_MSG IS '最近一次通知失败原因，成功时清空';
