CREATE INDEX IDX_DAILY_TICKET_ORDER_BATCH_REFUND ON DAILY_TICKET_ORDER (ORDER_STATUS, PAY_STATUS, PAY_DATE);
CREATE INDEX IDX_TRAVEL_TICKET_ORDER_BATCH_REFUND ON TRAVEL_TICKET_ORDER (ORDER_STATUS, PAY_STATUS, PAY_DATE);
