-- IF8B-05 支付结果通知 APP 任务表。
-- 已有环境执行一次即可；新环境可直接使用 daily-ticket-server-schema.sql。
CREATE TABLE DAILY_TICKET_PAY_NOTIFY (
    ID                 VARCHAR2(64) PRIMARY KEY,
    ORDER_NO           VARCHAR2(64) NOT NULL,
    ORDER_TYPE         VARCHAR2(8) NOT NULL,
    PAY_RESULT         VARCHAR2(16) NOT NULL,
    PAYLOAD            CLOB,
    NOTIFY_STATUS      VARCHAR2(16),
    NOTIFY_TIMES       NUMBER(3),
    NOTIFY_TIME        TIMESTAMP(6),
    NOTIFY_MSG         VARCHAR2(500),
    CREATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE UNIQUE INDEX UK_DAILY_TICKET_PAY_NOTIFY_ORDER ON DAILY_TICKET_PAY_NOTIFY (ORDER_NO);
CREATE INDEX IDX_DAILY_TICKET_PAY_NOTIFY_STATUS ON DAILY_TICKET_PAY_NOTIFY (NOTIFY_STATUS);

COMMENT ON TABLE DAILY_TICKET_PAY_NOTIFY IS 'IF8B-05支付结果通知APP任务表';
COMMENT ON COLUMN DAILY_TICKET_PAY_NOTIFY.ID IS '主键ID';
COMMENT ON COLUMN DAILY_TICKET_PAY_NOTIFY.ORDER_NO IS '日票订单号或旅游票主单号';
COMMENT ON COLUMN DAILY_TICKET_PAY_NOTIFY.ORDER_TYPE IS '订单类型：1日票，2旅游票';
COMMENT ON COLUMN DAILY_TICKET_PAY_NOTIFY.PAY_RESULT IS '通知APP的支付结果：SUCCESS/FAIL';
COMMENT ON COLUMN DAILY_TICKET_PAY_NOTIFY.PAYLOAD IS 'IF8B-05 bizData原始JSON字符串';
COMMENT ON COLUMN DAILY_TICKET_PAY_NOTIFY.NOTIFY_STATUS IS 'IF8B-05支付结果通知APP的投递状态：PENDING待发/SUCCESS已受理/GIVEUP放弃重投';
COMMENT ON COLUMN DAILY_TICKET_PAY_NOTIFY.NOTIFY_TIMES IS '通知已投递次数，达到daily-ticket.notify.app.max-notify-times即置GIVEUP';
COMMENT ON COLUMN DAILY_TICKET_PAY_NOTIFY.NOTIFY_TIME IS '最近一次通知投递时刻';
COMMENT ON COLUMN DAILY_TICKET_PAY_NOTIFY.NOTIFY_MSG IS '最近一次通知失败原因，成功时清空';
COMMENT ON COLUMN DAILY_TICKET_PAY_NOTIFY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DAILY_TICKET_PAY_NOTIFY.UPDATE_TIME IS '更新时间';
