-- 二维码闸机交易明细表
-- Oracle 月分区表，TXN_DATE 使用字符串 YYYYMMDD 入库。
-- 注意：本表按 TXN_DATE 手动维护月分区，P_MAX 仅作为兜底分区。
-- 建议每月提前创建后续月份分区，避免正常交易数据长期写入 P_MAX。

CREATE TABLE QRCODE_TXN_DETAIL (
    ID                        NUMBER(20) NOT NULL,
    DEVICE_ID                 VARCHAR2(16 CHAR),

    ITP_USER_ID               VARCHAR2(64 CHAR),
    TRX_TYPE                  VARCHAR2(4 CHAR) NOT NULL,
    ISSUE_CHANNEL_CODE        VARCHAR2(8 CHAR),
    SIGN_CHANNEL_CODE         VARCHAR2(8 CHAR),
    CARD_ID                   VARCHAR2(32 CHAR) NOT NULL,
    CARD_TYPE                 VARCHAR2(8 CHAR),
    HANDLE_DATE_TIME          VARCHAR2(14 CHAR) NOT NULL,
    TXN_DATE                  VARCHAR2(8 CHAR) NOT NULL,
    HANDLE_STATION_CODE       VARCHAR2(16 CHAR),
    TRX_AMOUNT                NUMBER(12),
    OVERTIME_AMOUNT           NUMBER(12),
    LAST_TICKET_STATUS        VARCHAR2(4 CHAR),
    HANDLE_RESULT_CODE        VARCHAR2(8 CHAR),
    LAST_HANDLE_STATION_CODE  VARCHAR2(16 CHAR),
    LAST_HANDLE_DATE_TIME     VARCHAR2(14 CHAR),
    TICKET_TRANS_SEQ          VARCHAR2(64 CHAR),
    RESERVE1                  VARCHAR2(512 CHAR),
    RESERVE2                  VARCHAR2(512 CHAR),

    CREATE_TIME               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_QRCODE_TXN_DETAIL PRIMARY KEY (ID)
)
PARTITION BY RANGE (TXN_DATE) (
    PARTITION P202606 VALUES LESS THAN ('20260701'),
    PARTITION P202607 VALUES LESS THAN ('20260801'),
    PARTITION P202608 VALUES LESS THAN ('20260901'),
    PARTITION P202609 VALUES LESS THAN ('20261001'),
    PARTITION P202610 VALUES LESS THAN ('20261101'),
    PARTITION P202611 VALUES LESS THAN ('20261201'),
    PARTITION P202612 VALUES LESS THAN ('20270101'),
    PARTITION P_MAX VALUES LESS THAN (MAXVALUE)
);

CREATE SEQUENCE SEQ_QRCODE_TXN_DETAIL
    START WITH 1
    INCREMENT BY 1
    CACHE 1000
    NOCYCLE;

-- 交易幂等唯一索引。
-- Oracle 本地唯一索引必须包含分区键，因此包含 TXN_DATE。
CREATE UNIQUE INDEX UK_QRCODE_TXN_DETAIL_BIZ
ON QRCODE_TXN_DETAIL (
    CARD_ID,
    TRX_TYPE,
    HANDLE_DATE_TIME,
    TICKET_TRANS_SEQ,
    DEVICE_ID,
    TXN_DATE
)
LOCAL;

-- 按卡号查询交易明细，查询时应带 TXN_DATE 范围以触发分区裁剪。
CREATE INDEX IDX_QRCODE_TXN_DETAIL_CARD_DATE
ON QRCODE_TXN_DETAIL (
    CARD_ID,
    TXN_DATE,
    HANDLE_DATE_TIME
)
LOCAL;

-- 按设备查询交易明细或排查设备重复上送、漏传问题。
CREATE INDEX IDX_QRCODE_TXN_DETAIL_DEVICE_DATE
ON QRCODE_TXN_DETAIL (
    DEVICE_ID,
    TXN_DATE,
    HANDLE_DATE_TIME
)
LOCAL;

-- 按 ITP 用户查询交易明细。
CREATE INDEX IDX_QRCODE_TXN_DETAIL_USER_DATE
ON QRCODE_TXN_DETAIL (
    ITP_USER_ID,
    TXN_DATE,
    HANDLE_DATE_TIME
)
LOCAL;

COMMENT ON TABLE QRCODE_TXN_DETAIL IS '二维码闸机交易明细表';

COMMENT ON COLUMN QRCODE_TXN_DETAIL.ID IS '主键ID';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.DEVICE_ID IS '设备ID，公共请求参数';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.ITP_USER_ID IS 'ITP用户编码，二维码中数据';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.TRX_TYPE IS '交易类型：01进站，02出站，03超时出站';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.ISSUE_CHANNEL_CODE IS '发行渠道代码';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.SIGN_CHANNEL_CODE IS '签约通道代码';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.CARD_ID IS '逻辑卡号';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.CARD_TYPE IS '票卡类型';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.HANDLE_DATE_TIME IS '闸机交易时间，格式YYYYMMDDHH24MISS';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.TXN_DATE IS '交易日期，取HANDLE_DATE_TIME前8位，格式YYYYMMDD，用于月分区';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.HANDLE_STATION_CODE IS '闸机交易车站代码';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.TRX_AMOUNT IS '实际交易金额，单位分';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.OVERTIME_AMOUNT IS '超时金额，单位分';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.LAST_TICKET_STATUS IS '上次票卡状态';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.HANDLE_RESULT_CODE IS '闸机处理结果码';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.LAST_HANDLE_STATION_CODE IS '上次交易车站代码';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.LAST_HANDLE_DATE_TIME IS '上次交易时间，格式YYYYMMDDHH24MISS';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.TICKET_TRANS_SEQ IS '二维码交易计数器，文档字段名为tikcetTransSeq';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.RESERVE1 IS '预留字段1';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.RESERVE2 IS '预留字段2';
COMMENT ON COLUMN QRCODE_TXN_DETAIL.CREATE_TIME IS '创建时间';

-- 后续月分区维护示例：
--
-- 1. 新增 2027 年 1 月分区。
--    P202701 覆盖范围：20270101 <= TXN_DATE < 20270201
--
-- ALTER TABLE QRCODE_TXN_DETAIL
-- SPLIT PARTITION P_MAX
-- AT ('20270201')
-- INTO (
--     PARTITION P202701,
--     PARTITION P_MAX
-- );
--
-- 2. 新增 2027 年 2 月分区。
--    P202702 覆盖范围：20270201 <= TXN_DATE < 20270301
--
-- ALTER TABLE QRCODE_TXN_DETAIL
-- SPLIT PARTITION P_MAX
-- AT ('20270301')
-- INTO (
--     PARTITION P202702,
--     PARTITION P_MAX
-- );
--
-- 3. 查询分区情况。
--
-- SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE
-- FROM USER_TAB_PARTITIONS
-- WHERE TABLE_NAME = 'QRCODE_TXN_DETAIL'
-- ORDER BY PARTITION_POSITION;
--
-- 4. 删除历史月份分区示例：删除 2026 年 6 月交易明细。
--    执行前务必确认历史数据已归档或无需保留。
--
-- ALTER TABLE QRCODE_TXN_DETAIL DROP PARTITION P202606 UPDATE INDEXES;
--
-- 5. 推荐查询写法：按卡号查询时同时带 TXN_DATE 范围，确保命中分区裁剪。
--
-- SELECT *
-- FROM QRCODE_TXN_DETAIL
-- WHERE CARD_ID = :cardId
--   AND TXN_DATE >= :beginDate
--   AND TXN_DATE <  :endDate
-- ORDER BY HANDLE_DATE_TIME DESC;
