package com.chinasofti.huateng.acc.es.server.model;

import java.io.Serializable;
import lombok.Data;

/**
 * @TableName TBL_TKT_PRE_PERSON
 */
@Data
public class TblTktPrePerson implements Serializable {
    /**
     * 任务编号
     *
     * @mbg.generated Wed Apr 21 16:30:40 CST 2021
     */
    private Integer taskNo;

    /**
     * 物理卡号
     *
     * @mbg.generated Wed Apr 21 16:30:40 CST 2021
     */
    private String phyCode;
    /**
     * 用户类型
     *
     * @mbg.generated Wed Apr 21 16:30:40 CST 2021
     */
    private String personType;

    /**
     * 用户名称
     *
     * @mbg.generated Wed Apr 21 16:30:40 CST 2021
     */
    private String userName;

    /**
     * 卡类型
     *
     * @mbg.generated Wed Apr 21 16:30:40 CST 2021
     */
    private String idType;

    /**
     * 卡id
     *
     * @mbg.generated Wed Apr 21 16:30:40 CST 2021
     */
    private String id;

    /**
     * 员工编号
     *
     * @mbg.generated Wed Apr 21 16:30:40 CST 2021
     */
    private String empNo;

    /**
     * 工作单位
     *
     * @mbg.generated Wed Apr 21 16:30:40 CST 2021
     */
    private String workUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_TKT_PRE_PERSON
     *
     * @mbg.generated Wed Apr 21 16:30:40 CST 2021
     */
    private static final long serialVersionUID = 1L;
}