package com.chinasofti.huateng.acc.es.server.model;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @TableName TBL_STL_PERSON_INFO
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class TblStlPersonInfo implements Serializable {
    /**
     * 主键，票卡id，逻辑id
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String ticketId;

    /**
     * 用户名
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String personName;

    /**
     * 性别
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String personSex;

    /**
     * 卡类型
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String pidCd;

    /**
     * 卡号
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String pidCode;

    /**
     * 密码
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String passwd;

    /**
     * 语言类别
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String langCd;

    /**
     * 工作单位
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String companyNm;

    /**
     * 员工号
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String empNo;

    /**
     * 联系电话
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String conTelNo;

    /**
     * 联系邮箱
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String conMail;

    /**
     * 地址
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String address;

    /**
     * 邮编
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String postCd;

    /**
     * 最后更新者
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private String lastUpdUser;

    /**
     * 更新时间
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private Date lastUpdTms;

    /**
     * 照片
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private byte[] photoBlob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_STL_PERSON_INFO
     *
     * @mbg.generated Tue Jan 26 09:52:32 CST 2021
     */
    private static final long serialVersionUID = 1L;
}