apiVersion: v1
kind: Secret
metadata:
  name: itp-secrets
  namespace: itp
type: Opaque
stringData:
  CARD_POOL_FTP_PASSWORD: ''
  DB_PASSWORD: ''
  ENTROPY_MCP_DATABASE_CONNECTIONS_QDITP_PASSWORD: ''
  JHM_KEY: ''
  MCP_SECURITY_ADMIN_PASSWORD: ''
  RECON_FTP_PASSWORD: ''
  RECON_INTERNAL_TOKEN: ''
  acc.3des.key: ''
  app.signKey: ''
  appserver.3des.key: ''
  ftp.password: ''
  itp.signKey: ''
  jhm.key: ''
  other.sql.password: ''
  para.ftp.password: ''
  pay.center.merchant-private-key: ''
  pay.center.paycenter-public-key: ''
  security.privateKey: ''
  security.publicKey: ''
  spring.datasource.druid.master.password: ''
  spring.datasource.druid.statViewServlet.login-password: ''
  spring.datasource.password: ''
  token.secret: ''
