-- Quartz JDBC JobStore schema for Oracle.
-- Compatible with Oracle 12c and later.

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QRTZ_FIRED_TRIGGERS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QRTZ_PAUSED_TRIGGER_GRPS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QRTZ_SCHEDULER_STATE CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QRTZ_LOCKS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QRTZ_SIMPLE_TRIGGERS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QRTZ_SIMPROP_TRIGGERS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QRTZ_CRON_TRIGGERS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QRTZ_BLOB_TRIGGERS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QRTZ_TRIGGERS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QRTZ_JOB_DETAILS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE QRTZ_CALENDARS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE QRTZ_JOB_DETAILS (
    SCHED_NAME        VARCHAR2(120 CHAR) NOT NULL,
    JOB_NAME          VARCHAR2(200 CHAR) NOT NULL,
    JOB_GROUP         VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION       VARCHAR2(250 CHAR),
    JOB_CLASS_NAME    VARCHAR2(250 CHAR) NOT NULL,
    IS_DURABLE        VARCHAR2(1 CHAR) NOT NULL,
    IS_NONCONCURRENT  VARCHAR2(1 CHAR) NOT NULL,
    IS_UPDATE_DATA    VARCHAR2(1 CHAR) NOT NULL,
    REQUESTS_RECOVERY VARCHAR2(1 CHAR) NOT NULL,
    JOB_DATA          BLOB,
    CONSTRAINT PK_QRTZ_JOB_DETAILS PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

CREATE TABLE QRTZ_TRIGGERS (
    SCHED_NAME     VARCHAR2(120 CHAR) NOT NULL,
    TRIGGER_NAME   VARCHAR2(200 CHAR) NOT NULL,
    TRIGGER_GROUP  VARCHAR2(200 CHAR) NOT NULL,
    JOB_NAME       VARCHAR2(200 CHAR) NOT NULL,
    JOB_GROUP      VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION    VARCHAR2(250 CHAR),
    NEXT_FIRE_TIME NUMBER(13),
    PREV_FIRE_TIME NUMBER(13),
    PRIORITY       NUMBER(10),
    TRIGGER_STATE  VARCHAR2(16 CHAR) NOT NULL,
    TRIGGER_TYPE   VARCHAR2(8 CHAR) NOT NULL,
    START_TIME     NUMBER(13) NOT NULL,
    END_TIME       NUMBER(13),
    CALENDAR_NAME  VARCHAR2(200 CHAR),
    MISFIRE_INSTR  NUMBER(5),
    JOB_DATA       BLOB,
    CONSTRAINT PK_QRTZ_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT FK_QRTZ_TRIGGERS_JOB FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
        REFERENCES QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
    SCHED_NAME      VARCHAR2(120 CHAR) NOT NULL,
    TRIGGER_NAME    VARCHAR2(200 CHAR) NOT NULL,
    TRIGGER_GROUP   VARCHAR2(200 CHAR) NOT NULL,
    REPEAT_COUNT    NUMBER(7) NOT NULL,
    REPEAT_INTERVAL NUMBER(12) NOT NULL,
    TIMES_TRIGGERED NUMBER(10) NOT NULL,
    CONSTRAINT PK_QRTZ_SIMPLE_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT FK_QRTZ_SIMPLE_TRIGGER FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE QRTZ_CRON_TRIGGERS (
    SCHED_NAME      VARCHAR2(120 CHAR) NOT NULL,
    TRIGGER_NAME    VARCHAR2(200 CHAR) NOT NULL,
    TRIGGER_GROUP   VARCHAR2(200 CHAR) NOT NULL,
    CRON_EXPRESSION VARCHAR2(200 CHAR) NOT NULL,
    TIME_ZONE_ID    VARCHAR2(80 CHAR),
    CONSTRAINT PK_QRTZ_CRON_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT FK_QRTZ_CRON_TRIGGER FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE QRTZ_BLOB_TRIGGERS (
    SCHED_NAME    VARCHAR2(120 CHAR) NOT NULL,
    TRIGGER_NAME  VARCHAR2(200 CHAR) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200 CHAR) NOT NULL,
    BLOB_DATA     BLOB,
    CONSTRAINT PK_QRTZ_BLOB_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT FK_QRTZ_BLOB_TRIGGER FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE QRTZ_CALENDARS (
    SCHED_NAME    VARCHAR2(120 CHAR) NOT NULL,
    CALENDAR_NAME VARCHAR2(200 CHAR) NOT NULL,
    CALENDAR      BLOB NOT NULL,
    CONSTRAINT PK_QRTZ_CALENDARS PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
    SCHED_NAME    VARCHAR2(120 CHAR) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200 CHAR) NOT NULL,
    CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);

CREATE TABLE QRTZ_FIRED_TRIGGERS (
    SCHED_NAME        VARCHAR2(120 CHAR) NOT NULL,
    ENTRY_ID          VARCHAR2(95 CHAR) NOT NULL,
    TRIGGER_NAME      VARCHAR2(200 CHAR) NOT NULL,
    TRIGGER_GROUP     VARCHAR2(200 CHAR) NOT NULL,
    INSTANCE_NAME     VARCHAR2(200 CHAR) NOT NULL,
    FIRED_TIME        NUMBER(13) NOT NULL,
    SCHED_TIME        NUMBER(13) NOT NULL,
    PRIORITY          NUMBER(10) NOT NULL,
    STATE             VARCHAR2(16 CHAR) NOT NULL,
    JOB_NAME          VARCHAR2(200 CHAR),
    JOB_GROUP         VARCHAR2(200 CHAR),
    IS_NONCONCURRENT  VARCHAR2(1 CHAR),
    REQUESTS_RECOVERY VARCHAR2(1 CHAR),
    CONSTRAINT PK_QRTZ_FIRED_TRIGGERS PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);

CREATE TABLE QRTZ_SCHEDULER_STATE (
    SCHED_NAME        VARCHAR2(120 CHAR) NOT NULL,
    INSTANCE_NAME     VARCHAR2(200 CHAR) NOT NULL,
    LAST_CHECKIN_TIME NUMBER(13) NOT NULL,
    CHECKIN_INTERVAL  NUMBER(13) NOT NULL,
    CONSTRAINT PK_QRTZ_SCHEDULER_STATE PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);

CREATE TABLE QRTZ_LOCKS (
    SCHED_NAME VARCHAR2(120 CHAR) NOT NULL,
    LOCK_NAME  VARCHAR2(40 CHAR) NOT NULL,
    CONSTRAINT PK_QRTZ_LOCKS PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);

CREATE TABLE QRTZ_SIMPROP_TRIGGERS (
    SCHED_NAME    VARCHAR2(120 CHAR) NOT NULL,
    TRIGGER_NAME  VARCHAR2(200 CHAR) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200 CHAR) NOT NULL,
    STR_PROP_1    VARCHAR2(512 CHAR),
    STR_PROP_2    VARCHAR2(512 CHAR),
    STR_PROP_3    VARCHAR2(512 CHAR),
    INT_PROP_1    NUMBER(10),
    INT_PROP_2    NUMBER(10),
    LONG_PROP_1   NUMBER(19),
    LONG_PROP_2   NUMBER(19),
    DEC_PROP_1    NUMBER(13, 4),
    DEC_PROP_2    NUMBER(13, 4),
    BOOL_PROP_1   VARCHAR2(1 CHAR),
    BOOL_PROP_2   VARCHAR2(1 CHAR),
    CONSTRAINT PK_QRTZ_SIMPROP_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT FK_QRTZ_SIMPROP_TRIGGER FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

COMMENT ON TABLE QRTZ_JOB_DETAILS IS 'Quartz任务详细信息表';
COMMENT ON COLUMN QRTZ_JOB_DETAILS.SCHED_NAME IS '调度名称';
COMMENT ON COLUMN QRTZ_JOB_DETAILS.JOB_NAME IS '任务名称';
COMMENT ON COLUMN QRTZ_JOB_DETAILS.JOB_GROUP IS '任务组名';
COMMENT ON COLUMN QRTZ_JOB_DETAILS.DESCRIPTION IS '相关介绍';
COMMENT ON COLUMN QRTZ_JOB_DETAILS.JOB_CLASS_NAME IS '执行任务类名称';
COMMENT ON COLUMN QRTZ_JOB_DETAILS.IS_DURABLE IS '是否持久化';
COMMENT ON COLUMN QRTZ_JOB_DETAILS.IS_NONCONCURRENT IS '是否并发';
COMMENT ON COLUMN QRTZ_JOB_DETAILS.IS_UPDATE_DATA IS '是否更新数据';
COMMENT ON COLUMN QRTZ_JOB_DETAILS.REQUESTS_RECOVERY IS '是否接受恢复执行';
COMMENT ON COLUMN QRTZ_JOB_DETAILS.JOB_DATA IS '存放持久化job对象';

COMMENT ON TABLE QRTZ_TRIGGERS IS 'Quartz触发器详细信息表';
COMMENT ON COLUMN QRTZ_TRIGGERS.SCHED_NAME IS '调度名称';
COMMENT ON COLUMN QRTZ_TRIGGERS.TRIGGER_NAME IS '触发器名称';
COMMENT ON COLUMN QRTZ_TRIGGERS.TRIGGER_GROUP IS '触发器所属组名称';
COMMENT ON COLUMN QRTZ_TRIGGERS.JOB_NAME IS 'QRTZ_JOB_DETAILS表JOB_NAME的外键';
COMMENT ON COLUMN QRTZ_TRIGGERS.JOB_GROUP IS 'QRTZ_JOB_DETAILS表JOB_GROUP的外键';
COMMENT ON COLUMN QRTZ_TRIGGERS.DESCRIPTION IS '相关介绍';
COMMENT ON COLUMN QRTZ_TRIGGERS.NEXT_FIRE_TIME IS '下一次触发时间，毫秒';
COMMENT ON COLUMN QRTZ_TRIGGERS.PREV_FIRE_TIME IS '上一次触发时间，毫秒';
COMMENT ON COLUMN QRTZ_TRIGGERS.PRIORITY IS '优先级';
COMMENT ON COLUMN QRTZ_TRIGGERS.TRIGGER_STATE IS '触发器状态';
COMMENT ON COLUMN QRTZ_TRIGGERS.TRIGGER_TYPE IS '触发器类型';
COMMENT ON COLUMN QRTZ_TRIGGERS.START_TIME IS '开始时间，毫秒';
COMMENT ON COLUMN QRTZ_TRIGGERS.END_TIME IS '结束时间，毫秒';
COMMENT ON COLUMN QRTZ_TRIGGERS.CALENDAR_NAME IS '日程表名称';
COMMENT ON COLUMN QRTZ_TRIGGERS.MISFIRE_INSTR IS '补偿执行策略';
COMMENT ON COLUMN QRTZ_TRIGGERS.JOB_DATA IS '存放持久化job对象';

COMMENT ON TABLE QRTZ_SIMPLE_TRIGGERS IS 'Quartz简单触发器信息表';
COMMENT ON COLUMN QRTZ_SIMPLE_TRIGGERS.SCHED_NAME IS '调度名称';
COMMENT ON COLUMN QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME IS 'QRTZ_TRIGGERS表TRIGGER_NAME的外键';
COMMENT ON COLUMN QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP IS 'QRTZ_TRIGGERS表TRIGGER_GROUP的外键';
COMMENT ON COLUMN QRTZ_SIMPLE_TRIGGERS.REPEAT_COUNT IS '重复次数统计';
COMMENT ON COLUMN QRTZ_SIMPLE_TRIGGERS.REPEAT_INTERVAL IS '重复间隔时间，毫秒';
COMMENT ON COLUMN QRTZ_SIMPLE_TRIGGERS.TIMES_TRIGGERED IS '已触发次数';

COMMENT ON TABLE QRTZ_CRON_TRIGGERS IS 'Quartz Cron触发器表';
COMMENT ON COLUMN QRTZ_CRON_TRIGGERS.SCHED_NAME IS '调度名称';
COMMENT ON COLUMN QRTZ_CRON_TRIGGERS.TRIGGER_NAME IS 'QRTZ_TRIGGERS表TRIGGER_NAME的外键';
COMMENT ON COLUMN QRTZ_CRON_TRIGGERS.TRIGGER_GROUP IS 'QRTZ_TRIGGERS表TRIGGER_GROUP的外键';
COMMENT ON COLUMN QRTZ_CRON_TRIGGERS.CRON_EXPRESSION IS 'Cron表达式';
COMMENT ON COLUMN QRTZ_CRON_TRIGGERS.TIME_ZONE_ID IS '时区';

COMMENT ON TABLE QRTZ_BLOB_TRIGGERS IS 'Quartz Blob触发器表';
COMMENT ON COLUMN QRTZ_BLOB_TRIGGERS.SCHED_NAME IS '调度名称';
COMMENT ON COLUMN QRTZ_BLOB_TRIGGERS.TRIGGER_NAME IS 'QRTZ_TRIGGERS表TRIGGER_NAME的外键';
COMMENT ON COLUMN QRTZ_BLOB_TRIGGERS.TRIGGER_GROUP IS 'QRTZ_TRIGGERS表TRIGGER_GROUP的外键';
COMMENT ON COLUMN QRTZ_BLOB_TRIGGERS.BLOB_DATA IS '存放持久化Trigger对象';

COMMENT ON TABLE QRTZ_CALENDARS IS 'Quartz日历信息表';
COMMENT ON COLUMN QRTZ_CALENDARS.SCHED_NAME IS '调度名称';
COMMENT ON COLUMN QRTZ_CALENDARS.CALENDAR_NAME IS '日历名称';
COMMENT ON COLUMN QRTZ_CALENDARS.CALENDAR IS '存放持久化Calendar对象';

COMMENT ON TABLE QRTZ_PAUSED_TRIGGER_GRPS IS 'Quartz暂停触发器组表';
COMMENT ON COLUMN QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME IS '调度名称';
COMMENT ON COLUMN QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP IS 'QRTZ_TRIGGERS表TRIGGER_GROUP的外键';

COMMENT ON TABLE QRTZ_FIRED_TRIGGERS IS 'Quartz已触发触发器表';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.SCHED_NAME IS '调度名称';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.ENTRY_ID IS '调度器实例ID';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.TRIGGER_NAME IS 'QRTZ_TRIGGERS表TRIGGER_NAME的外键';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.TRIGGER_GROUP IS 'QRTZ_TRIGGERS表TRIGGER_GROUP的外键';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.INSTANCE_NAME IS '调度器实例名称';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.FIRED_TIME IS '触发时间，毫秒';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.SCHED_TIME IS '计划触发时间，毫秒';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.PRIORITY IS '优先级';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.STATE IS '状态';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.JOB_NAME IS '任务名称';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.JOB_GROUP IS '任务组名';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.IS_NONCONCURRENT IS '是否并发';
COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.REQUESTS_RECOVERY IS '是否接受恢复执行';

COMMENT ON TABLE QRTZ_SCHEDULER_STATE IS 'Quartz调度器状态表';
COMMENT ON COLUMN QRTZ_SCHEDULER_STATE.SCHED_NAME IS '调度名称';
COMMENT ON COLUMN QRTZ_SCHEDULER_STATE.INSTANCE_NAME IS '实例名称';
COMMENT ON COLUMN QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME IS '上次检查时间，毫秒';
COMMENT ON COLUMN QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL IS '检查间隔，毫秒';

COMMENT ON TABLE QRTZ_LOCKS IS 'Quartz悲观锁表';
COMMENT ON COLUMN QRTZ_LOCKS.SCHED_NAME IS '调度名称';
COMMENT ON COLUMN QRTZ_LOCKS.LOCK_NAME IS '悲观锁名称';

COMMENT ON TABLE QRTZ_SIMPROP_TRIGGERS IS 'Quartz同步属性触发器表';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.SCHED_NAME IS '调度名称';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.TRIGGER_NAME IS 'QRTZ_TRIGGERS表TRIGGER_NAME的外键';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.TRIGGER_GROUP IS 'QRTZ_TRIGGERS表TRIGGER_GROUP的外键';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.STR_PROP_1 IS 'String类型Trigger的第一个参数';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.STR_PROP_2 IS 'String类型Trigger的第二个参数';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.STR_PROP_3 IS 'String类型Trigger的第三个参数';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.INT_PROP_1 IS 'int类型Trigger的第一个参数';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.INT_PROP_2 IS 'int类型Trigger的第二个参数';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.LONG_PROP_1 IS 'long类型Trigger的第一个参数';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.LONG_PROP_2 IS 'long类型Trigger的第二个参数';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.DEC_PROP_1 IS 'decimal类型Trigger的第一个参数';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.DEC_PROP_2 IS 'decimal类型Trigger的第二个参数';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_1 IS 'Boolean类型Trigger的第一个参数';
COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_2 IS 'Boolean类型Trigger的第二个参数';

COMMIT;
