
UPDATE SYS_MENU SET ROUTE_NAME = 'DailyTicketRefundRecord'    WHERE MENU_ID = 2006;
UPDATE SYS_MENU SET ROUTE_NAME = 'FacePayOrder'               WHERE MENU_ID = 2007;
UPDATE SYS_MENU SET ROUTE_NAME = 'BaseFare'                   WHERE MENU_ID = 2008;
UPDATE SYS_MENU SET ROUTE_NAME = 'OrderRefundCycle'           WHERE MENU_ID = 2009;
UPDATE SYS_MENU SET ROUTE_NAME = 'BlacklistManagement'        WHERE MENU_ID = 2013;
UPDATE SYS_MENU SET ROUTE_NAME = 'RiskGroup'                  WHERE MENU_ID = 2016;
UPDATE SYS_MENU SET ROUTE_NAME = 'RiskRule'                   WHERE MENU_ID = 2020;
UPDATE SYS_MENU SET ROUTE_NAME = 'RiskControlLog'             WHERE MENU_ID = 2024;
UPDATE SYS_MENU SET ROUTE_NAME = 'LineInfo'                   WHERE MENU_ID = 2026;
UPDATE SYS_MENU SET ROUTE_NAME = 'StationInfo'                WHERE MENU_ID = 2027;
UPDATE SYS_MENU SET ROUTE_NAME = 'LineStationVersion'         WHERE MENU_ID = 2028;
UPDATE SYS_MENU SET ROUTE_NAME = 'DailyTicketRefund'          WHERE MENU_ID = 2029;
UPDATE SYS_MENU SET ROUTE_NAME = 'AlipayUserSearch'           WHERE MENU_ID = 2072;
UPDATE SYS_MENU SET ROUTE_NAME = 'ItpUserSearch'              WHERE MENU_ID = 2073;
UPDATE SYS_MENU SET ROUTE_NAME = 'SingleTicketPurchaseLimit'  WHERE MENU_ID = 2075;
UPDATE SYS_MENU SET ROUTE_NAME = 'CardPoolManagement'         WHERE MENU_ID = 2078;

DELETE FROM SYS_ROLE_MENU WHERE MENU_ID = 2030;
DELETE FROM SYS_MENU      WHERE MENU_ID = 2045;
DELETE FROM SYS_MENU      WHERE MENU_ID = 2030;
DELETE FROM SYS_MENU      WHERE MENU_ID = 2005;
COMMIT;



DELETE FROM SYS_MENU WHERE MENU_ID IN (2041,2043,2044,2048,2049,2053,2057,2061,2062,2066,2070)
  AND MENU_TYPE = 'F' AND NOT EXISTS (SELECT 1 FROM SYS_ROLE_MENU rm WHERE rm.MENU_ID = SYS_MENU.MENU_ID);
-- 第二组：同一父菜单下同 perms 的两条 F，保留先建的（2010~2012 / 2017~2019 / 2021~2023 / 2025），删后建的。
DELETE FROM SYS_MENU WHERE MENU_ID IN (2042,2050,2051,2052,2054,2055,2056,2058,2059,2060)
  AND MENU_TYPE = 'F' AND NOT EXISTS (SELECT 1 FROM SYS_ROLE_MENU rm WHERE rm.MENU_ID = SYS_MENU.MENU_ID);
COMMIT;



