CREATE TABLE DAILY_TICKET_ORDER (
    ID                 VARCHAR2(64) PRIMARY KEY,
    ORDER_NO           VARCHAR2(64) NOT NULL UNIQUE,
    ORDER_TYPE         VARCHAR2(8) DEFAULT '1' NOT NULL,
    THIRD_USER_ID      VARCHAR2(64),
    USER_ID            VARCHAR2(64),
    ORDER_SOURCE       VARCHAR2(8),
    CARD_TYPE          VARCHAR2(16),
    SHOW_TYPE          VARCHAR2(16),
    TICKET_NAME        VARCHAR2(128),
    TICKET_PRICE       NUMBER(12),
    PAY_AMOUNT         NUMBER(12),
    PAY_CHANNEL_CODE   VARCHAR2(16),
    CHANNEL_TYPE       VARCHAR2(8),
    PAY_SCENE          VARCHAR2(16),
    ORDER_STATUS       VARCHAR2(32) NOT NULL,
    PAY_STATUS         VARCHAR2(32),
    TRADE_NO           VARCHAR2(128),
    PAYMENT_ORDER_NO   VARCHAR2(128),
    PAY_DATE           TIMESTAMP,
    CREATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_DAILY_TICKET_ORDER_USER ON DAILY_TICKET_ORDER (THIRD_USER_ID, USER_ID);
CREATE INDEX IDX_DAILY_TICKET_ORDER_STATUS ON DAILY_TICKET_ORDER (ORDER_STATUS, PAY_STATUS);

COMMENT ON TABLE DAILY_TICKET_ORDER IS '日票订单表';
COMMENT ON COLUMN DAILY_TICKET_ORDER.ID IS '主键ID';
COMMENT ON COLUMN DAILY_TICKET_ORDER.ORDER_NO IS '日票订单号';
COMMENT ON COLUMN DAILY_TICKET_ORDER.ORDER_TYPE IS '订单类型，日票固定为1';
COMMENT ON COLUMN DAILY_TICKET_ORDER.THIRD_USER_ID IS '第三方用户编号';
COMMENT ON COLUMN DAILY_TICKET_ORDER.USER_ID IS 'APP用户编号';
COMMENT ON COLUMN DAILY_TICKET_ORDER.ORDER_SOURCE IS '订单来源';
COMMENT ON COLUMN DAILY_TICKET_ORDER.CARD_TYPE IS 'APP侧卡类型，日票生码时码体票种仍固定为0441';
COMMENT ON COLUMN DAILY_TICKET_ORDER.SHOW_TYPE IS '展示票类型';
COMMENT ON COLUMN DAILY_TICKET_ORDER.TICKET_NAME IS '车票名称';
COMMENT ON COLUMN DAILY_TICKET_ORDER.TICKET_PRICE IS '票价，单位分';
COMMENT ON COLUMN DAILY_TICKET_ORDER.PAY_AMOUNT IS '实付金额，单位分';
COMMENT ON COLUMN DAILY_TICKET_ORDER.PAY_CHANNEL_CODE IS '支付渠道编码';
COMMENT ON COLUMN DAILY_TICKET_ORDER.CHANNEL_TYPE IS 'APP支付场景来源，1转app，2转wap';
COMMENT ON COLUMN DAILY_TICKET_ORDER.PAY_SCENE IS '支付服务scene字段';
COMMENT ON COLUMN DAILY_TICKET_ORDER.ORDER_STATUS IS '订单状态：CREATED/PAYING/PAID/CANCELED/REFUNDING/REFUNDED等';
COMMENT ON COLUMN DAILY_TICKET_ORDER.PAY_STATUS IS '支付状态：INIT/PAYING/PAID/FAIL等';
COMMENT ON COLUMN DAILY_TICKET_ORDER.TRADE_NO IS '第三方支付交易号';
COMMENT ON COLUMN DAILY_TICKET_ORDER.PAYMENT_ORDER_NO IS '支付系统订单号';
COMMENT ON COLUMN DAILY_TICKET_ORDER.PAY_DATE IS '支付完成时间';
COMMENT ON COLUMN DAILY_TICKET_ORDER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DAILY_TICKET_ORDER.UPDATE_TIME IS '更新时间';

CREATE TABLE DAILY_TICKET_INSTANCE (
    ID                 VARCHAR2(64) PRIMARY KEY,
    ORDER_NO           VARCHAR2(64) NOT NULL,
    THIRD_USER_ID      VARCHAR2(64),
    CARD_NUM           VARCHAR2(64),
    CARD_ISSUE         VARCHAR2(32),
    APP_CARD_TYPE      VARCHAR2(16),
    CODE_TICKET_TYPE   VARCHAR2(16) DEFAULT '0441' NOT NULL,
    TICKET_TYPE        VARCHAR2(16),
    SHOW_TYPE          VARCHAR2(16),
    TICKET_CODE        VARCHAR2(64),
    TICKET_NAME        VARCHAR2(128),
    PERIOD             NUMBER(4),
    ACTUAL_TIMES       NUMBER(8),
    TRANS_SEQ          NUMBER(12),
    TRANS_AMOUNT       NUMBER(12),
    DISCOUNT_AMOUNT    NUMBER(12),
    PAY_CHANNEL        VARCHAR2(16),
    TICKET_STATUS      VARCHAR2(32) NOT NULL,
    COUNTING_START     NUMBER(20),
    COUNTING_END       NUMBER(20),
    ACTIVATE_TIME      TIMESTAMP,
    FIRST_USE_TIME     TIMESTAMP,
    ACC_NOTICE_STATUS  VARCHAR2(32),
    ACC_NOTICE_TIME    TIMESTAMP,
    CREATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE UNIQUE INDEX UK_DAILY_TICKET_INSTANCE_ORDER ON DAILY_TICKET_INSTANCE (ORDER_NO);
CREATE INDEX IDX_DAILY_TICKET_INSTANCE_CARD ON DAILY_TICKET_INSTANCE (CARD_NUM);
CREATE INDEX IDX_DAILY_TICKET_INSTANCE_STATUS ON DAILY_TICKET_INSTANCE (TICKET_STATUS, ACC_NOTICE_STATUS);

COMMENT ON TABLE DAILY_TICKET_INSTANCE IS '日票票实例表';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.ID IS '主键ID';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.ORDER_NO IS '关联日票订单号';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.THIRD_USER_ID IS '第三方用户编号';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.CARD_NUM IS '日票虚拟卡号';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.CARD_ISSUE IS '发卡机构代码';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.APP_CARD_TYPE IS 'APP侧卡类型';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.CODE_TICKET_TYPE IS '码体车票类型，日票固定为0441';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.TICKET_TYPE IS 'APP侧票类型';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.SHOW_TYPE IS '展示票类型';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.TICKET_CODE IS '车票编码';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.TICKET_NAME IS '车票名称';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.PERIOD IS '有效期天数';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.ACTUAL_TIMES IS '实际可用次数，-99表示不限次';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.TRANS_SEQ IS '交易序号';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.TRANS_AMOUNT IS '交易金额，单位分';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.DISCOUNT_AMOUNT IS '优惠金额，单位分';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.PAY_CHANNEL IS '支付渠道';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.TICKET_STATUS IS '票状态：INIT/ACTIVATED/USED/EXPIRED/REFUND_LOCKED/REFUNDED等';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.COUNTING_START IS '计次/计时开始时间，毫秒时间戳';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.COUNTING_END IS '计次/计时结束时间，毫秒时间戳';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.ACTIVATE_TIME IS '激活时间';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.FIRST_USE_TIME IS '首次使用时间';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.ACC_NOTICE_STATUS IS 'ACC通知状态：INIT/SUCCESS/FAIL等';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.ACC_NOTICE_TIME IS 'ACC通知时间';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DAILY_TICKET_INSTANCE.UPDATE_TIME IS '更新时间';

CREATE TABLE DAILY_TICKET_PAY_LOG (
    ID                 VARCHAR2(64) PRIMARY KEY,
    ORDER_NO           VARCHAR2(64) NOT NULL,
    BIZ_TYPE           VARCHAR2(32) NOT NULL,
    PAY_CHANNEL_CODE   VARCHAR2(16),
    REQUEST_BODY       CLOB,
    RESPONSE_BODY      CLOB,
    RESULT_CODE        VARCHAR2(32),
    RESULT_MSG         VARCHAR2(512),
    CREATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_DAILY_TICKET_PAY_LOG_ORDER ON DAILY_TICKET_PAY_LOG (ORDER_NO, BIZ_TYPE);

COMMENT ON TABLE DAILY_TICKET_PAY_LOG IS '日票支付交互日志表';
COMMENT ON COLUMN DAILY_TICKET_PAY_LOG.ID IS '主键ID';
COMMENT ON COLUMN DAILY_TICKET_PAY_LOG.ORDER_NO IS '日票订单号';
COMMENT ON COLUMN DAILY_TICKET_PAY_LOG.BIZ_TYPE IS '业务类型，如PAY/QUERY/REFUND/CALLBACK';
COMMENT ON COLUMN DAILY_TICKET_PAY_LOG.PAY_CHANNEL_CODE IS '支付渠道编码';
COMMENT ON COLUMN DAILY_TICKET_PAY_LOG.REQUEST_BODY IS '请求报文';
COMMENT ON COLUMN DAILY_TICKET_PAY_LOG.RESPONSE_BODY IS '响应报文';
COMMENT ON COLUMN DAILY_TICKET_PAY_LOG.RESULT_CODE IS '处理结果码';
COMMENT ON COLUMN DAILY_TICKET_PAY_LOG.RESULT_MSG IS '处理结果信息';
COMMENT ON COLUMN DAILY_TICKET_PAY_LOG.CREATE_TIME IS '创建时间';

CREATE TABLE DAILY_TICKET_REFUND (
    ID                 VARCHAR2(64) PRIMARY KEY,
    ORDER_NO           VARCHAR2(64) NOT NULL,
    REFUND_ORDER_NO    VARCHAR2(64),
    REFUND_AMOUNT      NUMBER(12),
    REFUND_STATUS      VARCHAR2(32),
    REFUND_TYPE        VARCHAR2(8),
    REFUND_DATE        TIMESTAMP,
    VERIFY_AFTER_TIME  TIMESTAMP,
    CREATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_DAILY_TICKET_REFUND_VERIFY ON DAILY_TICKET_REFUND (REFUND_STATUS, VERIFY_AFTER_TIME);

COMMENT ON TABLE DAILY_TICKET_REFUND IS '日票退款记录表';
COMMENT ON COLUMN DAILY_TICKET_REFUND.ID IS '主键ID';
COMMENT ON COLUMN DAILY_TICKET_REFUND.ORDER_NO IS '原日票订单号';
COMMENT ON COLUMN DAILY_TICKET_REFUND.REFUND_ORDER_NO IS '退款订单号';
COMMENT ON COLUMN DAILY_TICKET_REFUND.REFUND_AMOUNT IS '退款金额，单位分';
COMMENT ON COLUMN DAILY_TICKET_REFUND.REFUND_STATUS IS '退款状态：REFUNDING/REFUNDED/FAILED/WAIT_VERIFY等';
COMMENT ON COLUMN DAILY_TICKET_REFUND.REFUND_TYPE IS '退款类型，00直接退款，01激活后核验退款';
COMMENT ON COLUMN DAILY_TICKET_REFUND.REFUND_DATE IS '退款完成时间';
COMMENT ON COLUMN DAILY_TICKET_REFUND.VERIFY_AFTER_TIME IS '激活后退款核验时间，通常为申请后5天';
COMMENT ON COLUMN DAILY_TICKET_REFUND.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DAILY_TICKET_REFUND.UPDATE_TIME IS '更新时间';
