ALTER TABLE USER_ITP_REG_INFO ADD (TICKET_LIMIT VARCHAR2(1 CHAR));

ALTER TABLE USER_ITP_REG_INFO ADD CONSTRAINT CK_UIRI_TICKET_LIMIT CHECK (TICKET_LIMIT IN ('1', '2'));

COMMENT ON COLUMN USER_ITP_REG_INFO.TICKET_LIMIT IS '开卡数量限制，1-同用户同所属方同卡类型唯一卡，2-每次发新卡；NULL保留历史普通卡唯一、Y/C多卡规则';
COMMENT ON COLUMN USER_ITP_REG_INFO.ISSUE_ORG_CODE IS '票卡所属方，APP开户上送原值，参与唯一卡查重，不校验机构字典，不参与码体拼装';
COMMENT ON COLUMN USER_ITP_REG_INFO.COMPANION_FLAG IS '卡用途，N-主卡，Y-同行票，C-第三方票；新开户数量限制由TICKET_LIMIT决定';

SELECT SUM(CNT) AS TOTAL_ROWS, COUNT(*) AS DISTINCT_KEYS
FROM (
    SELECT THIRD_USER_ID, ISSUE_ORG_CODE, CARD_TYPE, COUNT(*) AS CNT
    FROM USER_ITP_REG_INFO
    WHERE DEL_YN = 1
      AND (TICKET_LIMIT = '1' OR (TICKET_LIMIT IS NULL AND NVL(COMPANION_FLAG, 'N') NOT IN ('Y', 'C')))
    GROUP BY THIRD_USER_ID, ISSUE_ORG_CODE, CARD_TYPE
);

DECLARE
    DUPLICATE_GROUPS NUMBER;
BEGIN
    SELECT COUNT(*) INTO DUPLICATE_GROUPS
    FROM (
        SELECT THIRD_USER_ID, ISSUE_ORG_CODE, CARD_TYPE
        FROM USER_ITP_REG_INFO
        WHERE DEL_YN = 1
          AND (TICKET_LIMIT = '1' OR (TICKET_LIMIT IS NULL AND NVL(COMPANION_FLAG, 'N') NOT IN ('Y', 'C')))
        GROUP BY THIRD_USER_ID, ISSUE_ORG_CODE, CARD_TYPE
        HAVING COUNT(*) > 1
    );
    IF DUPLICATE_GROUPS > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Duplicate unique-card keys; stop migration without changing business rows');
    END IF;
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_UIRI_LIMIT_PENDING ON USER_ITP_REG_INFO (
        CASE WHEN DEL_YN = 1 AND (TICKET_LIMIT = ''1'' OR (TICKET_LIMIT IS NULL AND NVL(COMPANION_FLAG, ''N'') NOT IN (''Y'', ''C''))) THEN THIRD_USER_ID END,
        CASE WHEN DEL_YN = 1 AND (TICKET_LIMIT = ''1'' OR (TICKET_LIMIT IS NULL AND NVL(COMPANION_FLAG, ''N'') NOT IN (''Y'', ''C''))) THEN ISSUE_ORG_CODE END,
        CASE WHEN DEL_YN = 1 AND (TICKET_LIMIT = ''1'' OR (TICKET_LIMIT IS NULL AND NVL(COMPANION_FLAG, ''N'') NOT IN (''Y'', ''C''))) THEN CARD_TYPE END)';
    EXECUTE IMMEDIATE 'DROP INDEX UK_UIRI_ACTIVE_USER_CARDTYPE';
    EXECUTE IMMEDIATE 'ALTER INDEX UK_UIRI_LIMIT_PENDING RENAME TO UK_UIRI_ACTIVE_USER_CARDTYPE';
END;
/

SELECT COLUMN_NAME, CHAR_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLS
WHERE TABLE_NAME = 'USER_ITP_REG_INFO' AND COLUMN_NAME = 'TICKET_LIMIT';

SELECT CONSTRAINT_NAME, STATUS, VALIDATED, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'CK_UIRI_TICKET_LIMIT';

SELECT INDEX_NAME, UNIQUENESS, PARTITIONED, STATUS, FUNCIDX_STATUS
FROM USER_INDEXES
WHERE INDEX_NAME IN ('UK_UIRI_ACTIVE_USER_CARDTYPE', 'UK_UIRI_LIMIT_PENDING');

SELECT COLUMN_POSITION, COLUMN_EXPRESSION
FROM USER_IND_EXPRESSIONS
WHERE INDEX_NAME = 'UK_UIRI_ACTIVE_USER_CARDTYPE'
ORDER BY COLUMN_POSITION;

SELECT TICKET_LIMIT, COUNT(*) AS CNT FROM USER_ITP_REG_INFO GROUP BY TICKET_LIMIT;
