-- ADR-D49 / ticketLimit 改造后的开户防重唯一索引。
-- 这份脚本用于把既有库里的旧索引 UK_UIRI_ACTIVE_USER_CARDTYPE 改成新口径；也可以手工执行。
-- 新口径与 UserItpRegInfoMapper.selectActiveUniqueCard 保持一致：
--   thirdUserId + ISSUE_ORG_CODE + 映射后 CARD_TYPE
--   且只约束 ticketLimit=1，兼容历史普通卡（ticketLimit is null 且 companionFlag 非 Y/C）。
-- CARD_ISSUE_CODE 存的是归一后的发行渠道码（如 5412/0008 -> 0001），用于注册乘车状态、码体/行业数据；
-- ISSUE_ORG_CODE 存 APP 上送原值，用于区分所属平台和唯一卡归属，不能用归一后的 CARD_ISSUE_CODE 参与开户查重。
--
-- 两处 NEVER：
-- ① NEVER 简化成朴素的 UNIQUE (THIRD_USER_ID, CARD_TYPE)，也 NEVER 用 CARD_ISSUE_CODE 替代 ISSUE_ORG_CODE。
--    不同所属方可能归一到同一个 CARD_ISSUE_CODE；用 CARD_ISSUE_CODE 会误判已开户，或把唯一冲突归错平台。
-- ② NEVER 只按 companionFlag 排除 Y/C。新开卡数量由 ticketLimit 决定：ticketLimit=2 每次新卡，
--    ticketLimit=1 即使 companionFlag=Y/C 也必须按唯一卡处理。
-- ③ NEVER 顺手加 LOCAL。USER_ITP_REG_INFO 按 THIRD_USER_ID 派生值 LIST 分区，而键是三个 CASE
--    表达式、不是分区键，Oracle 只允许 GLOBAL，加 LOCAL 报 ORA-14039。
--
-- 执行前 MUST 按索引的确切谓词做 ORA-01452 前置检查；有重复只能与业务定归属，NEVER 直接删行。
SELECT THIRD_USER_ID, ISSUE_ORG_CODE, CARD_TYPE, COUNT(*) AS CNT
FROM USER_ITP_REG_INFO
WHERE DEL_YN = 1
  AND (TICKET_LIMIT = '1' OR (TICKET_LIMIT IS NULL AND NVL(COMPANION_FLAG, 'N') NOT IN ('Y', 'C')))
GROUP BY THIRD_USER_ID, ISSUE_ORG_CODE, CARD_TYPE
HAVING COUNT(*) > 1;

DECLARE
    DUPLICATE_GROUPS NUMBER;
    INDEX_EXISTS NUMBER;
BEGIN
    SELECT COUNT(*) INTO DUPLICATE_GROUPS
    FROM (
        SELECT THIRD_USER_ID, ISSUE_ORG_CODE, CARD_TYPE
        FROM USER_ITP_REG_INFO
        WHERE DEL_YN = 1
          AND (TICKET_LIMIT = '1' OR (TICKET_LIMIT IS NULL AND NVL(COMPANION_FLAG, 'N') NOT IN ('Y', 'C')))
        GROUP BY THIRD_USER_ID, ISSUE_ORG_CODE, CARD_TYPE
        HAVING COUNT(*) > 1
    );
    IF DUPLICATE_GROUPS > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Duplicate unique-card keys; stop rebuilding UK_UIRI_ACTIVE_USER_CARDTYPE');
    END IF;

    SELECT COUNT(*) INTO INDEX_EXISTS
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'UK_UIRI_ACTIVE_USER_CARDTYPE';
    IF INDEX_EXISTS > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX UK_UIRI_ACTIVE_USER_CARDTYPE';
    END IF;

    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_UIRI_ACTIVE_USER_CARDTYPE ON USER_ITP_REG_INFO (
        CASE WHEN DEL_YN = 1 AND (TICKET_LIMIT = ''1'' OR (TICKET_LIMIT IS NULL AND NVL(COMPANION_FLAG, ''N'') NOT IN (''Y'', ''C''))) THEN THIRD_USER_ID END,
        CASE WHEN DEL_YN = 1 AND (TICKET_LIMIT = ''1'' OR (TICKET_LIMIT IS NULL AND NVL(COMPANION_FLAG, ''N'') NOT IN (''Y'', ''C''))) THEN ISSUE_ORG_CODE END,
        CASE WHEN DEL_YN = 1 AND (TICKET_LIMIT = ''1'' OR (TICKET_LIMIT IS NULL AND NVL(COMPANION_FLAG, ''N'') NOT IN (''Y'', ''C''))) THEN CARD_TYPE END)';
END;
/

SELECT COLUMN_POSITION, COLUMN_EXPRESSION
FROM USER_IND_EXPRESSIONS
WHERE INDEX_NAME = 'UK_UIRI_ACTIVE_USER_CARDTYPE'
ORDER BY COLUMN_POSITION;
