ALTER TABLE USER_ITP_REG_INFO ADD (ITP_CARD_TYPE VARCHAR2(64 CHAR));

UPDATE USER_ITP_REG_INFO
SET ITP_CARD_TYPE = CASE CARD_TYPE
    WHEN '0441' THEN '02'
    WHEN '0442' THEN '03'
    WHEN '0443' THEN '04'
    WHEN '0444' THEN '11'
    WHEN '0445' THEN '12'
    WHEN '0446' THEN '13'
    WHEN '0447' THEN '14'
    WHEN '0448' THEN '15'
    ELSE CARD_TYPE
END;

ALTER TABLE USER_ITP_REG_INFO MODIFY (ITP_CARD_TYPE NOT NULL);

COMMENT ON COLUMN USER_ITP_REG_INFO.CARD_TYPE IS '转换后的卡类型';
COMMENT ON COLUMN USER_ITP_REG_INFO.ITP_CARD_TYPE IS 'APP入参卡类型';
