ALTER TABLE F2F_ORDER ADD REFUND_STATUS VARCHAR2(16 CHAR) DEFAULT 'NONE' NOT NULL;

ALTER TABLE F2F_ORDER ADD REFUND_AMOUNT NUMBER(12) DEFAULT 0 NOT NULL;

ALTER TABLE F2F_ORDER ADD LAST_REFUND_TMS TIMESTAMP(6);

ALTER TABLE F2F_ORDER ADD CONSTRAINT CK_F2F_ORDER_REFUND_STATUS
    CHECK (REFUND_STATUS IN ('NONE', 'PARTIAL', 'SUCCESS'));

COMMENT ON COLUMN F2F_ORDER.REFUND_STATUS IS '退款汇总状态：NONE未退，PARTIAL部分退，SUCCESS全额退。与ORDER_STATUS正交，退款不改支付/履约主状态';
COMMENT ON COLUMN F2F_ORDER.REFUND_AMOUNT IS '已成功退款总额（分），由F2F_REFUND中REFUND_STATUS=SUCCESS的行重算得出，NEVER累加';
COMMENT ON COLUMN F2F_ORDER.LAST_REFUND_TMS IS '最后一次退款汇总重算时刻';

UPDATE F2F_ORDER O
SET O.REFUND_AMOUNT = (
        SELECT NVL(SUM(R.REFUND_AMOUNT), 0)
        FROM F2F_REFUND R
        WHERE R.ORIG_ORDER_NO = O.ORDER_NO
          AND R.REFUND_STATUS = 'SUCCESS'
    ),
    O.REFUND_STATUS = CASE
        WHEN (SELECT NVL(SUM(R.REFUND_AMOUNT), 0) FROM F2F_REFUND R
              WHERE R.ORIG_ORDER_NO = O.ORDER_NO AND R.REFUND_STATUS = 'SUCCESS') <= 0
            THEN 'NONE'
        WHEN (SELECT NVL(SUM(R.REFUND_AMOUNT), 0) FROM F2F_REFUND R
              WHERE R.ORIG_ORDER_NO = O.ORDER_NO AND R.REFUND_STATUS = 'SUCCESS')
             >= O.ORDER_AMOUNT
            THEN 'SUCCESS'
        ELSE 'PARTIAL'
    END,
    O.LAST_REFUND_TMS = CASE
        WHEN EXISTS (SELECT 1 FROM F2F_REFUND R
                     WHERE R.ORIG_ORDER_NO = O.ORDER_NO AND R.REFUND_STATUS = 'SUCCESS')
            THEN SYSTIMESTAMP
        ELSE NULL
    END
WHERE EXISTS (SELECT 1 FROM F2F_REFUND R WHERE R.ORIG_ORDER_NO = O.ORDER_NO);

UPDATE F2F_ORDER O
SET O.ORDER_STATUS = 'FULFILLED',
    O.UPDATE_TMS = SYSTIMESTAMP
WHERE O.ORDER_STATUS IN ('REFUNDING', 'REFUNDED')
  AND O.FULFILL_TMS IS NOT NULL;

UPDATE F2F_ORDER O
SET O.ORDER_STATUS = 'PAID',
    O.UPDATE_TMS = SYSTIMESTAMP
WHERE O.ORDER_STATUS IN ('REFUNDING', 'REFUNDED')
  AND O.FULFILL_TMS IS NULL
  AND O.PAID_TMS IS NOT NULL;

COMMIT;
