-- 支付交易明细表
-- Oracle 月分区表，TXN_DATE 使用字符串 YYYYMMDD 入库。
-- 本脚本保存支付侧完整明细，GATE_TXN_PAY.ORDER_NO = PAY_TXN_DETAIL.ORDER_NO。
-- 重试最大次数不入库，后续由配置文件控制。

CREATE TABLE PAY_TXN_DETAIL (
    ID                  NUMBER(22) NOT NULL,

    ORDER_NO            VARCHAR2(128 CHAR) NOT NULL,
    PAY_TYPE            VARCHAR2(32 CHAR) DEFAULT 'PAY' NOT NULL,
    PAY_STATUS          VARCHAR2(32 CHAR) DEFAULT 'INIT' NOT NULL,

    THIRD_USER_ID       VARCHAR2(128 CHAR),
    CARD_ID             VARCHAR2(64 CHAR),
    CARD_TYPE           VARCHAR2(64 CHAR),

    PAYMENT_VENDOR      VARCHAR2(32 CHAR),
    PAY_CHANNEL_CODE    VARCHAR2(32 CHAR),
    REQUEST_SIGN_SEQ    VARCHAR2(256 CHAR),

    AMOUNT              NUMBER(22) DEFAULT 0 NOT NULL,
    TOTAL_AMOUNT        NUMBER(22),
    CASH_AMOUNT         NUMBER(22),
    COUPON_AMOUNT       NUMBER(22),

    REFUND_STATUS       VARCHAR2(32 CHAR) DEFAULT 'NONE' NOT NULL,
    REFUND_AMOUNT       NUMBER(22) DEFAULT 0 NOT NULL,
    LAST_REFUND_TIME    TIMESTAMP(6),

    MERCHANT_ORDER_NO   VARCHAR2(128 CHAR),
    CHANNEL_ORDER_NO    VARCHAR2(256 CHAR),
    PAY_USER_ID         VARCHAR2(256 CHAR),

    REQUEST_COUNT       NUMBER(22) DEFAULT 0 NOT NULL,
    NEXT_REQUEST_TIME   TIMESTAMP(6),
    LAST_REQUEST_TIME   TIMESTAMP(6),

    FIRST_REQUEST_TIME  TIMESTAMP(6),
    RESPONSE_TIME       TIMESTAMP(6),
    PAY_TIME            VARCHAR2(28 CHAR),
    TXN_DATE            DATE NOT NULL,

    CREATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_PAY_TXN_DETAIL PRIMARY KEY (ID)
)
PARTITION BY RANGE (TXN_DATE) (
    PARTITION P202606 VALUES LESS THAN ('20260701'),
    PARTITION P202607 VALUES LESS THAN ('20260801'),
    PARTITION P202608 VALUES LESS THAN ('20260901'),
    PARTITION P202609 VALUES LESS THAN ('20261001'),
    PARTITION P202610 VALUES LESS THAN ('20261101'),
    PARTITION P202611 VALUES LESS THAN ('20261201'),
    PARTITION P202612 VALUES LESS THAN ('20270101'),
    PARTITION P_MAX VALUES LESS THAN (MAXVALUE)
);

CREATE SEQUENCE SEQ_PAY_TXN_DETAIL
    START WITH 1
    INCREMENT BY 1
    CACHE 1000
    NOCYCLE;

CREATE UNIQUE INDEX UK_PAY_TXN_DETAIL_ORDER
ON PAY_TXN_DETAIL (
    ORDER_NO,
    TXN_DATE
)
LOCAL;

CREATE INDEX IDX_PAY_TXN_DETAIL_STATUS
ON PAY_TXN_DETAIL (
    PAY_STATUS,
    TXN_DATE,
    NEXT_REQUEST_TIME
)
LOCAL;

CREATE INDEX IDX_PAY_TXN_DETAIL_CARD_DATE
ON PAY_TXN_DETAIL (
    CARD_ID,
    TXN_DATE
)
LOCAL;

CREATE INDEX IDX_PAY_TXN_DETAIL_USER_DATE
ON PAY_TXN_DETAIL (
    THIRD_USER_ID,
    TXN_DATE
)
LOCAL;

CREATE INDEX IDX_PAY_TXN_DETAIL_CHANNEL_ORDER
ON PAY_TXN_DETAIL (
    CHANNEL_ORDER_NO,
    TXN_DATE
)
LOCAL;

COMMENT ON TABLE PAY_TXN_DETAIL IS '支付交易明细表';
COMMENT ON COLUMN PAY_TXN_DETAIL.ORDER_NO IS '地铁侧订单号，同时作为支付接口orderNo';
COMMENT ON COLUMN PAY_TXN_DETAIL.PAY_TYPE IS '交易类型：PAY支付，REFUND退款';
COMMENT ON COLUMN PAY_TXN_DETAIL.PAY_STATUS IS '支付状态：INIT初始化，PROCESSING处理中，SUCCESS成功，FAIL失败，RETRY待重试，CLOSED关闭';
COMMENT ON COLUMN PAY_TXN_DETAIL.THIRD_USER_ID IS '第三方用户ID，对应设备报文itpUserId转换后的用户标识';
COMMENT ON COLUMN PAY_TXN_DETAIL.CARD_ID IS '逻辑卡号';
COMMENT ON COLUMN PAY_TXN_DETAIL.CARD_TYPE IS '票卡类型';
COMMENT ON COLUMN PAY_TXN_DETAIL.PAYMENT_VENDOR IS '支付方式';
COMMENT ON COLUMN PAY_TXN_DETAIL.PAY_CHANNEL_CODE IS '支付通道编码';
COMMENT ON COLUMN PAY_TXN_DETAIL.REQUEST_SIGN_SEQ IS '签约流水号或免密协议流水';
COMMENT ON COLUMN PAY_TXN_DETAIL.AMOUNT IS '请求支付金额，单位分';
COMMENT ON COLUMN PAY_TXN_DETAIL.TOTAL_AMOUNT IS '订单总金额，单位分';
COMMENT ON COLUMN PAY_TXN_DETAIL.CASH_AMOUNT IS '实付金额，单位分';
COMMENT ON COLUMN PAY_TXN_DETAIL.COUPON_AMOUNT IS '优惠金额，单位分';
COMMENT ON COLUMN PAY_TXN_DETAIL.REFUND_STATUS IS '退款状态：NONE未退款，PROCESSING退款中，PARTIAL部分退款，SUCCESS已全额退款，FAIL退款失败';
COMMENT ON COLUMN PAY_TXN_DETAIL.REFUND_AMOUNT IS '已退款总金额，单位分';
COMMENT ON COLUMN PAY_TXN_DETAIL.LAST_REFUND_TIME IS '最近一次退款完成时间';
COMMENT ON COLUMN PAY_TXN_DETAIL.MERCHANT_ORDER_NO IS '商户订单号';
COMMENT ON COLUMN PAY_TXN_DETAIL.CHANNEL_ORDER_NO IS '渠道订单号';
COMMENT ON COLUMN PAY_TXN_DETAIL.PAY_USER_ID IS '支付渠道账户或买家账户';
COMMENT ON COLUMN PAY_TXN_DETAIL.REQUEST_COUNT IS '已发起支付请求次数';
COMMENT ON COLUMN PAY_TXN_DETAIL.NEXT_REQUEST_TIME IS '下次允许重试支付时间';
COMMENT ON COLUMN PAY_TXN_DETAIL.LAST_REQUEST_TIME IS '最近一次发起支付时间';
COMMENT ON COLUMN PAY_TXN_DETAIL.FIRST_REQUEST_TIME IS '首次发起支付时间';
COMMENT ON COLUMN PAY_TXN_DETAIL.RESPONSE_TIME IS '最近一次收到支付响应时间';
COMMENT ON COLUMN PAY_TXN_DETAIL.PAY_TIME IS '支付完成时间，格式YYYYMMDDHH24MISS';
COMMENT ON COLUMN PAY_TXN_DETAIL.TXN_DATE IS '订单日期，格式YYYYMMDD，用于月分区';
-- 退款明细表
-- 一笔支付订单可以有多笔退款，退款结果回写 PAY_TXN_DETAIL.REFUND_STATUS / REFUND_AMOUNT。

CREATE TABLE PAY_REFUND_DETAIL (
    ID                  NUMBER(22) NOT NULL,

    REFUND_ORDER_NO     VARCHAR2(128 CHAR) NOT NULL,
    ORDER_NO            VARCHAR2(128 CHAR) NOT NULL,
    REFUND_STATUS       VARCHAR2(32 CHAR) DEFAULT 'INIT' NOT NULL,

    REFUND_AMOUNT       NUMBER(16) NOT NULL,
    REFUND_REASON       VARCHAR2(1024 CHAR),

    MERCHANT_REFUND_NO  VARCHAR2(128 CHAR),
    REFUND_NO           VARCHAR2(128 CHAR) NOT NULL,
    CHANNEL_REFUND_NO   VARCHAR2(256 CHAR),

    REQUEST_COUNT       NUMBER(22) DEFAULT 0 NOT NULL,
    NEXT_REQUEST_TIME   TIMESTAMP(6),
    LAST_REQUEST_TIME   TIMESTAMP(6),

    REFUND_TIME         VARCHAR2(28 CHAR),
    TXN_DATE            DATE NOT NULL,

    RET_CODE            VARCHAR2(32 CHAR),
    RET_MSG             VARCHAR2(512 CHAR),
    PAY_CENTER_CODE     VARCHAR2(32 CHAR),
    PAY_CENTER_MSG      VARCHAR2(1024 CHAR),

    REQUEST_BODY        CLOB,
    RESPONSE_BODY       CLOB,

    CREATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_PAY_REFUND_DETAIL PRIMARY KEY (ID)
)
PARTITION BY RANGE (TXN_DATE) (
    PARTITION P202606 VALUES LESS THAN ('20260701'),
    PARTITION P202607 VALUES LESS THAN ('20260801'),
    PARTITION P202608 VALUES LESS THAN ('20260901'),
    PARTITION P202609 VALUES LESS THAN ('20261001'),
    PARTITION P202610 VALUES LESS THAN ('20261101'),
    PARTITION P202611 VALUES LESS THAN ('20261201'),
    PARTITION P202612 VALUES LESS THAN ('20270101'),
    PARTITION P_MAX VALUES LESS THAN (MAXVALUE)
);

CREATE SEQUENCE SEQ_PAY_REFUND_DETAIL
    START WITH 1
    INCREMENT BY 1
    CACHE 1000
    NOCYCLE;

CREATE UNIQUE INDEX UK_PAY_REFUND_DETAIL_NO
ON PAY_REFUND_DETAIL (
    REFUND_ORDER_NO,
    TXN_DATE
)
LOCAL;

CREATE INDEX IDX_PAY_REFUND_DETAIL_ORDER
ON PAY_REFUND_DETAIL (
    ORDER_NO,
    TXN_DATE
)
LOCAL;

CREATE INDEX IDX_PAY_REFUND_DETAIL_STATUS
ON PAY_REFUND_DETAIL (
    REFUND_STATUS,
    TXN_DATE,
    NEXT_REQUEST_TIME
)
LOCAL;

COMMENT ON TABLE PAY_REFUND_DETAIL IS '支付退款明细表';
COMMENT ON COLUMN PAY_REFUND_DETAIL.REFUND_ORDER_NO IS '内部退款单号';
COMMENT ON COLUMN PAY_REFUND_DETAIL.ORDER_NO IS '原支付订单号，对应PAY_TXN_DETAIL.ORDER_NO';
COMMENT ON COLUMN PAY_REFUND_DETAIL.REFUND_STATUS IS '退款状态：INIT初始化，PROCESSING处理中，SUCCESS成功，FAIL失败，RETRY待重试，CLOSED关闭';
COMMENT ON COLUMN PAY_REFUND_DETAIL.REFUND_AMOUNT IS '退款金额，单位分';
COMMENT ON COLUMN PAY_REFUND_DETAIL.REQUEST_COUNT IS '已发起退款请求次数';
COMMENT ON COLUMN PAY_REFUND_DETAIL.NEXT_REQUEST_TIME IS '下次允许重试退款时间';
COMMENT ON COLUMN PAY_REFUND_DETAIL.LAST_REQUEST_TIME IS '最近一次发起退款时间';

-- 支付/退款回调流水表
-- 每次回调插入一条，避免重复回调覆盖原文。

CREATE TABLE PAY_CALLBACK_LOG (
    ID                  NUMBER(22) NOT NULL,

    ORDER_NO            VARCHAR2(128 CHAR) NOT NULL,
    CALLBACK_TYPE       VARCHAR2(32 CHAR) NOT NULL,
    CALLBACK_STATUS     VARCHAR2(32 CHAR),

    REFUND_ORDER_NO     VARCHAR2(128 CHAR),
    MERCHANT_ORDER_NO   VARCHAR2(128 CHAR),
    CHANNEL_ORDER_NO    VARCHAR2(256 CHAR),
    MERCHANT_REFUND_NO  VARCHAR2(128 CHAR),
    REFUND_NO           VARCHAR2(128 CHAR),
    CHANNEL_REFUND_NO   VARCHAR2(256 CHAR),

    PAY_TIME            VARCHAR2(28 CHAR),
    REFUND_TIME         VARCHAR2(28 CHAR),
    TOTAL_AMOUNT        NUMBER(22),
    CASH_AMOUNT         NUMBER(22),
    COUPON_AMOUNT       NUMBER(22),
    REFUND_AMOUNT       NUMBER(22),

    PAY_USER_ID         VARCHAR2(256 CHAR),
    PAYMENT_VENDOR      VARCHAR2(32 CHAR),
    TXN_DATE            DATE NOT NULL,

    RAW_BODY            CLOB,
    HANDLE_STATUS       VARCHAR2(32 CHAR),
    HANDLE_MSG          VARCHAR2(1024 CHAR),
    CREATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_PAY_CALLBACK_LOG PRIMARY KEY (ID)
)
PARTITION BY RANGE (TXN_DATE) (
    PARTITION P202606 VALUES LESS THAN ('20260701'),
    PARTITION P202607 VALUES LESS THAN ('20260801'),
    PARTITION P202608 VALUES LESS THAN ('20260901'),
    PARTITION P202609 VALUES LESS THAN ('20261001'),
    PARTITION P202610 VALUES LESS THAN ('20261101'),
    PARTITION P202611 VALUES LESS THAN ('20261201'),
    PARTITION P202612 VALUES LESS THAN ('20270101'),
    PARTITION P_MAX VALUES LESS THAN (MAXVALUE)
);

CREATE SEQUENCE SEQ_PAY_CALLBACK_LOG
    START WITH 1
    INCREMENT BY 1
    CACHE 1000
    NOCYCLE;

CREATE INDEX IDX_PAY_CALLBACK_LOG_ORDER
ON PAY_CALLBACK_LOG (
    ORDER_NO,
    TXN_DATE
)
LOCAL;

CREATE INDEX IDX_PAY_CALLBACK_LOG_REFUND
ON PAY_CALLBACK_LOG (
    REFUND_ORDER_NO,
    TXN_DATE
)
LOCAL;

COMMENT ON TABLE PAY_CALLBACK_LOG IS '支付回调流水表';
COMMENT ON COLUMN PAY_CALLBACK_LOG.CALLBACK_TYPE IS '回调类型：PAY支付回调，REFUND退款回调';
COMMENT ON COLUMN PAY_CALLBACK_LOG.CALLBACK_STATUS IS '回调中的支付或退款状态';
COMMENT ON COLUMN PAY_CALLBACK_LOG.RAW_BODY IS '回调原文';
COMMENT ON COLUMN PAY_CALLBACK_LOG.HANDLE_STATUS IS '本地处理状态：SUCCESS成功，FAIL失败';

-- 后续月分区维护示例：
--
-- ALTER TABLE PAY_TXN_DETAIL
-- SPLIT PARTITION P_MAX
-- AT ('20270201')
-- INTO (
--     PARTITION P202701,
--     PARTITION P_MAX
-- );
--
-- ALTER TABLE PAY_REFUND_DETAIL
-- SPLIT PARTITION P_MAX
-- AT ('20270201')
-- INTO (
--     PARTITION P202701,
--     PARTITION P_MAX
-- );
--
-- ALTER TABLE PAY_CALLBACK_LOG
-- SPLIT PARTITION P_MAX
-- AT ('20270201')
-- INTO (
--     PARTITION P202701,
--     PARTITION P_MAX
-- );
--
-- 待支付重试查询示例，最大重试次数由配置文件传入。
--
-- SELECT *
-- FROM PAY_TXN_DETAIL
-- WHERE PAY_STATUS IN ('FAIL', 'RETRY')
--   AND REQUEST_COUNT < :maxRequestCount
--   AND (NEXT_REQUEST_TIME IS NULL OR NEXT_REQUEST_TIME <= SYSTIMESTAMP)
-- ORDER BY NEXT_REQUEST_TIME NULLS FIRST, UPDATE_TIME;
