server.port=8080
spring.application.name=alipay-account

other.sql.host=172.20.222.3
other.sql.double-datasource=false
other.sql.type=oracle
other.sql.page.type=oracle
other.sql.database=AFCITPDB
other.sql.username=qditp
other.sql.password=qditp

other.web.unSafeUrlChars=null
other.web.enableLogRequestInFilter=true
other.web.enableBodyCacheFilter=true
other.web.enableLogTakeTimesInInterceptor=true

knife4j.production=false

service.ticket.openLogger=true
service.ticket.url=http://ticket-server:9103

mybatis.mapper-locations=classpath*:mapper/*.xml

alipay.card-pool.threshold=10
alipay.card-pool.batch-size=20

alipay.card-pool.debug-manual-allocate=false
alipay.card-pool.debug-manual-card-id=0000

itp.providerId=01
itp.charset=UTF-8
itp.format=json
itp.signKey=bc4f7c96259acf9946094fa
