<template>
  <div class="app-container">
    <el-form :model="query" :inline="true"><el-form-item label="规则编号"><el-input v-model="query.ruleId" clearable placeholder="请输入规则编号"/></el-form-item><el-form-item label="规则名称"><el-input v-model="query.ruleName" clearable placeholder="请输入规则名称"/></el-form-item><el-form-item label="风险组"><el-select v-model="query.groupId" clearable placeholder="全部"><el-option v-for="g in groups" :key="g.groupId" :label="g.groupName" :value="g.groupId"/></el-select></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="search">查询</el-button><el-button icon="Refresh" @click="resetQuery">重置</el-button></el-form-item></el-form>
    <el-row class="mb8"><el-col :span="1.5"><el-button v-hasPermi="['para:risk-rule:add']" type="primary" plain icon="Plus" @click="add">新增</el-button></el-col></el-row>
    <el-table v-loading="loading" :data="rows" border><el-table-column label="序号" width="70" align="center"><template #default="s">{{(query.pageNum-1)*query.pageSize+s.$index+1}}</template></el-table-column><el-table-column label="规则编号" prop="ruleId" width="140" align="center"/><el-table-column label="风险规则名称" prop="ruleName" min-width="220"/><el-table-column label="风险组" prop="groupName" min-width="170"><template #default="{row}">{{row.groupName||'-'}}</template></el-table-column><el-table-column label="风险等级" prop="riskLevel" width="110" align="center"/><el-table-column label="风险规则最大值" prop="riskLimitValue" width="160" align="right"/><el-table-column label="管理编码" prop="managerCode" width="150"/><el-table-column label="修改时间" width="180" align="center"><template #default="{row}">{{parseTime(row.updateTime)||'-'}}</template></el-table-column><el-table-column label="操作" width="120" fixed="right" align="center"><template #default="{row}"><el-tooltip content="修改"><el-button v-hasPermi="['para:risk-rule:edit']" link type="primary" icon="Edit" @click="edit(row)"/></el-tooltip><el-tooltip content="删除"><el-button v-hasPermi="['para:risk-rule:remove']" link type="danger" icon="Delete" @click="remove(row)"/></el-tooltip></template></el-table-column></el-table>
    <pagination v-show="total>0" v-model:page="query.pageNum" v-model:limit="query.pageSize" :total="total" @pagination="load"/>
    <el-dialog v-model="open" :title="title" width="600px" append-to-body destroy-on-close><el-form ref="formRef" :model="form" :rules="rules" label-width="130px"><el-form-item label="规则编号" prop="ruleId"><el-input v-model="form.ruleId" :disabled="editing" maxlength="16"/></el-form-item><el-form-item label="风险规则名称" prop="ruleName"><el-input v-model="form.ruleName" maxlength="100"/></el-form-item><el-form-item label="所属风险组"><el-select v-model="form.groupId" clearable placeholder="可不选择"><el-option v-for="g in groups" :key="g.groupId" :label="g.groupName" :value="g.groupId"/></el-select></el-form-item><el-form-item label="风险等级" prop="riskLevel"><el-select v-model="form.riskLevel"><el-option v-for="n in 5" :key="n" :label="`${n}级`" :value="n"/></el-select></el-form-item><el-form-item label="风险规则最大值" prop="riskLimitValue"><el-input-number v-model="form.riskLimitValue" :min="0" :precision="2" controls-position="right"/></el-form-item><el-form-item label="管理编码"><el-input v-model="form.managerCode" maxlength="64"/></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" :rows="3" maxlength="500" show-word-limit/></el-form-item></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" :loading="saving" @click="submit">确定</el-button></template></el-dialog>
  </div>
</template>
<script setup name="RiskRule">
import { addRiskRule, delRiskRule, listRiskGroupOptions, listRiskRules, updateRiskRule } from '@/api/para/risk'
// 风险规则新增后编号不可编辑，更新请求以路径规则编号为准。
const {proxy}=getCurrentInstance();const loading=ref(false),saving=ref(false),open=ref(false),editing=ref(false),title=ref(''),rows=ref([]),groups=ref([]),total=ref(0);const query=reactive({ruleId:'',ruleName:'',groupId:null,pageNum:1,pageSize:10});const form=reactive({ruleId:'',groupId:null,ruleName:'',riskLevel:1,riskLimitValue:0,managerCode:'',remark:''});const rules={ruleId:[{required:true,message:'请输入规则编号',trigger:'blur'}],ruleName:[{required:true,message:'请输入规则名称',trigger:'blur'}],riskLevel:[{required:true,message:'请选择风险等级',trigger:'change'}],riskLimitValue:[{required:true,message:'请输入最大值',trigger:'change'}]}
function load(){loading.value=true;listRiskRules({...query}).then(r=>{rows.value=r.data?.list||[];total.value=Number(r.data?.total||0)}).finally(()=>loading.value=false)}function loadGroups(){listRiskGroupOptions().then(r=>groups.value=r.data||[])}function search(){query.pageNum=1;load()}function resetQuery(){Object.assign(query,{ruleId:'',ruleName:'',groupId:null});search()}function resetForm(){Object.assign(form,{ruleId:'',groupId:null,ruleName:'',riskLevel:1,riskLimitValue:0,managerCode:'',remark:''});proxy.resetForm('formRef')}function add(){resetForm();editing.value=false;title.value='新增风险规则';open.value=true}function edit(row){resetForm();Object.assign(form,row);editing.value=true;title.value='修改风险规则';open.value=true}
function submit(){proxy.$refs.formRef.validate(v=>{if(!v)return;saving.value=true;const data={...form,ruleId:form.ruleId.trim(),ruleName:form.ruleName.trim(),managerCode:form.managerCode.trim()||null,remark:form.remark.trim()||null};(editing.value?updateRiskRule(form.ruleId,data):addRiskRule(data)).then(()=>{proxy.$modal.msgSuccess(editing.value?'修改成功':'新增成功');open.value=false;load()}).finally(()=>saving.value=false)})}function remove(row){proxy.$modal.confirm(`确认删除风险规则“${row.ruleName}”吗？`).then(()=>delRiskRule(row.ruleId)).then(()=>{proxy.$modal.msgSuccess('删除成功');load()}).catch(()=>{})}onMounted(()=>{loadGroups();load()})
</script>
