other.sql.double-datasource=true
#
spring.datasource.druid.database1.page-type=mysql
spring.datasource.druid.database1.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.druid.database1.url=jdbc:mysql://localhost:3306/test
spring.datasource.druid.database1.username=test
spring.datasource.druid.database1.password=test
#
spring.datasource.druid.database2.page-type=mysql
spring.datasource.druid.database2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.druid.database2.url=jdbc:mysql://localhost:3306/test
spring.datasource.druid.database2.username=test
spring.datasource.druid.database2.password=test
