-- ============================================================
-- if8a_29 / if8a_34 / if8a_05 查询接口 - 表字段补充 DDL
-- ============================================================
-- 执行顺序：先执行 GATE_TXN_PAY，再执行 PAY_TXN_DETAIL
-- 历史数据补录仅在开发/测试环境执行，生产环境请勿直接 UPDATE 历史数据

-- ============================================================
-- 1. GATE_TXN_PAY：新增字段
-- ============================================================

-- 1.1 TICKET_STATUS：存储票卡当前状态，避免每次查询都调用 ticket-server RPC
--     状态值参考 QRCodeStatus.CODE_STATUS：
--       01=无交易  02=ENTRY  04=FAILED  05=EXIT  06=EXIT_OVERTIME
--       70=ABNORMAL  80=SELF_SERVICE_EXIT
ALTER TABLE GATE_TXN_PAY ADD (TICKET_STATUS VARCHAR2(8 CHAR));
COMMENT ON COLUMN GATE_TXN_PAY.TICKET_STATUS IS '票卡状态：01无交易,02进站,03进站超时,04进站失败,05出站,06出站超时,70异常,80自助补出站';

-- 1.2 ENTRY_STATION_NAME / EXIT_STATION_NAME：存储车站名称，避免查询时关联 stations 表
ALTER TABLE GATE_TXN_PAY ADD (ENTRY_STATION_NAME VARCHAR2(64 CHAR));
ALTER TABLE GATE_TXN_PAY ADD (EXIT_STATION_NAME VARCHAR2(64 CHAR));
COMMENT ON COLUMN GATE_TXN_PAY.ENTRY_STATION_NAME IS '进站车站名称';
COMMENT ON COLUMN GATE_TXN_PAY.EXIT_STATION_NAME IS '出站车站名称';

-- 1.3 ORDER_EXP_TYPE：订单异常类型
--       0=正常  1=单边账(入站)  2=单边账(出站)  3=单边入站(人工处理单)
--       4=单边出站(人工处理单)  5=双段计费正常订单_行程超时
ALTER TABLE GATE_TXN_PAY ADD (ORDER_EXP_TYPE VARCHAR2(8 CHAR));
COMMENT ON COLUMN GATE_TXN_PAY.ORDER_EXP_TYPE IS '订单异常类型：0正常,1单边账(入),2单边账(出),3单边入站人工,4单边出站人工,5双段计费超时';

-- 1.4 COMPANION_FLAG / OFFLINE_FLAG：同行票标识、离线码标识
ALTER TABLE GATE_TXN_PAY ADD (COMPANION_FLAG VARCHAR2(2 CHAR) DEFAULT 'N');
ALTER TABLE GATE_TXN_PAY ADD (OFFLINE_FLAG VARCHAR2(2 CHAR) DEFAULT 'N');
COMMENT ON COLUMN GATE_TXN_PAY.COMPANION_FLAG IS '同行票标识：Y/N';
COMMENT ON COLUMN GATE_TXN_PAY.OFFLINE_FLAG IS '离线码标识：Y/N';

-- 1.5 TICKET_CODE / COUNTING_TIMES / COUNTING_FLAG：日票票号、计次票次数与标志
ALTER TABLE GATE_TXN_PAY ADD (TICKET_CODE VARCHAR2(32 CHAR));
ALTER TABLE GATE_TXN_PAY ADD (COUNTING_TIMES NUMBER(8));
ALTER TABLE GATE_TXN_PAY ADD (COUNTING_FLAG VARCHAR2(4 CHAR));
COMMENT ON COLUMN GATE_TXN_PAY.TICKET_CODE IS '日票票号';
COMMENT ON COLUMN GATE_TXN_PAY.COUNTING_TIMES IS '计次票剩余次数（扣减后）';
COMMENT ON COLUMN GATE_TXN_PAY.COUNTING_FLAG IS '计次票标志：Y是，N否';

-- 1.6 ATTRIBUTABLE_PARTY / RECEIVING_PARTY：订单应收商户 / 实收商户
ALTER TABLE GATE_TXN_PAY ADD (ATTRIBUTABLE_PARTY VARCHAR2(32 CHAR));
ALTER TABLE GATE_TXN_PAY ADD (RECEIVING_PARTY VARCHAR2(32 CHAR));
COMMENT ON COLUMN GATE_TXN_PAY.ATTRIBUTABLE_PARTY IS '订单应收商户';
COMMENT ON COLUMN GATE_TXN_PAY.RECEIVING_PARTY IS '订单实收商户';

-- 1.5 历史数据补录（仅开发/测试环境执行）
UPDATE GATE_TXN_PAY
   SET TICKET_STATUS = CASE
                          WHEN DEBIT_STATUS IN ('SUCCESS', 'PROCESSING') AND TRX_TYPE IN ('02', '03') THEN '05'
                          WHEN DEBIT_STATUS = 'FAIL'                      AND TRX_TYPE IN ('02', '03') THEN '04'
                          WHEN DEBIT_STATUS = 'INIT'                      AND TRX_TYPE = '01'         THEN '02'
                          ELSE DEBIT_STATUS
                       END
 WHERE TICKET_STATUS IS NULL;

-- 1.6 PAY_CHANNEL_CODE / DISCOUNT_FEE / DISCOUNT_INFO：支付通道、优惠金额、优惠详情
ALTER TABLE GATE_TXN_PAY ADD (PAY_CHANNEL_CODE VARCHAR2(16 CHAR));
ALTER TABLE GATE_TXN_PAY ADD (DISCOUNT_FEE NUMERIC(10));
ALTER TABLE GATE_TXN_PAY ADD (DISCOUNT_INFO VARCHAR2(512 CHAR));
COMMENT ON COLUMN GATE_TXN_PAY.PAY_CHANNEL_CODE IS '支付通道编码（signChannelCode）';
COMMENT ON COLUMN GATE_TXN_PAY.DISCOUNT_FEE IS '优惠金额（分）';
COMMENT ON COLUMN GATE_TXN_PAY.DISCOUNT_INFO IS '优惠详情JSON数组';

COMMIT;

-- ============================================================
-- 2. PAY_TXN_DETAIL：新增字段
-- ============================================================

-- 2.1 DISCOUNT_INFO：优惠详情JSON数组，来自支付平台回调
--     使用 VARCHAR2(512) 而非 CLOB：优惠详情通常 < 200 字节，VARCHAR2 查询性能更好且支持索引
ALTER TABLE PAY_TXN_DETAIL ADD (DISCOUNT_INFO VARCHAR2(512 CHAR));
COMMENT ON COLUMN PAY_TXN_DETAIL.DISCOUNT_INFO IS '优惠详情JSON数组，来自支付平台回调';

-- 2.2 DEBIT_REQUEST_RESULT：扣款请求结果（PROCESSING/SUCCESS/FAIL）
ALTER TABLE PAY_TXN_DETAIL ADD (DEBIT_REQUEST_RESULT VARCHAR2(16 CHAR));
COMMENT ON COLUMN PAY_TXN_DETAIL.DEBIT_REQUEST_RESULT IS '扣款结果：PROCESSING/SUCCESS/FAIL';

-- 2.3 DISCOUNT_FEE：优惠金额（分），由 ticket-server 计算透传
ALTER TABLE PAY_TXN_DETAIL ADD (DISCOUNT_FEE NUMERIC(10));
COMMENT ON COLUMN PAY_TXN_DETAIL.DISCOUNT_FEE IS '优惠金额（分）';

-- CASH_AMOUNT / COUPON_AMOUNT 字段已在 pay-txn-schema.sql 建表脚本中定义，无需重复添加

COMMIT;

-- ============================================================
-- 3. QRCODE_TXN_DETAIL：新增字段（ticket-server 交易明细扩展）
-- ============================================================

-- 3.1 CARD_NUM：卡号（与 CARD_ID 同值，方便别名查询）
ALTER TABLE QRCODE_TXN_DETAIL ADD (CARD_NUM VARCHAR2(32 CHAR));
COMMENT ON COLUMN QRCODE_TXN_DETAIL.CARD_NUM IS '卡号（与CARD_ID同值）';

-- 3.2 PAY_CHANNEL_CODE：支付通道编码（signChannelCode）
ALTER TABLE QRCODE_TXN_DETAIL ADD (PAY_CHANNEL_CODE VARCHAR2(16 CHAR));
COMMENT ON COLUMN QRCODE_TXN_DETAIL.PAY_CHANNEL_CODE IS '支付通道编码（signChannelCode）';

-- 3.3 DEBIT_REQUEST_RESULT：扣款结果（PROCESSING/SUCCESS/FAIL），出站完成后回填
ALTER TABLE QRCODE_TXN_DETAIL ADD (DEBIT_REQUEST_RESULT VARCHAR2(16 CHAR));
COMMENT ON COLUMN QRCODE_TXN_DETAIL.DEBIT_REQUEST_RESULT IS '扣款结果：PROCESSING/SUCCESS/FAIL';

-- 3.4 DISCOUNT_FEE：优惠金额（分）
ALTER TABLE QRCODE_TXN_DETAIL ADD (DISCOUNT_FEE NUMERIC(10));
COMMENT ON COLUMN QRCODE_TXN_DETAIL.DISCOUNT_FEE IS '优惠金额（分）';

-- 3.5 DISCOUNT_INFO：优惠详情 JSON 数组
ALTER TABLE QRCODE_TXN_DETAIL ADD (DISCOUNT_INFO VARCHAR2(512 CHAR));
COMMENT ON COLUMN QRCODE_TXN_DETAIL.DISCOUNT_INFO IS '优惠详情JSON数组';

COMMIT;

-- ============================================================
-- 3. 索引优化（可选）
--    GATE_TXN_PAY 已有 IDX_GATE_TXN_PAY_CARD_DATE (CARD_ID, TXN_DATE, OUT_TIME)，
--    可覆盖按卡号+日期查询最近行程的场景，无需新增索引。
--
--    若后续需要按 TICKET_STATUS 过滤，可考虑新增复合索引：
-- CREATE INDEX IDX_GATE_TXN_PAY_CARD_STATUS_DATE
--     ON GATE_TXN_PAY (CARD_ID, TICKET_STATUS, TXN_DATE) LOCAL;
-- ============================================================
