-- ============================================================
-- 用途: 新增「签约展示账号同步补偿」定时任务（每 5 分钟一次）
-- 调用目标: accountQuartzTask.compensatePhoneSignSync()
-- 所属服务: web-admin（任务 Bean 在 web-admin，经 rpc 调 account-server 9098 POST /phoneSignSyncCompensate）
-- 创建日期: 2026-09-11
-- 数据库: Oracle（sys_job.job_id 是 IDENTITY GENERATED BY DEFAULT ON NULL，可省略）
--
-- 背景: 手机号变更后需把新号同步给支付域更新 APP_PAY_SIGN_INFO.DISPLAY_ACCOUNT。
--   该投递已于 2026-09-11 移出事务，失败落 USER_PHONE_CHANGE_LOG.SIGN_SYNC_STATUS='FAILED'。
--   在本任务建起来之前，FAILED 行只留痕、不会被重推。见 docs/domain/decisions.md ADR-D8。
--
-- ⚠️ 执行状态: 已于 2026-09-11 在 AFCITPDB 执行，生成 job_id=108，job_name='签约展示账号同步补偿'，status='0'（启动）。
--    重复执行会产生同名重复任务（主键是 job_id+job_name+job_group，job_id 自增不会冲突），
--    再次执行前 MUST 先查 sys_job 确认是否已存在。
--    回滚: DELETE FROM sys_job WHERE job_id = 108; COMMIT;
-- ============================================================
--
-- 执行前提与注意事项：
-- 1) Quartz 用内存 JobStore（ScheduleConfig 整个文件被注释掉，无 spring.quartz.job-store-type），
--    任务在 web-admin 启动时由 @PostConstruct 从 sys_job 全量加载。
--    因此本 INSERT 提交后【不会立即生效】，MUST 重启 web-admin，
--    或在管理后台「定时任务」界面对该任务做一次「修改并保存」。
-- 2) QRTZ_* 表恒为 0 行，判断任务是否在跑 MUST 查 SYS_JOB_LOG，不要看 QRTZ_JOB_DETAILS / QRTZ_TRIGGERS。
-- 3) web-admin MUST 单副本，否则每个副本各跑一份补偿（下游 CAS 能兜住正确性，但会白打 RPC）。
-- 4) web-admin 侧 MUST 已注入 ACCOUNT_SERVICE_URL（默认值 http://127.0.0.1:9098 是回环地址，
--    分 Pod 部署时等于打到 web-admin 自己）。
-- 5) concurrent='1'（禁止并发）：单批最多 200 条、每条一次 RPC，上一轮没跑完时不要再叠一轮。
-- 6) misfire_policy='3'（放弃执行）：重启期间错过的调度不补跑；待重推的行还在表里，下一轮自然会捞到。
-- 7) 本任务幂等：account-server 侧状态回写走 CAS（只接受 PENDING/FAILED），
--    前台「执行一次」与 cron 重叠触发最多多打几次 RPC，不会把已 SUCCESS 的行改回去。
--
INSERT INTO sys_job (job_name, job_group, invoke_target, cron_expression,
                     misfire_policy, concurrent, status, create_by, create_time, remark)
VALUES ('签约展示账号同步补偿（手机号变更）', 'DEFAULT', 'accountQuartzTask.compensatePhoneSignSync()',
        '0 0/5 * * * ?', '3', '1', '0', 'admin', SYSDATE,
        '每5分钟触发 account-server POST /phoneSignSyncCompensate，重推 USER_PHONE_CHANGE_LOG 中 SIGN_SYNC_STATUS 为 PENDING/FAILED 的行；单批上限 200 条、重试上限 10 次');

COMMIT;

-- 核对是否写入成功：
-- SELECT job_id, job_name, invoke_target, cron_expression, status FROM sys_job WHERE invoke_target LIKE 'accountQuartzTask.compensatePhoneSignSync%';
--
-- 重启 web-admin 后核对是否真的在跑（每 5 分钟一条）：
-- SELECT job_name, status, job_message, create_time FROM sys_job_log
--  WHERE invoke_target LIKE 'accountQuartzTask.compensatePhoneSignSync%' ORDER BY create_time DESC FETCH FIRST 20 ROWS ONLY;
--
-- 核对补偿实际效果（重推成功的行会从 FAILED 变 SUCCESS，SIGN_SYNC_TIME 刷新）：
-- SELECT SIGN_SYNC_STATUS, COUNT(*), MAX(SIGN_SYNC_TIME) FROM USER_PHONE_CHANGE_LOG GROUP BY SIGN_SYNC_STATUS;
--
-- 回滚（按上面查出的 job_id 精确删除，NEVER 用 job_name 模糊删）：
-- DELETE FROM sys_job WHERE job_id = <上面查到的 job_id>;
-- COMMIT;
