SELECT 'STEP1 实例版本（IDENTITY 需 12c+）' AS CHECK_ITEM FROM DUAL;
SELECT PRODUCT, VERSION FROM PRODUCT_COMPONENT_VERSION WHERE UPPER(PRODUCT) LIKE '%DATABASE%';

SELECT 'STEP2 当前用户与建表权限' AS CHECK_ITEM FROM DUAL;
SELECT USER AS CURRENT_USER FROM DUAL;
SELECT PRIVILEGE FROM USER_SYS_PRIVS
WHERE PRIVILEGE IN ('CREATE TABLE', 'CREATE SEQUENCE', 'CREATE ANY INDEX', 'UNLIMITED TABLESPACE')
UNION ALL
SELECT GRANTED_ROLE FROM USER_ROLE_PRIVS;

SELECT 'STEP3 目标表是否已存在（期望 0 行）' AS CHECK_ITEM FROM DUAL;
SELECT TABLE_NAME, NUM_ROWS, LAST_ANALYZED FROM USER_TABLES
WHERE TABLE_NAME IN ('LOGIC_CARD_POOL_BATCH', 'LOGIC_CARD_POOL_CARD', 'LOGIC_CARD_POOL_TYPE_LOCK')
ORDER BY TABLE_NAME;

SELECT 'STEP4 序列是否已存在（含旧名 WORK_ORDER_SEQ）' AS CHECK_ITEM FROM DUAL;
SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, LAST_NUMBER, CACHE_SIZE, CYCLE_FLAG
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN ('LOGIC_CARD_POOL_BATCH_SEQ', 'WORK_ORDER_SEQ')
ORDER BY SEQUENCE_NAME;

SELECT 'STEP5 同名约束与索引是否已被占用（期望 0 行）' AS CHECK_ITEM FROM DUAL;
SELECT CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME IN (
    'PK_LOGIC_CARD_POOL_BATCH', 'UK_LOGIC_CARD_POOL_BATCH_SEQ',
    'PK_LOGIC_CARD_POOL_CARD', 'UK_LOGIC_CARD_POOL_CARD_NO',
    'UK_LOGIC_CARD_POOL_RESERVATION', 'UK_LOGIC_CARD_POOL_BUSINESS',
    'FK_LOGIC_CARD_POOL_CARD_BATCH', 'PK_LOGIC_CARD_POOL_TYPE_LOCK')
ORDER BY CONSTRAINT_NAME;
SELECT INDEX_NAME, TABLE_NAME FROM USER_INDEXES
WHERE INDEX_NAME IN (
    'IDX_LOGIC_CARD_POOL_CARD_STATUS', 'IDX_LOGIC_CARD_POOL_CARD_AVAIL',
    'IDX_LOGIC_CARD_POOL_CARD_BUSINESS', 'IDX_LOGIC_CARD_POOL_BATCH_STATE')
ORDER BY INDEX_NAME;

SELECT 'VERIFY1 三张表齐全（期望 3 行）' AS CHECK_ITEM FROM DUAL;
SELECT TABLE_NAME FROM USER_TABLES
WHERE TABLE_NAME IN ('LOGIC_CARD_POOL_BATCH', 'LOGIC_CARD_POOL_CARD', 'LOGIC_CARD_POOL_TYPE_LOCK')
ORDER BY TABLE_NAME;

SELECT 'VERIFY2 序列存在且区间正确（期望 100000 / 999999 / N）' AS CHECK_ITEM FROM DUAL;
SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, CYCLE_FLAG FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'LOGIC_CARD_POOL_BATCH_SEQ';

SELECT 'VERIFY3 四个索引齐全（期望 4 行）' AS CHECK_ITEM FROM DUAL;
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS FROM USER_INDEXES
WHERE INDEX_NAME LIKE 'IDX_LOGIC_CARD_POOL%'
ORDER BY INDEX_NAME;

SELECT 'VERIFY4 约束齐全（期望 8 行：3 主键 + 4 唯一 + 1 外键）' AS CHECK_ITEM FROM DUAL;
SELECT CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE, STATUS FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('LOGIC_CARD_POOL_BATCH', 'LOGIC_CARD_POOL_CARD', 'LOGIC_CARD_POOL_TYPE_LOCK')
AND CONSTRAINT_TYPE IN ('P', 'U', 'R')
ORDER BY TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME;

SELECT 'VERIFY5 锁表种子数据（期望 7 行：0441 0444 0445 0446 0447 0448 044A）' AS CHECK_ITEM FROM DUAL;
SELECT CARD_TYPE, LOCK_OWNER, LOCK_TIME FROM LOGIC_CARD_POOL_TYPE_LOCK ORDER BY CARD_TYPE;

SELECT 'VERIFY6 计数列默认值与非空（期望 5 列 DEFAULT 0 且 N）' AS CHECK_ITEM FROM DUAL;
SELECT COLUMN_NAME, NULLABLE, DATA_DEFAULT FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'LOGIC_CARD_POOL_BATCH'
AND COLUMN_NAME IN ('TOTAL_COUNT', 'VALID_COUNT', 'DUPLICATE_COUNT', 'INVALID_COUNT', 'RETRY_COUNT')
ORDER BY COLUMN_NAME;

SELECT 'VERIFY7 IDENTITY 列生效确认' AS CHECK_ITEM FROM DUAL;
SELECT COLUMN_NAME, IDENTITY_COLUMN, DEFAULT_ON_NULL FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'LOGIC_CARD_POOL_CARD' AND COLUMN_NAME = 'ID';
