-- 2026-08-21 从 USER_ITP_REG_INFO 补充 PAY_TXN_DETAIL 缺失的 paymentVendor 和 requestSignSeq
-- ⚠️ 执行状态未记录；只补这两列为空的行，按 CARD_ID 关联。详见 docs/ops/生产环境清单.md 附.二.2

UPDATE PAY_TXN_DETAIL t
SET (t.PAYMENT_VENDOR, t.REQUEST_SIGN_SEQ) = (
    SELECT NVL(u.CHANNEL, ' '), NVL(u.REQ_CONTRACT_NO, ' ')
    FROM USER_ITP_REG_INFO u
    WHERE u.CARD_ID = t.CARD_ID
      AND u.DEL_YN = '1'
    AND ROWNUM = 1
)
WHERE (PAYMENT_VENDOR IS NULL OR PAYMENT_VENDOR = ' ')
   OR REQUEST_SIGN_SEQ IS NULL OR REQUEST_SIGN_SEQ = ' ';

-- 验证补充结果
SELECT COUNT(*) AS total_count,
       SUM(CASE WHEN PAYMENT_VENDOR IS NULL OR PAYMENT_VENDOR = ' ' THEN 1 ELSE 0 END) AS vendor_null_count,
       SUM(CASE WHEN REQUEST_SIGN_SEQ IS NULL OR REQUEST_SIGN_SEQ = ' ' THEN 1 ELSE 0 END) AS signseq_null_count
FROM PAY_TXN_DETAIL;
