-- ============================================================
-- 用途: 新增「卡池维护」定时任务（每 5 分钟一次）
-- 调用目标: cardPoolQuartzTask.runMaintenance()
-- 所属服务: web-admin（任务 Bean 在 web-admin，经 rpc 调 card-pool-server 9111）
-- 创建日期: 2026-09-09
-- 数据库: Oracle（sys_job.job_id 是 IDENTITY GENERATED BY DEFAULT ON NULL，可省略）
--
-- ⚠️ 执行状态: 已于 2026-09-09 15:00:26 在 AFCITPDB 执行，生成 job_id=107。
--    重复执行会产生同名重复任务（主键是 job_id+job_name+job_group，job_id 自增不会冲突），
--    再次执行前 MUST 先查 sys_job 确认是否已存在。
--    回滚: DELETE FROM sys_job WHERE job_id = 107; COMMIT;
-- ============================================================
--
-- 执行前提与注意事项：
-- 1) Quartz 用内存 JobStore（ScheduleConfig 整个文件被注释掉，无 spring.quartz.job-store-type），
--    任务在 web-admin 启动时由 @PostConstruct 从 sys_job 全量加载。
--    因此本 INSERT 提交后【不会立即生效】，MUST 重启 web-admin，
--    或在管理后台「定时任务」界面对该任务做一次「修改并保存」。
-- 2) QRTZ_* 表恒为 0 行，判断任务是否在跑 MUST 查 SYS_JOB_LOG，不要看 QRTZ_JOB_DETAILS / QRTZ_TRIGGERS。
-- 3) web-admin MUST 单副本，否则每个副本各跑一份维护。
-- 4) web-admin 侧 MUST 已注入 CARD_POOL_SERVICE_URL（默认值 http://127.0.0.1:9111 是回环地址，
--    分 Pod 部署时等于打到 web-admin 自己）。
-- 5) concurrent='1'（禁止并发）：卡池维护含 ACC 申请、FTP 下载与十万行入库，
--    上一轮没结束时 card-pool-server 侧也会返回 accepted=false 再挡一次，两层都不要放开。
-- 6) misfire_policy='3'（放弃执行）：重启期间错过的调度不补跑，下一个 5 分钟点自然会再来。
--
INSERT INTO sys_job (job_name, job_group, invoke_target, cron_expression,
                     misfire_policy, concurrent, status, create_by, create_time, remark)
VALUES ('卡池维护（回收预占/补货/推进批次）', 'DEFAULT', 'cardPoolQuartzTask.runMaintenance()',
        '0 0/5 * * * ?', '3', '1', '0', 'admin', SYSDATE,
        '每5分钟触发 card-pool-server POST /internal/card-pools/maintenance；接口只受理，执行结果看 card-pool-server 日志与 /card-pools/summary');

COMMIT;

-- 核对是否写入成功：
-- SELECT job_id, job_name, invoke_target, cron_expression, status FROM sys_job WHERE invoke_target LIKE 'cardPoolQuartzTask%';
--
-- 重启 web-admin 后核对是否真的在跑（每 5 分钟一条）：
-- SELECT job_name, status, job_message, create_time FROM sys_job_log
--  WHERE invoke_target LIKE 'cardPoolQuartzTask%' ORDER BY create_time DESC FETCH FIRST 20 ROWS ONLY;
--
-- 回滚（按上面查出的 job_id 精确删除，NEVER 用 job_name 模糊删）：
-- DELETE FROM sys_job WHERE job_id = <上面查到的 job_id>;
-- COMMIT;
