-- ============================================================
-- 用途: 新增两条 gate-txn-pay 补偿定时任务（各每 1 分钟一次）
-- 调用目标: gateTxnPayQuartzTask.recoverOfflineFare()
--           gateTxnPayQuartzTask.pushMetroTransfer()
-- 所属服务: web-admin（任务 Bean 在 web-admin，经 rpc 调 gate-txn-pay-server 9106）
-- 创建日期: 2026-09-15
-- 数据库: Oracle（sys_job.job_id 是 IDENTITY GENERATED BY DEFAULT ON NULL，可省略）
--
-- ⚠️ 执行状态: 已于 2026-09-15 在 AFCITPDB 执行，生成 job_id=120（离线码金额补偿）与 job_id=121（公交换乘推送），
--    回查确认 cron_expression='0 0/1 * * * ?'、concurrent='1'、misfire_policy='3'、status='0'。
--    重复执行会产生同名重复任务（job_id 自增不会冲突），
--    再次执行前 MUST 先查 sys_job 确认是否已存在。
--    回滚: DELETE FROM sys_job WHERE job_id IN (120, 121); COMMIT;
-- ============================================================
--
-- 背景：gate-txn-pay-server 2.0.73 把 OfflineFareRecoveryProcessor 与
-- MetroTransferPushTaskProcessor 上的 @Scheduled 摘掉了，改由本模块 Quartz 触发
-- （POST /internal/gate-txn-pay/offline-fare/recover 与 /metro-transfer/push）。
-- 【这两条 INSERT 不执行，这两条补偿链路在 2.0.73 上就完全不跑】：
--   离线码金额补偿不跑 = DISCOUNT_CALC_STATUS='OFFLINE_FARE_PENDING' 的订单永远不扣款；
--   公交换乘推送不跑 = METRO_TRANSFER_PUSH_TASK 永远堆在 READY/RETRY。
--
-- 执行前提与注意事项：
-- 1) Quartz 用内存 JobStore，任务在 web-admin 启动时由 @PostConstruct 从 sys_job 全量加载。
--    因此本 INSERT 提交后【不会立即生效】，MUST 重启 web-admin，
--    或在管理后台「定时任务」界面对该任务做一次「修改并保存」。
-- 2) QRTZ_* 表恒为 0 行，判断任务是否在跑 MUST 查 SYS_JOB_LOG。
-- 3) web-admin MUST 单副本，否则每个副本各跑一份 —— 离线码那条是【真扣款】链路。
-- 4) web-admin 侧 MUST 已注入 GATE_TXN_PAY_SERVICE_URL（本模块 env 命名是 <X>_SERVICE_URL，
--    与业务模块的 SERVICE_<X>_URL 相反，NEVER 混用）。仓库默认值已回填集群实测 Service 名。
-- 5) concurrent='1' 是【禁止并发】（'0' 才是允许，与直觉相反，见 SysJob.java:49）。
--    原实现是 fixedDelay（上一轮跑完再等 N 秒），cron 表达不了这个语义，
--    不重叠只靠这一列保证 —— 【NEVER 改成 '0'】，一改就是并发重复扣款。
--    残留差异（用户 2026-09-15 已知情并接受）：上一轮耗时接近 60 秒时，
--    下一轮会比原 fixedDelay 行为早最多 60 秒开始；不加守卫是因为守卫要么让有效频率腰斩、
--    要么须打密 cron 从而撑爆 SYS_JOB_LOG（1.1.18 起 before() 无条件先 INSERT 一行）。
-- 6) misfire_policy='3'（放弃执行）：每分钟一轮，补跑毫无意义只会挤压 Quartz worker。
-- 7) 公交换乘推送的轮询周期由原来的 10 秒变成 60 秒（用户 2026-09-15 裁决），
--    这是【外部可感知的行为变化】：公交卡系统收到换乘推送的时延上限 10s -> 60s。
--
INSERT INTO sys_job (job_name, job_group, invoke_target, cron_expression,
                     misfire_policy, concurrent, status, create_by, create_time, remark)
VALUES ('离线码金额补偿', 'DEFAULT', 'gateTxnPayQuartzTask.recoverOfflineFare()',
        '0 0/1 * * * ?', '3', '1', '0', 'admin', SYSDATE,
        '每1分钟触发 gate-txn-pay-server POST /internal/gate-txn-pay/offline-fare/recover；重算离线码出站金额并补扣款，本轮笔数看 sys_job_log 的 job_message');

INSERT INTO sys_job (job_name, job_group, invoke_target, cron_expression,
                     misfire_policy, concurrent, status, create_by, create_time, remark)
VALUES ('公交换乘推送', 'DEFAULT', 'gateTxnPayQuartzTask.pushMetroTransfer()',
        '0 0/1 * * * ?', '3', '1', '0', 'admin', SYSDATE,
        '每1分钟触发 gate-txn-pay-server POST /internal/gate-txn-pay/metro-transfer/push；投递 METRO_TRANSFER_PUSH_TASK，原为模块内 10 秒轮询');

COMMIT;

-- 核对是否写入成功：
-- SELECT job_id, job_name, invoke_target, cron_expression, concurrent, misfire_policy, status
--   FROM sys_job WHERE invoke_target LIKE 'gateTxnPayQuartzTask%';
--
-- 重启 web-admin 后核对是否真的在跑（每分钟各一条；job_message 会带本轮结论）：
-- SELECT job_name, status, job_message, create_time FROM sys_job_log
--  WHERE invoke_target LIKE 'gateTxnPayQuartzTask%' ORDER BY create_time DESC FETCH FIRST 20 ROWS ONLY;
--
-- 回滚（按上面查出的 job_id 精确删除，NEVER 用 job_name 模糊删）：
-- DELETE FROM sys_job WHERE job_id IN (<离线码那条>, <公交换乘那条>);
-- COMMIT;
