-- 参数服务建表脚本
-- Source: paradb.pdman.json
-- Note: table names have been normalized.

CREATE TABLE TBL_LINE_INFO (
    PARA_VER_NO NUMBER(6) NOT NULL,
    LINE_CODE VARCHAR2(2) NOT NULL,
    LINE_NM VARCHAR2(50) NOT NULL,
    LINE_E_NM VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_TBL_LINE_INFO PRIMARY KEY (PARA_VER_NO, LINE_CODE)
);

COMMENT ON TABLE TBL_LINE_INFO IS '线路信息参数表';
COMMENT ON COLUMN TBL_LINE_INFO.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_LINE_INFO.LINE_CODE IS '线路节点编码';
COMMENT ON COLUMN TBL_LINE_INFO.LINE_NM IS '线路中文名';
COMMENT ON COLUMN TBL_LINE_INFO.LINE_E_NM IS '线路英文名';

CREATE TABLE TBL_STATION_INFO (
    PARA_VER_NO NUMBER(6) NOT NULL,
    STATION_CODE VARCHAR2(4) NOT NULL,
    OWNER_LINE_ID VARCHAR2(2) NOT NULL,
    OWNER_INCOME_ID VARCHAR2(4) DEFAULT '0' NOT NULL,
    STATION_TYPE VARCHAR2(1) DEFAULT '0' NOT NULL,
    STATION_NM VARCHAR2(50) NOT NULL,
    STATION_E_NM VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_TBL_STATION_INFO PRIMARY KEY (PARA_VER_NO, STATION_CODE)
);

COMMENT ON TABLE TBL_STATION_INFO IS '车站信息参数表';
COMMENT ON COLUMN TBL_STATION_INFO.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_STATION_INFO.STATION_CODE IS '车站编码';
COMMENT ON COLUMN TBL_STATION_INFO.OWNER_LINE_ID IS '所属线路编码';
COMMENT ON COLUMN TBL_STATION_INFO.OWNER_INCOME_ID IS '所属收益方';
COMMENT ON COLUMN TBL_STATION_INFO.STATION_TYPE IS '车站类型';
COMMENT ON COLUMN TBL_STATION_INFO.STATION_NM IS '车站中文名';
COMMENT ON COLUMN TBL_STATION_INFO.STATION_E_NM IS '车站英文名';

CREATE TABLE TBL_TSF_INFO (
    PARA_VER_NO NUMBER(6) NOT NULL,
    FROM_STAT_CODE VARCHAR2(4) NOT NULL,
    FROM_LINE_CODE VARCHAR2(2) NOT NULL,
    TO_LINE_CODE VARCHAR2(2) NOT NULL,
    TO_STAT_CODE VARCHAR2(4) NOT NULL,
    TSF_STATION_TYPE VARCHAR2(2),
    TSF_TIME NUMBER(4) DEFAULT 60 NOT NULL,
    TSF_DISTANCE NUMBER(6) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TBL_TSF_INFO PRIMARY KEY (PARA_VER_NO, FROM_STAT_CODE, FROM_LINE_CODE, TO_STAT_CODE, TO_LINE_CODE)
);

COMMENT ON TABLE TBL_TSF_INFO IS '换乘站信息表';
COMMENT ON COLUMN TBL_TSF_INFO.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_TSF_INFO.FROM_STAT_CODE IS '换出车站节点编码';
COMMENT ON COLUMN TBL_TSF_INFO.FROM_LINE_CODE IS '换出线路节点编码';
COMMENT ON COLUMN TBL_TSF_INFO.TO_LINE_CODE IS '换入线路节点编码';
COMMENT ON COLUMN TBL_TSF_INFO.TO_STAT_CODE IS '换入车站节点编码';
COMMENT ON COLUMN TBL_TSF_INFO.TSF_STATION_TYPE IS '换乘类型';
COMMENT ON COLUMN TBL_TSF_INFO.TSF_TIME IS '换乘时间';
COMMENT ON COLUMN TBL_TSF_INFO.TSF_DISTANCE IS '换乘距离';

CREATE TABLE TBL_ZONE_INFO (
    PARA_VER_NO NUMBER(6) NOT NULL,
    ZONE_NO NUMBER(6) NOT NULL,
    ZONE_NAME VARCHAR2(50) NOT NULL,
    ZONE_E_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_TBL_ZONE_INFO PRIMARY KEY (PARA_VER_NO, ZONE_NO)
);

COMMENT ON TABLE TBL_ZONE_INFO IS '区域信息参数表';
COMMENT ON COLUMN TBL_ZONE_INFO.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_ZONE_INFO.ZONE_NO IS '区域编号';
COMMENT ON COLUMN TBL_ZONE_INFO.ZONE_NAME IS '区域中文名';
COMMENT ON COLUMN TBL_ZONE_INFO.ZONE_E_NAME IS '区域英文名';

CREATE TABLE TBL_ZONE_DTL (
    PARA_VER_NO NUMBER(6) NOT NULL,
    ZONE_NO NUMBER(4) NOT NULL,
    SEQ_NO NUMBER(9) NOT NULL,
    STATION_CODE VARCHAR2(4) NOT NULL,
    CONSTRAINT PK_TBL_ZONE_DTL PRIMARY KEY (PARA_VER_NO, ZONE_NO, SEQ_NO)
);

COMMENT ON TABLE TBL_ZONE_DTL IS '区域车站参数表';
COMMENT ON COLUMN TBL_ZONE_DTL.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_ZONE_DTL.ZONE_NO IS '区域编号';
COMMENT ON COLUMN TBL_ZONE_DTL.SEQ_NO IS '序列号';
COMMENT ON COLUMN TBL_ZONE_DTL.STATION_CODE IS '车站编号';

CREATE TABLE TBL_SECT_INFO (
    PARA_VER_NO NUMBER(6) NOT NULL,
    SECT_NO NUMBER(6) NOT NULL,
    SECT_NAME VARCHAR2(50) NOT NULL,
    SECT_E_NAME VARCHAR2(50) NOT NULL,
    STAT_CODE1 VARCHAR2(4) NOT NULL,
    STAT_CODE2 VARCHAR2(4) NOT NULL,
    CONSTRAINT PK_TBL_SECT_INFO PRIMARY KEY (PARA_VER_NO, SECT_NO)
);

COMMENT ON TABLE TBL_SECT_INFO IS '区段信息参数';
COMMENT ON COLUMN TBL_SECT_INFO.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_SECT_INFO.SECT_NO IS '区段编号';
COMMENT ON COLUMN TBL_SECT_INFO.SECT_NAME IS '区段中文名';
COMMENT ON COLUMN TBL_SECT_INFO.SECT_E_NAME IS '区段英文名';
COMMENT ON COLUMN TBL_SECT_INFO.STAT_CODE1 IS '开始车站编码';
COMMENT ON COLUMN TBL_SECT_INFO.STAT_CODE2 IS '结束车站编码';

CREATE TABLE TBL_SPECIAL_DATE (
    PARA_VER_NO NUMBER(6) NOT NULL,
    SEQ_NO NUMBER(9) NOT NULL,
    DATE_TYPE VARCHAR2(4) NOT NULL,
    SPECIAL_DATE VARCHAR2(8) NOT NULL,
    LAST_UPD_USER VARCHAR2(10) NOT NULL,
    LAST_UPD_TMS DATE NOT NULL,
    CONSTRAINT PK_TBL_SPECIAL_DATE PRIMARY KEY (PARA_VER_NO, SEQ_NO)
);

COMMENT ON TABLE TBL_SPECIAL_DATE IS '特殊日期参数表';
COMMENT ON COLUMN TBL_SPECIAL_DATE.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_SPECIAL_DATE.SEQ_NO IS '序列号';
COMMENT ON COLUMN TBL_SPECIAL_DATE.DATE_TYPE IS '日期类型';
COMMENT ON COLUMN TBL_SPECIAL_DATE.SPECIAL_DATE IS '特殊日期';
COMMENT ON COLUMN TBL_SPECIAL_DATE.LAST_UPD_USER IS '最后更新者';
COMMENT ON COLUMN TBL_SPECIAL_DATE.LAST_UPD_TMS IS '最后更新时间';

CREATE TABLE TBL_TIME_INTERVAL (
    PARA_VER_NO NUMBER(6) NOT NULL,
    INTERVAL_NO NUMBER(9) NOT NULL,
    BEGIN_TIME VARCHAR2(6) NOT NULL,
    END_TIME VARCHAR2(6) NOT NULL,
    LAST_UPD_USER VARCHAR2(10) NOT NULL,
    LAST_UPD_TMS DATE NOT NULL,
    CONSTRAINT PK_TBL_TIME_INTERVAL PRIMARY KEY (PARA_VER_NO, INTERVAL_NO)
);

COMMENT ON TABLE TBL_TIME_INTERVAL IS '时间段参数表';
COMMENT ON COLUMN TBL_TIME_INTERVAL.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_TIME_INTERVAL.INTERVAL_NO IS '时间段编号';
COMMENT ON COLUMN TBL_TIME_INTERVAL.BEGIN_TIME IS '时间段开始时间';
COMMENT ON COLUMN TBL_TIME_INTERVAL.END_TIME IS '时间段结束时间';
COMMENT ON COLUMN TBL_TIME_INTERVAL.LAST_UPD_USER IS '最后更新者';
COMMENT ON COLUMN TBL_TIME_INTERVAL.LAST_UPD_TMS IS '最后更新时间';

CREATE TABLE TBL_FARE_TIME (
    PARA_VER_NO NUMBER(6) NOT NULL,
    FARE_TIER NUMBER(4) NOT NULL,
    ALLOWED_TIME NUMBER(6) NOT NULL,
    LAST_UPD_USER VARCHAR2(10) NOT NULL,
    LAST_UPD_TMS DATE NOT NULL,
    CONSTRAINT PK_TBL_FARE_TIME PRIMARY KEY (PARA_VER_NO, FARE_TIER)
);

COMMENT ON TABLE TBL_FARE_TIME IS '超时时间参数表';
COMMENT ON COLUMN TBL_FARE_TIME.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_FARE_TIME.FARE_TIER IS '费率等级代码';
COMMENT ON COLUMN TBL_FARE_TIME.ALLOWED_TIME IS '时间';
COMMENT ON COLUMN TBL_FARE_TIME.LAST_UPD_USER IS '最后更新者';
COMMENT ON COLUMN TBL_FARE_TIME.LAST_UPD_TMS IS '最后更新时间';

CREATE TABLE TBL_CHIP_TYPE (
    PARA_VER_NO NUMBER(6) NOT NULL,
    CHIP_TYPE VARCHAR2(2) NOT NULL,
    DURATION_DAYS NUMBER(8) NOT NULL,
    MAX_IO_TIMES NUMBER(8) NOT NULL,
    LAST_UPD_USER VARCHAR2(10) NOT NULL,
    LAST_UPD_TMS DATE NOT NULL,
    CONSTRAINT PK_TBL_CHIP_TYPE PRIMARY KEY (PARA_VER_NO, CHIP_TYPE)
);

COMMENT ON TABLE TBL_CHIP_TYPE IS '芯片类型参数表';
COMMENT ON COLUMN TBL_CHIP_TYPE.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_CHIP_TYPE.CHIP_TYPE IS '票卡芯片类型';
COMMENT ON COLUMN TBL_CHIP_TYPE.DURATION_DAYS IS '有效期天数';
COMMENT ON COLUMN TBL_CHIP_TYPE.MAX_IO_TIMES IS '最大交易次数';
COMMENT ON COLUMN TBL_CHIP_TYPE.LAST_UPD_USER IS '最后更新者';
COMMENT ON COLUMN TBL_CHIP_TYPE.LAST_UPD_TMS IS '最后更新时间';

CREATE TABLE TBL_TICKET_TYPE (
    PARA_VER_NO NUMBER(6) NOT NULL,
    TICKET_TYPE NUMBER(4) NOT NULL,
    TICKET_DESC_CH_PTR VARCHAR2(50) NOT NULL,
    TICKET_DESC_EN VARCHAR2(50) NOT NULL,
    TICKET_MAIN_TYPE NUMBER(4) NOT NULL,
    ISSUER_TYPE NUMBER(3) NOT NULL,
    PRICE_TYPE NUMBER(3) NOT NULL,
    AREA_FLAG VARCHAR2(4) NOT NULL,
    PASSENGER_TIME NUMBER(10) NOT NULL,
    SALE_AMT NUMBER(9) NOT NULL,
    SIGN_TERM VARCHAR2(32) NOT NULL,
    RETURN_TICKET_BATCH VARCHAR2(10) NOT NULL,
    MAX_USE_NUM NUMBER(10) NOT NULL,
    MAX_USE_DAYS NUMBER(10) NOT NULL,
    SOUND_TYPE NUMBER(10) NOT NULL,
    LAMP_COLOR_TYPE NUMBER(10) NOT NULL,
    ADD_MIN_VALUE NUMBER(9) NOT NULL,
    MAX_REMAIN_VALUE NUMBER(9) NOT NULL,
    ENTER_MIN_VALUE NUMBER(9) NOT NULL,
    EXT_MIN_VALUE NUMBER(9) NOT NULL,
    DEP_AMT NUMBER(9) NOT NULL,
    DEPRECIATION_AMT NUMBER(9) NOT NULL,
    MAX_RETURN_AMT NUMBER(9) NOT NULL,
    RETURN_FEE NUMBER(9) NOT NULL,
    MAX_TIMES NUMBER(8) NOT NULL,
    MAX_TIMES_CYCLE NUMBER(3) DEFAULT 0 NOT NULL,
    DURATION_TYPE NUMBER(4) NOT NULL,
    DURATION_DAYS NUMBER(10) NOT NULL,
    ACTIVE_VALID_DAYS NUMBER(10) NOT NULL,
    FIX_END_DATE VARCHAR2(8) NOT NULL,
    MAX_REENTR_PERIOD NUMBER(10) NOT NULL,
    MAX_REENTR_FEE NUMBER(9) NOT NULL,
    OVERTIME_FEE NUMBER(9) NOT NULL,
    NO_EXIT_FEE NUMBER(9) NOT NULL,
    MISMATCH_FEE NUMBER(9) NOT NULL,
    TWICE_TXN_TIME NUMBER(9) NOT NULL,
    SALE_WAY VARCHAR2(16) NOT NULL,
    CONT_SAF_TIME NUMBER(9) NOT NULL,
    CONT_SAF_ERROR_TIME NUMBER(9) NOT NULL,
    CONT_AMT NUMBER(9) NOT NULL,
    TOTAL_SALE_WAY VARCHAR2(9) NOT NULL,
    UNFINISHED_CHARGE_AMT NUMBER(9) NOT NULL,
    INTERCONN_UPDATE_CTRL NUMBER(3) NOT NULL,
    LAST_UPD_USER VARCHAR2(10) NOT NULL,
    LAST_UPD_TMS DATE NOT NULL,
    CONSTRAINT PK_TBL_TICKET_TYPE PRIMARY KEY (PARA_VER_NO, TICKET_TYPE)
);

COMMENT ON TABLE TBL_TICKET_TYPE IS '车票类型参数表';
COMMENT ON COLUMN TBL_TICKET_TYPE.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_TICKET_TYPE.TICKET_TYPE IS '车票类型';
COMMENT ON COLUMN TBL_TICKET_TYPE.TICKET_DESC_CH_PTR IS '车票类型中文名称';
COMMENT ON COLUMN TBL_TICKET_TYPE.TICKET_DESC_EN IS '车票类型英文名称';
COMMENT ON COLUMN TBL_TICKET_TYPE.TICKET_MAIN_TYPE IS '车票主类型';
COMMENT ON COLUMN TBL_TICKET_TYPE.ISSUER_TYPE IS '车票发行方';
COMMENT ON COLUMN TBL_TICKET_TYPE.PRICE_TYPE IS '车票计价方式';
COMMENT ON COLUMN TBL_TICKET_TYPE.AREA_FLAG IS '使用范围限制标志';
COMMENT ON COLUMN TBL_TICKET_TYPE.PASSENGER_TIME IS '计次票乘客次数';
COMMENT ON COLUMN TBL_TICKET_TYPE.SALE_AMT IS '固定发售价格';
COMMENT ON COLUMN TBL_TICKET_TYPE.SIGN_TERM IS '标志项';
COMMENT ON COLUMN TBL_TICKET_TYPE.RETURN_TICKET_BATCH IS '回收废票发行批次';
COMMENT ON COLUMN TBL_TICKET_TYPE.MAX_USE_NUM IS '回收废票最大使用次数';
COMMENT ON COLUMN TBL_TICKET_TYPE.MAX_USE_DAYS IS '回收废票最大使用天数';
COMMENT ON COLUMN TBL_TICKET_TYPE.SOUND_TYPE IS '提示音ID';
COMMENT ON COLUMN TBL_TICKET_TYPE.LAMP_COLOR_TYPE IS '灯光提示ID';
COMMENT ON COLUMN TBL_TICKET_TYPE.ADD_MIN_VALUE IS '最小充值金额';
COMMENT ON COLUMN TBL_TICKET_TYPE.MAX_REMAIN_VALUE IS '储值票最大余额';
COMMENT ON COLUMN TBL_TICKET_TYPE.ENTER_MIN_VALUE IS '最小进站金额';
COMMENT ON COLUMN TBL_TICKET_TYPE.EXT_MIN_VALUE IS '最小出站金额';
COMMENT ON COLUMN TBL_TICKET_TYPE.DEP_AMT IS '押金';
COMMENT ON COLUMN TBL_TICKET_TYPE.DEPRECIATION_AMT IS '折旧计算参数';
COMMENT ON COLUMN TBL_TICKET_TYPE.MAX_RETURN_AMT IS '最大即时退票金额';
COMMENT ON COLUMN TBL_TICKET_TYPE.RETURN_FEE IS '退票手续费';
COMMENT ON COLUMN TBL_TICKET_TYPE.MAX_TIMES IS '乘车次数';
COMMENT ON COLUMN TBL_TICKET_TYPE.MAX_TIMES_CYCLE IS '乘车次数统计周期';
COMMENT ON COLUMN TBL_TICKET_TYPE.DURATION_TYPE IS '车票有效期类别';
COMMENT ON COLUMN TBL_TICKET_TYPE.DURATION_DAYS IS '车票发售有效天数';
COMMENT ON COLUMN TBL_TICKET_TYPE.ACTIVE_VALID_DAYS IS '车票激活有效天数';
COMMENT ON COLUMN TBL_TICKET_TYPE.FIX_END_DATE IS '固定截止有效日期';
COMMENT ON COLUMN TBL_TICKET_TYPE.MAX_REENTR_PERIOD IS '重复进站免费更新最大时限';
COMMENT ON COLUMN TBL_TICKET_TYPE.MAX_REENTR_FEE IS '重复进站更新罚款金额';
COMMENT ON COLUMN TBL_TICKET_TYPE.OVERTIME_FEE IS '超时罚款金额';
COMMENT ON COLUMN TBL_TICKET_TYPE.NO_EXIT_FEE IS '进出站不匹配罚款金额（进站端）';
COMMENT ON COLUMN TBL_TICKET_TYPE.MISMATCH_FEE IS '非罚款车站过闸罚款金额';
COMMENT ON COLUMN TBL_TICKET_TYPE.TWICE_TXN_TIME IS '两次交易时间间隔';
COMMENT ON COLUMN TBL_TICKET_TYPE.SALE_WAY IS '优惠方式';
COMMENT ON COLUMN TBL_TICKET_TYPE.CONT_SAF_TIME IS '联程优惠时间间隔';
COMMENT ON COLUMN TBL_TICKET_TYPE.CONT_SAF_ERROR_TIME IS '联程优惠误差时间';
COMMENT ON COLUMN TBL_TICKET_TYPE.CONT_AMT IS '联乘优惠';
COMMENT ON COLUMN TBL_TICKET_TYPE.TOTAL_SALE_WAY IS '累计优惠方式';
COMMENT ON COLUMN TBL_TICKET_TYPE.UNFINISHED_CHARGE_AMT IS '异地交通部互联互通卡交易未完成收费金额';
COMMENT ON COLUMN TBL_TICKET_TYPE.INTERCONN_UPDATE_CTRL IS '异地交通部互联互通卡更新控制';
COMMENT ON COLUMN TBL_TICKET_TYPE.LAST_UPD_USER IS '最后更新者';
COMMENT ON COLUMN TBL_TICKET_TYPE.LAST_UPD_TMS IS '最后更新时间';

CREATE TABLE TBL_TOTAL_SALE_PART (
    PARA_VER_NO NUMBER(6) NOT NULL,
    TICKET_TYPE NUMBER(4) NOT NULL,
    PART_SEQ_NO NUMBER(4) NOT NULL,
    BEGIN_TOTAL_SALE NUMBER(9) NOT NULL,
    END_TOTAL_SALE NUMBER(9) NOT NULL,
    SALE_RATIO NUMBER(6) NOT NULL,
    LAST_UPD_USER VARCHAR2(10) NOT NULL,
    LAST_UPD_TMS DATE NOT NULL,
    CONSTRAINT PK_TBL_TOTAL_SALE_PART PRIMARY KEY (PARA_VER_NO, TICKET_TYPE, PART_SEQ_NO)
);

COMMENT ON TABLE TBL_TOTAL_SALE_PART IS '累计优惠分段参数表';
COMMENT ON COLUMN TBL_TOTAL_SALE_PART.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_TOTAL_SALE_PART.TICKET_TYPE IS '车票类型';
COMMENT ON COLUMN TBL_TOTAL_SALE_PART.PART_SEQ_NO IS '累计优惠分段序号';
COMMENT ON COLUMN TBL_TOTAL_SALE_PART.BEGIN_TOTAL_SALE IS '开始累计发售金额';
COMMENT ON COLUMN TBL_TOTAL_SALE_PART.END_TOTAL_SALE IS '结束累计发售金额';
COMMENT ON COLUMN TBL_TOTAL_SALE_PART.SALE_RATIO IS '优惠比例';
COMMENT ON COLUMN TBL_TOTAL_SALE_PART.LAST_UPD_USER IS '最后更新者';
COMMENT ON COLUMN TBL_TOTAL_SALE_PART.LAST_UPD_TMS IS '最后更新时间';

CREATE TABLE TBL_ADD_PARA (
    PARA_VER_NO NUMBER(6) NOT NULL,
    BANK_MIN_AMT NUMBER(9) NOT NULL,
    BANK_MAX_AMT NUMBER(9) NOT NULL,
    LAST_UPD_USER VARCHAR2(10) NOT NULL,
    LAST_UPD_TMS DATE NOT NULL,
    CONSTRAINT PK_TBL_ADD_PARA PRIMARY KEY (PARA_VER_NO)
);

COMMENT ON TABLE TBL_ADD_PARA IS '银行卡充值参数表';
COMMENT ON COLUMN TBL_ADD_PARA.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_ADD_PARA.BANK_MIN_AMT IS '银行卡最小支付金额';
COMMENT ON COLUMN TBL_ADD_PARA.BANK_MAX_AMT IS '银行卡最大字符金额';
COMMENT ON COLUMN TBL_ADD_PARA.LAST_UPD_USER IS '最后更新者';
COMMENT ON COLUMN TBL_ADD_PARA.LAST_UPD_TMS IS '最后更新时间';

CREATE TABLE TBL_BASE_FARE (
    PARA_VER_NO NUMBER(6) NOT NULL,
    FARE_TYPE NUMBER(6) NOT NULL,
    FARE_TIER NUMBER(4) NOT NULL,
    TICKET_PRICE NUMBER(9) NOT NULL,
    CONSTRAINT PK_TBL_BASE_FARE PRIMARY KEY (PARA_VER_NO, FARE_TYPE, FARE_TIER)
);

COMMENT ON TABLE TBL_BASE_FARE IS '费率类型参数表';
COMMENT ON COLUMN TBL_BASE_FARE.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_BASE_FARE.FARE_TYPE IS '费率组代码';
COMMENT ON COLUMN TBL_BASE_FARE.FARE_TIER IS '费率等级';
COMMENT ON COLUMN TBL_BASE_FARE.TICKET_PRICE IS '费率值';

CREATE TABLE TBL_FARE_MATRIX (
    PARA_VER_NO NUMBER(6) NOT NULL,
    BEGIN_STAT_CODE VARCHAR2(4) NOT NULL,
    END_STAT_CODE VARCHAR2(4) NOT NULL,
    FARE_TIER NUMBER(4) NOT NULL,
    CONSTRAINT PK_TBL_FARE_MATRIX PRIMARY KEY (PARA_VER_NO, BEGIN_STAT_CODE, END_STAT_CODE)
);

COMMENT ON TABLE TBL_FARE_MATRIX IS '费率等级参数表';
COMMENT ON COLUMN TBL_FARE_MATRIX.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_FARE_MATRIX.BEGIN_STAT_CODE IS '进站车站编码';
COMMENT ON COLUMN TBL_FARE_MATRIX.END_STAT_CODE IS '出站车站编码';
COMMENT ON COLUMN TBL_FARE_MATRIX.FARE_TIER IS '费率等级';

CREATE TABLE TBL_TICKET_FARE (
    PARA_VER_NO NUMBER(6) NOT NULL,
    TICKET_TYPE NUMBER(4) NOT NULL,
    CHIP_TYPE VARCHAR2(2) NOT NULL,
    FARE_GROUP_NO NUMBER(6) NOT NULL,
    LAST_UPD_USER VARCHAR2(10) NOT NULL,
    LAST_UPD_TMS DATE NOT NULL,
    CONSTRAINT PK_TBL_TICKET_FARE PRIMARY KEY (PARA_VER_NO, TICKET_TYPE, CHIP_TYPE)
);

COMMENT ON TABLE TBL_TICKET_FARE IS '车票费率参数表';
COMMENT ON COLUMN TBL_TICKET_FARE.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_TICKET_FARE.TICKET_TYPE IS '车票类型';
COMMENT ON COLUMN TBL_TICKET_FARE.CHIP_TYPE IS '票卡芯片类型';
COMMENT ON COLUMN TBL_TICKET_FARE.FARE_GROUP_NO IS '费率类型代码';
COMMENT ON COLUMN TBL_TICKET_FARE.LAST_UPD_USER IS '最后更新者';
COMMENT ON COLUMN TBL_TICKET_FARE.LAST_UPD_TMS IS '最后更新时间';

CREATE TABLE TBL_FARE_GROUP (
    PARA_VER_NO NUMBER(6) NOT NULL,
    DATE_TYPE NUMBER(4) NOT NULL,
    FARE_TYPE NUMBER(6) NOT NULL,
    INTERVAL_NO NUMBER(9) NOT NULL,
    FARE_GROUP NUMBER(6) NOT NULL,
    LAST_UPD_USER VARCHAR2(10) NOT NULL,
    LAST_UPD_TMS DATE NOT NULL,
    CONSTRAINT PK_TBL_FARE_GROUP PRIMARY KEY (PARA_VER_NO, DATE_TYPE, FARE_TYPE, INTERVAL_NO)
);

COMMENT ON TABLE TBL_FARE_GROUP IS '费率组参数表';
COMMENT ON COLUMN TBL_FARE_GROUP.PARA_VER_NO IS '参数版本号';
COMMENT ON COLUMN TBL_FARE_GROUP.DATE_TYPE IS '特殊日期类型';
COMMENT ON COLUMN TBL_FARE_GROUP.FARE_TYPE IS '费率类型';
COMMENT ON COLUMN TBL_FARE_GROUP.INTERVAL_NO IS '时间段编号';
COMMENT ON COLUMN TBL_FARE_GROUP.FARE_GROUP IS '费率组代码';
COMMENT ON COLUMN TBL_FARE_GROUP.LAST_UPD_USER IS '最后更新者';
COMMENT ON COLUMN TBL_FARE_GROUP.LAST_UPD_TMS IS '最后更新时间';

CREATE TABLE TBL_PARA_VERSION (
    PARA_TYPE VARCHAR2(4) NOT NULL,
    CURRENT_VER_NO NUMBER(10) NOT NULL,
    CURRENT_FILE_NAME VARCHAR2(100),
    VALID_DATE_TIME VARCHAR2(14),
    MD5_VALUE VARCHAR2(32),
    LAST_UPD_USER VARCHAR2(10) DEFAULT 'itp' NOT NULL,
    LAST_UPD_TMS DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TBL_PARA_VERSION PRIMARY KEY (PARA_TYPE)
);

COMMENT ON TABLE TBL_PARA_VERSION IS '参数当前版本维护表';
COMMENT ON COLUMN TBL_PARA_VERSION.PARA_TYPE IS '参数类型，0001路网，0002日历，0003车票，0004费率';
COMMENT ON COLUMN TBL_PARA_VERSION.CURRENT_VER_NO IS '当前已入库参数版本号';
COMMENT ON COLUMN TBL_PARA_VERSION.CURRENT_FILE_NAME IS '当前已入库参数文件名';
COMMENT ON COLUMN TBL_PARA_VERSION.VALID_DATE_TIME IS '参数生效时间';
COMMENT ON COLUMN TBL_PARA_VERSION.MD5_VALUE IS '当前已入库参数文件MD5';
COMMENT ON COLUMN TBL_PARA_VERSION.LAST_UPD_USER IS '最后更新者';
COMMENT ON COLUMN TBL_PARA_VERSION.LAST_UPD_TMS IS '最后更新时间';

