spring.application.name=employee-card-acc-simulator
server.port=9114

acc-simulator.fep-acc-base-url=${ACC_SIMULATOR_FEP_ACC_BASE_URL:http://172.20.211.200:48000/fep-acc}
acc-simulator.provider-id=06
acc-simulator.charset=UTF-8
acc-simulator.format=json
acc-simulator.device-id=ACC-SIMULATOR
acc-simulator.sign-type=00
acc-simulator.history-limit=50


other.web.unSafeUrlChars=null
other.web.enableLogRequestInFilter=true
other.web.enableBodyCacheFilter=true
other.web.enableLogTakeTimesInInterceptor=true
knife4j.production=false

other.sql.host=${DB_HOST:172.20.222.3}
other.sql.double-datasource=false
other.sql.type=oracle
other.sql.page.type=oracle
other.sql.database=${DB_NAME:AFCITPDB}
other.sql.username=${DB_USERNAME:qditp}
other.sql.password=${DB_PASSWORD:qditp}
mybatis.mapper-locations=classpath*:mapper/*.xml

spring.jackson.default-property-inclusion=non_null
