spring.datasource.url=jdbc:db2://${other.sql.host}/${other.sql.database}
spring.datasource.username=${other.sql.username}
spring.datasource.password=${other.sql.password}
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
