spring.datasource.druid.url=jdbc:dm://${other.sql.host}
spring.datasource.druid.username=${other.sql.username}
spring.datasource.druid.password=${other.sql.password}
spring.datasource.druid.driver-class-name=dm.jdbc.driver.DmDriver
spring.datasource.druid.filter.wall.enabled=false