spring.datasource.url=jdbc:oracle:thin:@${other.sql.host}/${other.sql.database}
spring.datasource.username=${other.sql.username}
spring.datasource.password=${other.sql.password}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
