other.sql.double-datasource=false
other.sql.type=mysql
other.sql.page.type=mysql
other.sql.host=localhost:3306
other.sql.database=test
other.sql.username=test
other.sql.password=test
other.sql.rows.warn=1000
other.sql.print.pre=false
other.sql.audit=true
#
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.filter.stat.db-type=${other.sql.type}
spring.datasource.druid.filter.wall.db-type=${other.sql.type}
spring.datasource.druid.filter.stat.slow-sql-millis=2000
spring.datasource.druid.max-active=80
spring.datasource.druid.initial-size=5
spring.datasource.druid.min-idle=5
spring.datasource.druid.max-wait=15000
spring.datasource.druid.pool-prepared-statements=true
spring.datasource.druid.max-pool-prepared-statement-per-connection-size=20
spring.datasource.druid.validation-query=SELECT 1 FROM DUAL
spring.datasource.druid.validation-query-timeout=5000
spring.datasource.druid.test-on-borrow=false
spring.datasource.druid.test-on-return=false
spring.datasource.druid.test-while-idle=true
spring.datasource.druid.time-between-eviction-runs-millis=15000
spring.datasource.druid.min-evictable-idle-time-millis=120000
spring.datasource.druid.web-stat-filter.enabled=true
spring.datasource.druid.web-stat-filter.url-pattern=/*
spring.datasource.druid.web-stat-filter.exclusions='*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
spring.datasource.druid.stat-view-servlet.enabled=true
spring.datasource.druid.stat-view-servlet.allow=
spring.datasource.druid.stat-view-servlet.url-pattern=/druid/*
spring.datasource.druid.stat-view-servlet.reset-enable=true
spring.datasource.druid.stat-view-servlet.login-username=admin
spring.datasource.druid.stat-view-servlet.login-password=admin
spring.datasource.druid.filter.stat.enabled=true
spring.datasource.druid.filter.stat.log-slow-sql=true
spring.datasource.druid.filter.wall.enabled=true
spring.datasource.druid.filter.wall.config.delete-allow=true
spring.datasource.druid.filter.wall.config.drop-table-allow=true
#