-- AGM 密钥同步日志表（ADR-D169 延伸设计）
-- 用于记录每次密钥同步的详细信息，便于问题排查和审计

CREATE TABLE GATE_KEY_SYNC_LOG (
    ID                  NUMBER(20) NOT NULL,
    DEVICE_ID           VARCHAR2(20 CHAR) NOT NULL,
    SYNC_DATE           TIMESTAMP(6) NOT NULL,
    REQ_BIZ_DATA        CLOB,
    REQ_KEY_COUNT       NUMBER(10) DEFAULT 0 NOT NULL,
    RESP_RET_CODE       VARCHAR2(10 CHAR),
    RESP_RET_MSG        VARCHAR2(200 CHAR),
    RESP_KEY_VERSION_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    PROCESS_DURATION_MS NUMBER(10),
    STATUS              VARCHAR2(20 CHAR) DEFAULT 'SUCCESS' NOT NULL,
    ERROR_MSG           VARCHAR2(512 CHAR),
    CREATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    
    CONSTRAINT PK_GATE_KEY_SYNC_LOG PRIMARY KEY (ID)
);

-- 索引：按设备查询
CREATE INDEX IDX_KEY_SYNC_LOG_DEVICE ON GATE_KEY_SYNC_LOG (DEVICE_ID, SYNC_DATE);

-- 索引：按状态查询
CREATE INDEX IDX_KEY_SYNC_LOG_STATUS ON GATE_KEY_SYNC_LOG (STATUS, SYNC_DATE);

COMMENT ON TABLE GATE_KEY_SYNC_LOG IS 'AGM密钥同步日志表（ADR-D169）';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.ID IS '主键';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.DEVICE_ID IS '设备编号';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.SYNC_DATE IS '同步时间';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.REQ_BIZ_DATA IS '请求原始报文（bizData）';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.REQ_KEY_COUNT IS '设备上报的密钥版本数量';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.RESP_RET_CODE IS '响应返回码（0000=成功）';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.RESP_RET_MSG IS '响应返回信息';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.RESP_KEY_VERSION_COUNT IS '下发给设备的密钥版本数量';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.PROCESS_DURATION_MS IS '处理耗时（毫秒）';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.STATUS IS '同步状态：SUCCESS=成功, FAIL=失败';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.ERROR_MSG IS '失败原因';
COMMENT ON COLUMN GATE_KEY_SYNC_LOG.CREATE_TIME IS '记录创建时间';

-- 序列
CREATE SEQUENCE SEQ_GATE_KEY_SYNC_LOG
    START WITH 1
    INCREMENT BY 1
    CACHE 100
    NOCYCLE;

-- 数据保留策略：建议按季度清理，保留最近 1 年数据
-- DELETE FROM GATE_KEY_SYNC_LOG WHERE SYNC_DATE < ADD_MONTHS(SYSDATE, -12);
