-- 二维码过闸扣费订单表
-- Oracle 月分区表，TXN_DATE 使用字符串 YYYYMMDD 入库。
-- 本表只保存地铁侧过闸订单和扣费结果，支付渠道明细、回调报文放支付侧表（PAY_TXN_DETAIL）。
-- 注意：本表按出站交易日期 TXN_DATE 手动维护月分区，P_MAX 仅作为兜底分区。
--
-- 2026-09-14：本文件已按 AFCITPDB 库内实际结构整体对齐（列清单 / 长度 / 可空性 / 默认值 / 列注释
-- 全部取自 USER_TAB_COLS + USER_COL_COMMENTS 实测；长度一律以 CHAR_LENGTH 为准，
-- NEVER 用 DATA_LENGTH 判长度，库字符集下 8 字符 = 16 字节，曾据此误记过 TXN_DATE 是 VARCHAR2(16)）。
-- 对齐前后的差异：补进 13 列钱包优惠 / 换乘列（PAYMENT_VENDOR ~ DISCOUNT_CALC_MSG），
-- 删掉库里并不存在的 3 列（PAY_CHANNEL_CODE / DISCOUNT_FEE / DISCOUNT_INFO，全仓零代码引用），
-- 约 18 列长度改小、CARD_TYPE 由 NOT NULL 改为可空。索引与分区实测与本文件一致，未改。
--
-- 遗留待业务确认的注释语义冲突（本文件现按库内原文写，与改动前的说法不同，NEVER 当成笔误改回）：
-- 1. COUNTING_TIMES：库注释「计次票剩余可用次数」，实体注释「计次票剩余次数（扣减后）」
--    （GateTxnPay.java:42），而本文件此前写「本次行程消耗次数（恒为 1），NEVER 回填剩余次数」。
--    代码实际是「取上游上送值，日票缺省 1」（GateTxnPayServiceImpl.java:372），两种解读都能套上，
--    语义 MUST 与业务确认后再定稿，NEVER 据本行注释直接改写入逻辑。
-- 2. COUNTING_FLAG：库注释「1=计时,2=计次」，但代码走的是 Y/N（GateTxnPayQueryServiceImpl.java:264
--    兜底 'N'，GateTxnPay.java:43 注释「Y是,N否」）。**取值域以代码为准**，库注释疑似过期。
-- 3. TICKET_STATUS：库多出 02 进站 / 03 进站超时 / 80 自助补出站，此前少记这三个、且 07 与 06 对不上。
-- 4. ORDER_EXP_TYPE：库是 0~5 六个值，此前只写 0/1/2。
-- 5. COMPANION_FLAG：库叫「同行票」，此前叫「陪同票」。

CREATE TABLE GATE_TXN_PAY (
    ID                  NUMBER(20) NOT NULL,

    ORDER_NO            VARCHAR2(64 CHAR) NOT NULL,
    DEBIT_STATUS        VARCHAR2(16 CHAR) DEFAULT 'INIT' NOT NULL,

    THIRD_USER_ID       VARCHAR2(64 CHAR),
    CARD_ID             VARCHAR2(32 CHAR) NOT NULL,
    CARD_TYPE           VARCHAR2(8 CHAR),
    DEVICE_ID           VARCHAR2(16 CHAR),
    TRX_TYPE            VARCHAR2(4 CHAR) NOT NULL,
    TICKET_TRANS_SEQ    VARCHAR2(64 CHAR),

    IN_STATION          VARCHAR2(16 CHAR),
    IN_TIME             VARCHAR2(14 CHAR),
    OUT_STATION         VARCHAR2(16 CHAR),
    OUT_TIME            VARCHAR2(14 CHAR) NOT NULL,
    TXN_DATE            VARCHAR2(8 CHAR) NOT NULL,

    TRX_AMOUNT          NUMBER(12) DEFAULT 0 NOT NULL,
    OVERTIME_AMOUNT     NUMBER(12) DEFAULT 0 NOT NULL,
    TOTAL_AMOUNT        NUMBER(12) DEFAULT 0 NOT NULL,

    ISSUE_CHANNEL_CODE  VARCHAR2(8 CHAR),
    SIGN_CHANNEL_CODE   VARCHAR2(8 CHAR),
    REMARK              VARCHAR2(512 CHAR),

    CREATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    TICKET_STATUS       VARCHAR2(8 CHAR),
    ORDER_EXP_TYPE      VARCHAR2(8 CHAR),
    OFFLINE_FLAG        VARCHAR2(2 CHAR) DEFAULT 'N',
    ENTRY_STATION_NAME  VARCHAR2(64 CHAR),
    EXIT_STATION_NAME   VARCHAR2(64 CHAR),
    COMPANION_FLAG      VARCHAR2(2 CHAR) DEFAULT 'N',
    TICKET_CODE         VARCHAR2(64 CHAR),
    COUNTING_TIMES      NUMBER(10),
    COUNTING_FLAG       VARCHAR2(2 CHAR),
    ATTRIBUTABLE_PARTY  VARCHAR2(32 CHAR),
    RECEIVING_PARTY     VARCHAR2(32 CHAR),

    PAYMENT_VENDOR       VARCHAR2(16 CHAR),
    CHANNEL_TYPE         VARCHAR2(4 CHAR),
    PAY_USER_ID          VARCHAR2(128 CHAR),
    TRANSFER_FLAG        VARCHAR2(2 CHAR),
    CUMULATIVE_TYPE      VARCHAR2(2 CHAR),
    ORIGINAL_FARE        NUMBER(22),
    WALLET_TOTAL_AMT     NUMBER(22),
    DISCOUNT_LEVEL_AMT   NUMBER(22),
    DISCOUNT_RATE        NUMBER(8,6),
    EXPECTED_GATE_AMOUNT NUMBER(22),
    DISCOUNT_CALC_STATUS VARCHAR2(32 CHAR),
    DISCOUNT_CALC_MSG    VARCHAR2(512 CHAR),

    DEBIT_RETRY_TIMES     NUMBER(2) DEFAULT 0 NOT NULL,
    DEBIT_NEXT_RETRY_TIME TIMESTAMP(6),
    DEBIT_FAIL_CODE       VARCHAR2(32 CHAR),
    DEBIT_FAIL_MSG        VARCHAR2(512 CHAR),

    INDUSTRY_DETAIL     VARCHAR2(4000 CHAR),

    CONSTRAINT PK_GATE_TXN_PAY PRIMARY KEY (ID)
)
PARTITION BY RANGE (TXN_DATE) (
    PARTITION P202606 VALUES LESS THAN ('20260701'),
    PARTITION P202607 VALUES LESS THAN ('20260801'),
    PARTITION P202608 VALUES LESS THAN ('20260901'),
    PARTITION P202609 VALUES LESS THAN ('20261001'),
    PARTITION P202610 VALUES LESS THAN ('20261101'),
    PARTITION P202611 VALUES LESS THAN ('20261201'),
    PARTITION P202612 VALUES LESS THAN ('20270101'),
    PARTITION P_MAX VALUES LESS THAN (MAXVALUE)
);

CREATE SEQUENCE SEQ_GATE_TXN_PAY
    START WITH 1
    INCREMENT BY 1
    CACHE 1000
    NOCYCLE;

-- 地铁侧订单号唯一索引。ORDER_NO 同时作为调用支付接口的 orderNo。
-- Oracle 本地唯一索引必须包含分区键，因此包含 TXN_DATE。
CREATE UNIQUE INDEX UK_GATE_TXN_PAY_ORDER_NO
ON GATE_TXN_PAY (
    ORDER_NO,
    TXN_DATE
)
LOCAL;

-- 过闸交易幂等唯一索引。
-- 同一笔出站/超时出站交易只允许生成一笔扣费订单。
CREATE UNIQUE INDEX UK_GATE_TXN_PAY_BIZ
ON GATE_TXN_PAY (
    CARD_ID,
    TRX_TYPE,
    OUT_TIME,
    TICKET_TRANS_SEQ,
    DEVICE_ID,
    TXN_DATE
)
LOCAL;

-- 按卡号查询过闸扣费订单，查询时应带 TXN_DATE 范围以触发分区裁剪。
CREATE INDEX IDX_GATE_TXN_PAY_CARD_DATE
ON GATE_TXN_PAY (
    CARD_ID,
    TXN_DATE,
    OUT_TIME
)
LOCAL;

-- 按用户查询过闸扣费订单。
CREATE INDEX IDX_GATE_TXN_PAY_USER_DATE
ON GATE_TXN_PAY (
    THIRD_USER_ID,
    TXN_DATE,
    OUT_TIME
)
LOCAL;

-- 按扣费状态查询待补扣、失败、处理中订单。
CREATE INDEX IDX_GATE_TXN_PAY_STATUS_DATE
ON GATE_TXN_PAY (
    DEBIT_STATUS,
    TXN_DATE,
    CREATE_TIME
)
LOCAL;

-- 按设备查询扣费订单或排查设备重复上送、漏传问题。
CREATE INDEX IDX_GATE_TXN_PAY_DEVICE_DATE
ON GATE_TXN_PAY (
    DEVICE_ID,
    TXN_DATE,
    OUT_TIME
)
LOCAL;

COMMENT ON TABLE GATE_TXN_PAY IS '二维码过闸扣费订单表';

COMMENT ON COLUMN GATE_TXN_PAY.ID IS '主键ID';
COMMENT ON COLUMN GATE_TXN_PAY.ORDER_NO IS '地铁侧扣费订单号，同时作为支付接口orderNo';
COMMENT ON COLUMN GATE_TXN_PAY.DEBIT_STATUS IS '扣费状态：INIT初始化，PROCESSING处理中，SUCCESS成功，FAIL失败，RETRY待补扣，CLOSED关闭';
COMMENT ON COLUMN GATE_TXN_PAY.THIRD_USER_ID IS '第三方用户ID，对应设备报文itpUserId转换后的用户标识';
COMMENT ON COLUMN GATE_TXN_PAY.CARD_ID IS '逻辑卡号';
COMMENT ON COLUMN GATE_TXN_PAY.CARD_TYPE IS '票卡类型';
COMMENT ON COLUMN GATE_TXN_PAY.DEVICE_ID IS '设备ID，公共请求参数';
COMMENT ON COLUMN GATE_TXN_PAY.TRX_TYPE IS '交易类型：02出站，03超时出站';
COMMENT ON COLUMN GATE_TXN_PAY.TICKET_TRANS_SEQ IS '二维码交易计数器，文档字段名为tikcetTransSeq';
COMMENT ON COLUMN GATE_TXN_PAY.TXN_DATE IS '出站交易日期，取OUT_TIME前8位，格式YYYYMMDD，用于月分区';
COMMENT ON COLUMN GATE_TXN_PAY.TICKET_STATUS IS '票卡状态：01无交易,02进站,03进站超时,04进站失败,05出站,06出站超时,70异常,80自助补出站（与QRCodeStatusEnum不同源，跨表NEVER互换）';
COMMENT ON COLUMN GATE_TXN_PAY.ENTRY_STATION_NAME IS '进站车站名称';
COMMENT ON COLUMN GATE_TXN_PAY.EXIT_STATION_NAME IS '出站车站名称';
COMMENT ON COLUMN GATE_TXN_PAY.ORDER_EXP_TYPE IS '订单异常类型：0正常,1单边账(入),2单边账(出),3单边入站人工,4单边出站人工,5双段计费超时';
COMMENT ON COLUMN GATE_TXN_PAY.IN_STATION IS '进站车站代码';
COMMENT ON COLUMN GATE_TXN_PAY.IN_TIME IS '进站时间，格式YYYYMMDDHH24MISS';
COMMENT ON COLUMN GATE_TXN_PAY.OUT_STATION IS '出站车站代码';
COMMENT ON COLUMN GATE_TXN_PAY.OUT_TIME IS '出站时间，格式YYYYMMDDHH24MISS';
COMMENT ON COLUMN GATE_TXN_PAY.TRX_AMOUNT IS '闸机交易金额，单位分';
COMMENT ON COLUMN GATE_TXN_PAY.OVERTIME_AMOUNT IS '超时金额，单位分';
COMMENT ON COLUMN GATE_TXN_PAY.TOTAL_AMOUNT IS '应扣总金额，单位分';
COMMENT ON COLUMN GATE_TXN_PAY.ISSUE_CHANNEL_CODE IS '发行渠道代码';
COMMENT ON COLUMN GATE_TXN_PAY.SIGN_CHANNEL_CODE IS '签约通道代码';
COMMENT ON COLUMN GATE_TXN_PAY.COMPANION_FLAG IS '同行票标识：Y/N';
COMMENT ON COLUMN GATE_TXN_PAY.OFFLINE_FLAG IS '离线码标识：Y/N';
COMMENT ON COLUMN GATE_TXN_PAY.TICKET_CODE IS '日票票号';
COMMENT ON COLUMN GATE_TXN_PAY.COUNTING_TIMES IS '计次票剩余可用次数';
COMMENT ON COLUMN GATE_TXN_PAY.COUNTING_FLAG IS '计次/计时标识：1=计时,2=计次';
COMMENT ON COLUMN GATE_TXN_PAY.ATTRIBUTABLE_PARTY IS '订单应收商户';
COMMENT ON COLUMN GATE_TXN_PAY.RECEIVING_PARTY IS '订单实收商户';
COMMENT ON COLUMN GATE_TXN_PAY.PAYMENT_VENDOR IS '支付厂商编码，钱包为0B';
COMMENT ON COLUMN GATE_TXN_PAY.CHANNEL_TYPE IS '交易渠道类型，01为蓝牙';
COMMENT ON COLUMN GATE_TXN_PAY.PAY_USER_ID IS '钱包支付用户标识';
COMMENT ON COLUMN GATE_TXN_PAY.TRANSFER_FLAG IS '钱包换乘标识：01无换乘，02有换乘';
COMMENT ON COLUMN GATE_TXN_PAY.CUMULATIVE_TYPE IS '钱包累计类型：01正常出站，02超时出站，03不累计';
COMMENT ON COLUMN GATE_TXN_PAY.ORIGINAL_FARE IS '地铁进出站原价，单位分';
COMMENT ON COLUMN GATE_TXN_PAY.WALLET_TOTAL_AMT IS '钱包查询到的累计金额，单位分';
COMMENT ON COLUMN GATE_TXN_PAY.DISCOUNT_LEVEL_AMT IS '命中的折扣金额门槛，单位分';
COMMENT ON COLUMN GATE_TXN_PAY.DISCOUNT_RATE IS '命中的折扣率';
COMMENT ON COLUMN GATE_TXN_PAY.EXPECTED_GATE_AMOUNT IS '公式计算的期望闸机金额，单位分';
COMMENT ON COLUMN GATE_TXN_PAY.DISCOUNT_CALC_STATUS IS 'SUCCESS/FALLBACK/SKIPPED/OFFLINE_FARE_PENDING';
COMMENT ON COLUMN GATE_TXN_PAY.DISCOUNT_CALC_MSG IS '优惠计算说明或降级原因';
COMMENT ON COLUMN GATE_TXN_PAY.REMARK IS '备注';
COMMENT ON COLUMN GATE_TXN_PAY.INDUSTRY_DETAIL IS '支付宝出行行业明细JSON，21键，出站落单时由fep-dev-server组装后整块透传，仅ISSUE_CHANNEL_CODE=07有值';
COMMENT ON COLUMN GATE_TXN_PAY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN GATE_TXN_PAY.UPDATE_TIME IS '更新时间';

-- 后续月分区维护示例：
--
-- 1. 新增 2027 年 1 月分区。
--    P202701 覆盖范围：20270101 <= TXN_DATE < 20270201
--
-- ALTER TABLE GATE_TXN_PAY
-- SPLIT PARTITION P_MAX
-- AT ('20270201')
-- INTO (
--     PARTITION P202701,
--     PARTITION P_MAX
-- );
--
-- 2. 新增 2027 年 2 月分区。
--    P202702 覆盖范围：20270201 <= TXN_DATE < 20270301
--
-- ALTER TABLE GATE_TXN_PAY
-- SPLIT PARTITION P_MAX
-- AT ('20270301')
-- INTO (
--     PARTITION P202702,
--     PARTITION P_MAX
-- );
--
-- 3. 查询分区情况。
--
-- SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE
-- FROM USER_TAB_PARTITIONS
-- WHERE TABLE_NAME = 'GATE_TXN_PAY'
-- ORDER BY PARTITION_POSITION;
--
-- 4. 删除历史月份分区示例：删除 2026 年 6 月过闸扣费订单。
--    执行前务必确认历史数据已归档或无需保留。
--
-- ALTER TABLE GATE_TXN_PAY DROP PARTITION P202606 UPDATE INDEXES;
--
-- 5. 推荐查询写法：按卡号查询时同时带 TXN_DATE 范围，确保命中分区裁剪。
--
-- SELECT *
-- FROM GATE_TXN_PAY
-- WHERE CARD_ID = :cardId
--   AND TXN_DATE >= :beginDate
--   AND TXN_DATE <  :endDate
-- ORDER BY OUT_TIME DESC;
--
-- 6. 待补扣查询示例。
--
-- SELECT *
-- FROM GATE_TXN_PAY
-- WHERE DEBIT_STATUS IN ('FAIL', 'RETRY')
--   AND TXN_DATE >= :beginDate
--   AND TXN_DATE <  :endDate
-- ORDER BY CREATE_TIME;
