-- 用户主动重试扣费队列表（ADR-D169 方案 A 改造）
-- 用于解耦 APP 请求与支付中心调用，避免瞬时 TPS 冲击正常扣费流程
--
-- 设计要点：
-- 1. 不分区：队列表数据量小（单用户最多几百笔），分区无收益
-- 2. 状态机：PENDING → PROCESSING → DONE/FAILED
-- 3. 幂等：ORDER_NO + TXN_DATE 唯一，防重复消费
-- 4. 超时：PENDING 超过 24 小时自动标记 FAILED，人工介入

CREATE TABLE GATE_RETRY_QUEUE (
    ID              NUMBER(20) NOT NULL,
    ORDER_NO        VARCHAR2(64 CHAR) NOT NULL,
    TXN_DATE        VARCHAR2(8 CHAR) NOT NULL,
    THIRD_USER_ID   VARCHAR2(64 CHAR) NOT NULL,
    CARD_ID         VARCHAR2(32 CHAR) NOT NULL,
    STATUS          VARCHAR2(16 CHAR) DEFAULT 'PENDING' NOT NULL,
    RETRY_COUNT     NUMBER(4) DEFAULT 0 NOT NULL,
    MAX_RETRIES     NUMBER(4) DEFAULT 3 NOT NULL,
    ERROR_MSG       VARCHAR2(512 CHAR),
    CREATE_TIME     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSUME_TIME    TIMESTAMP(6),
    FINISH_TIME     TIMESTAMP(6),

    CONSTRAINT PK_GATE_RETRY_QUEUE PRIMARY KEY (ID)
);

-- 唯一索引：同一订单只允许入队一次
CREATE UNIQUE INDEX UK_GATE_RETRY_QUEUE_ORDER
ON GATE_RETRY_QUEUE (ORDER_NO, TXN_DATE);

-- 消费索引：按状态 + 创建时间排序，优先处理旧单
CREATE INDEX IDX_GATE_RETRY_QUEUE_CONSUME
ON GATE_RETRY_QUEUE (STATUS, CREATE_TIME)
WHERE STATUS IN ('PENDING', 'FAILED');

COMMENT ON TABLE GATE_RETRY_QUEUE IS '用户主动重试扣费队列表（ADR-D169）';
COMMENT ON COLUMN GATE_RETRY_QUEUE.ID IS '主键';
COMMENT ON COLUMN GATE_RETRY_QUEUE.ORDER_NO IS '过闸订单号';
COMMENT ON COLUMN GATE_RETRY_QUEUE.TXX_DATE IS '交易日期（8位）';
COMMENT ON COLUMN GATE_RETRY_QUEUE.THIRD_USER_ID IS '第三方用户ID';
COMMENT ON COLUMN GATE_RETRY_QUEUE.CARD_ID IS '逻辑卡号';
COMMENT ON COLUMN GATE_RETRY_QUEUE.STATUS IS '队列状态：PENDING=待消费, PROCESSING=消费中, DONE=已完成, FAILED=失败';
COMMENT ON COLUMN GATE_RETRY_QUEUE.RETRY_COUNT IS '已重试次数';
COMMENT ON COLUMN GATE_RETRY_QUEUE.MAX_RETRIES IS '最大重试次数（默认 3）';
COMMENT ON COLUMN GATE_RETRY_QUEUE.ERROR_MSG IS '失败原因';
COMMENT ON COLUMN GATE_RETRY_QUEUE.CREATE_TIME IS '入队时间';
COMMENT ON COLUMN GATE_RETRY_QUEUE.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN GATE_RETRY_QUEUE.CONSUME_TIME IS '开始消费时间';
COMMENT ON COLUMN GATE_RETRY_QUEUE.FINISH_TIME IS '完成时间';

-- 序列
CREATE SEQUENCE SEQ_GATE_RETRY_QUEUE
    START WITH 1
    INCREMENT BY 1
    CACHE 100
    NOCYCLE;
