ALTER TABLE GATE_TXN_PAY ADD (ADVICE_OPT VARCHAR2(8 CHAR));

COMMENT ON COLUMN GATE_TXN_PAY.ADVICE_OPT IS 'BOM补站操作类型：空=真实闸机检票或APP自助补站,005=免费更新,006=付费更新,018=补进站,020=免费更新(无时间窗)；非空即BOM补站单，现场已收款，NEVER由ITP发起扣款';
