CREATE TABLE SUPPLEMENT_ORDER (
    ID                NUMBER(19)     NOT NULL,
    ORDER_NO          VARCHAR2(128)  NOT NULL,
    PAY_STATUS        VARCHAR2(32)   NOT NULL,
    THIRD_USER_ID     VARCHAR2(128),
    CARD_ID           VARCHAR2(64),
    CARD_TYPE         VARCHAR2(16),
    GOODS_CODE        VARCHAR2(64),
    QUANTITY          NUMBER(10),
    TOTAL_AMOUNT      NUMBER(18),
    ORDER_COUNT       NUMBER(10),
    PAYMENT_VENDOR    VARCHAR2(32),
    SIGN_CHANNEL_CODE VARCHAR2(16),
    REQUEST_SIGN_SEQ  VARCHAR2(64),
    TXN_DATE          VARCHAR2(16)   NOT NULL,
    PAY_TIME          TIMESTAMP(6),
    REMARK            VARCHAR2(1024),
    CREATE_TIME       TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME       TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SUPPLEMENT_ORDER PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_SUPPLEMENT_ORDER_NO ON SUPPLEMENT_ORDER (ORDER_NO);

CREATE INDEX IDX_SUPPLEMENT_ORDER_USER ON SUPPLEMENT_ORDER (THIRD_USER_ID, TXN_DATE);

CREATE SEQUENCE SEQ_SUPPLEMENT_ORDER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE SUPPLEMENT_ORDER_ITEM (
    ID            NUMBER(19)     NOT NULL,
    ORDER_NO      VARCHAR2(128)  NOT NULL,
    ORIG_ORDER_NO VARCHAR2(128)  NOT NULL,
    ORIG_TXN_DATE VARCHAR2(16),
    ORIG_AMOUNT   NUMBER(18),
    SETTLE_STATUS VARCHAR2(32),
    REMARK        VARCHAR2(1024),
    ACTIVE_ORIG_ORDER_NO VARCHAR2(128),
    CREATE_TIME   TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME   TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SUPPLEMENT_ORDER_ITEM PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_SUPPLEMENT_ITEM_ORDER ON SUPPLEMENT_ORDER_ITEM (ORDER_NO, ORIG_ORDER_NO);

CREATE INDEX IDX_SUPPLEMENT_ITEM_ORIG ON SUPPLEMENT_ORDER_ITEM (ORIG_ORDER_NO);

CREATE SEQUENCE SEQ_SUPPLEMENT_ORDER_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE SUPPLEMENT_ORDER ADD (
    PAY_CHANNEL_CODE  VARCHAR2(16),
    MERCHANT_ORDER_NO VARCHAR2(128),
    PAYMENT_INFO      VARCHAR2(2000)
);

CREATE INDEX IDX_SUPPLEMENT_ORDER_STATUS ON SUPPLEMENT_ORDER (PAY_STATUS, CREATE_TIME);

CREATE INDEX IDX_SUPPLEMENT_ORDER_UPDT ON SUPPLEMENT_ORDER (PAY_STATUS, UPDATE_TIME);

CREATE UNIQUE INDEX UK_SUPPLEMENT_ITEM_ACTIVE ON SUPPLEMENT_ORDER_ITEM (ACTIVE_ORIG_ORDER_NO);

ALTER TABLE SUPPLEMENT_ORDER ADD (
    SALE_SYNC_STATUS      VARCHAR2(32 CHAR),
    SALE_SYNC_RETRY_COUNT NUMBER DEFAULT 0,
    SALE_SYNC_TIME        TIMESTAMP(6),
    SALE_SYNC_RESULT      VARCHAR2(1024 CHAR)
);

CREATE INDEX IDX_SUPPLEMENT_ORDER_SALESYNC ON SUPPLEMENT_ORDER (SALE_SYNC_STATUS, CREATE_TIME);
