<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.chinasofti.huateng</groupId>
        <artifactId>web-server</artifactId>
        <version>${project.version}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>
    <artifactId>web-admin</artifactId>

    <description>
        web服务入口
    </description>
    <properties>
        <image.prefix>web-admin</image.prefix>
        <docker.namespace>itp</docker.namespace>
        <rpc.version>2.0.1</rpc.version>
        <micro.web.version>2.0</micro.web.version>
    </properties>


    <dependencies>

        <!-- spring-boot-devtools -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional> <!-- 表示依赖不会传递 -->
        </dependency>

        <!-- OpenAPI/Swagger UI -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>

        <!-- Oracle JDBC驱动包 -->
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
        </dependency>

        <!-- Oracle NLS字符集支持（数据库字符集：ZHS16GBK） -->
        <dependency>
            <groupId>com.oracle.database.nls</groupId>
            <artifactId>orai18n</artifactId>
        </dependency>
        <!-- 达梦驱动包 -->
<!--        <dependency>-->
<!--            <groupId>com.dameng</groupId>-->
<!--            <artifactId>DmJdbcDriver18</artifactId>-->
<!--        </dependency>-->

        <!-- 核心模块-->
        <dependency>
            <groupId>com.chinasofti.huateng</groupId>
            <artifactId>web-framework</artifactId>
        </dependency>

        <!-- 定时任务-->
        <dependency>
            <groupId>com.chinasofti.huateng</groupId>
            <artifactId>web-quartz</artifactId>
        </dependency>

        <!-- 代码生成-->
        <dependency>
            <groupId>com.chinasofti.huateng</groupId>
            <artifactId>web-generator</artifactId>
        </dependency>

        <!-- RPC 客户端及其 ProxyWebClient 运行时依赖 -->
        <dependency>
            <groupId>com.chinasofti.huateng</groupId>
            <artifactId>rpc</artifactId>
            <version>${rpc.version}</version>
        </dependency>
        <dependency>
            <groupId>com.chinasofti.huateng.micro</groupId>
            <artifactId>web</artifactId>
            <version>${micro.web.version}</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
<!--                <configuration>-->
<!--                    <fork>true</fork> &lt;!&ndash; 如果没有该配置，devtools不会生效 &ndash;&gt;-->
<!--                </configuration>-->
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
<!--            <plugin>   -->
<!--                <groupId>org.apache.maven.plugins</groupId>   -->
<!--                <artifactId>maven-war-plugin</artifactId>   -->
<!--                <version>3.1.0</version>   -->
<!--                <configuration>-->
<!--                    <failOnMissingWebXml>false</failOnMissingWebXml>-->
<!--                    <warName>${project.artifactId}</warName>-->
<!--                </configuration>   -->
<!--           </plugin>   -->
        </plugins>
        <finalName>${project.artifactId}</finalName>
    </build>
    <profiles>
        <profile>
            <id>remote</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.eclipse.jkube</groupId>
                        <artifactId>kubernetes-maven-plugin</artifactId>
                        <version>1.19.0</version>
                        <executions>
                            <execution>
                                <id>build-image-remote</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>build</goal>
                                    <goal>push</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <namespace>itp</namespace>
                            <dockerHost>tcp://172.20.211.21:2375</dockerHost>
                            <pushRegistry>os-harbor-svc.default.svc.cloudos:443</pushRegistry>
                            <images>
                                <image>
                                    <name>os-harbor-svc.default.svc.cloudos:443/${docker.namespace}/${image.prefix}:${project.version}</name>
                                    <build>
                                        <dockerFile>${project.basedir}/../../docker/Dockerfile</dockerFile>
                                        <filter>true</filter>
                                        <contextDir>${project.basedir}</contextDir>
                                        <assembly>
                                            <mode>dir</mode>
                                            <targetDir>/</targetDir>
                                            <inline>
                                                <files>
                                                    <file>
                                                        <source>${project.build.directory}/${project.build.finalName}.jar</source>
                                                        <destName>app.jar</destName>
                                                        <outputDirectory>.</outputDirectory>
                                                    </file>
                                                </files>
                                            </inline>
                                        </assembly>
                                    </build>
                                </image>
                            </images>
                            <generator>
                                <excludes>
                                    <exclude>spring-boot</exclude>
                                </excludes>
                            </generator>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>local</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.eclipse.jkube</groupId>
                        <artifactId>kubernetes-maven-plugin</artifactId>
                        <version>1.19.0</version>
                        <executions>
                            <execution>
                                <id>build-image-local</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>resource</goal>
                                    <goal>build</goal>
                                    <goal>apply</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <images>
                                <image>
                                    <name>huateng/${image.prefix}:${project.version}</name>
                                    <build>
                                        <dockerFile>${project.basedir}/../docker/Dockerfile.local</dockerFile>
                                        <filter>true</filter>
                                        <contextDir>${project.basedir}</contextDir>
                                        <assembly>
                                            <mode>dir</mode>
                                            <targetDir>/</targetDir>
                                            <inline>
                                                <files>
                                                    <file>
                                                        <source>${project.build.directory}/${project.build.finalName}.jar</source>
                                                        <destName>app.jar</destName>
                                                        <outputDirectory>.</outputDirectory>
                                                    </file>
                                                </files>
                                            </inline>
                                        </assembly>
                                    </build>
                                </image>
                            </images>
                            <generator>
                                <excludes>
                                    <exclude>spring-boot</exclude>
                                </excludes>
                            </generator>
                            <resources>
                                <services>
                                    <service>
                                        <name>account-server</name>
                                        <type>NodePort</type>
                                        <ports>
                                            <port>
                                                <port>9103</port>
                                                <targetPort>9103</targetPort>
                                                <nodePort>30085</nodePort>
                                            </port>
                                        </ports>
                                    </service>
                                </services>
                            </resources>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
