-- 支付宝出行付款链路：ALIPAY_PAY_CALLBACK_LOG 承接对端回传字段（2026-09-18）
--
-- 背景：这批字段原先落在 ALIPAY_PAY_TXN_DETAIL（明细表）上，与「我方请求参数」混在一列表里。
-- 本次按「明细表只留我方送出的请求事实、回调表留对端回传事实」重划边界，把 10 个字段迁到本表。
-- 明细表侧的删列由 alipay-pay-txn-detail-rebuild-migration.sql 承担，两个脚本 MUST 一起执行。
--
-- 三对「同义不同源」的列在本表并存，NEVER 合并成一列：
--   TRANS_AMOUNT / TOTAL_AMOUNT           支付宝报文原文 / 支付中心口径
--   TRANS_TIME / PAY_TIME                 同上
--   CHANNEL_VOUCHER_ID / CHANNEL_ORDER_NO 同上
-- 两条入向报文各存一份，合并后无法追溯是谁送来的。

ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD MERCHANT_ORDER_NO VARCHAR2(64 CHAR);
ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD CHANNEL_ORDER_NO VARCHAR2(64 CHAR);
ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD PAY_USER_ID VARCHAR2(64 CHAR);
ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD PAY_TIME VARCHAR2(32 CHAR);
ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD TOTAL_AMOUNT NUMBER(22);
ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD CASH_AMOUNT NUMBER(22);
ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD COUPON_AMOUNT NUMBER(22);
ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD DISCOUNT_FEE NUMBER(22);
ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD DISCOUNT_INFO VARCHAR2(512 CHAR);
ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD TXN_DATE VARCHAR2(8 CHAR);

-- RAW_BODY 由 VARCHAR2(4000) 改为 CLOB，与 mapper 的 jdbcType=CLOB 对齐。
-- Oracle 不允许 VARCHAR2 直接 MODIFY 成 CLOB（ORA-22858，与数据量无关），
-- 本表 2026-09-18 实测 0 行、RAW_BODY 全为 NULL，因此可以直接 DROP + ADD、无需搬数据。
-- 表内已有数据时 NEVER 照抄这两行，MUST 走「加临时列 -> UPDATE 搬数据 -> DROP 旧列 -> RENAME」。
ALTER TABLE ALIPAY_PAY_CALLBACK_LOG DROP COLUMN RAW_BODY;
ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD RAW_BODY CLOB;

COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.MERCHANT_ORDER_NO IS '对端回显的商户订单号，与 ORDER_NO 同源；只用于发现对端串单，NEVER 拿它做关联';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.CHANNEL_ORDER_NO IS '支付中心口径的渠道订单号（支付宝交易号）；与 CHANNEL_VOUCHER_ID 不是同一个号';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.PAY_USER_ID IS '支付渠道账户或买家账户，回调回传值';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.PAY_TIME IS '支付完成时间 YYYYMMDDHH24MISS，原文直存不解析；与 TRANS_TIME 不同源';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.TOTAL_AMOUNT IS '支付中心回传的订单总金额（分）；与 TRANS_AMOUNT 不同源，后者是支付宝报文原文字符串';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.CASH_AMOUNT IS '支付中心回传的实付金额（分）；已实测恒等于总金额，NEVER 拿它算优惠';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.COUPON_AMOUNT IS '支付中心回传的优惠金额（分）；已实测恒等于总金额，NEVER 拿它算优惠';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.DISCOUNT_FEE IS '支付中心回传的优惠金额（分），与 COUPON_AMOUNT 分列存放，同样仅供核对';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.DISCOUNT_INFO IS '渠道优惠详情原文 JSON 数组；存原文不解析，NEVER 与明细表里我方自算的优惠混用';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.TXN_DATE IS '订单日期 yyyyMMdd，取自主表；供按账期检索，本表当前未分区';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.RAW_BODY IS '整包报文原文，CLOB；接线时不必再截断';

-- 第二批（同日追加）：退款结果回调也落本表，需要三个退款专属列。
-- 本表靠 CALLBACK_TYPE 区分方向：'PAY' 支付回调、'REFUND' 退款回调，
-- 下面三列只在 CALLBACK_TYPE='REFUND' 时有值，NEVER 拿它们判断支付回调。

ALTER TABLE ALIPAY_PAY_CALLBACK_LOG ADD (
    REFUND_ORDER_NO VARCHAR2(64 CHAR),
    REFUND_AMOUNT   NUMBER(22),
    REFUND_STATUS   VARCHAR2(16 CHAR)
);

COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.REFUND_ORDER_NO IS '退款单号，与 ALIPAY_REFUND_LOG.REFUND_ORDER_NO 同源；CALLBACK_TYPE=REFUND 时有值';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.REFUND_AMOUNT IS '退款金额（分），支付中心回调回传值';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.REFUND_STATUS IS '退款状态，支付中心回调回传值；当前只落证据不回写业务';
