-- 支付宝出行渠道 支付交易明细 / 退款明细
--
-- 形态对齐 pay-sign-server 的 pay-txn-schema.sql（PAY_TXN_DETAIL / PAY_REFUND_DETAIL）：
--   金额一律 NUMBER 且单位为分，时间一律 TIMESTAMP，TXN_DATE 为 yyyyMMdd 字符串并作月分区键，
--   主键取序列，业务唯一键是 (ORDER_NO, TXN_DATE) 的 LOCAL 唯一索引。
--
-- 为什么另起两张表、而不是继续用 ALIPAY_PAY_LOG / ALIPAY_REFUND_LOG：
--   1) 旧两表 31 / 20 列**全部是 VARCHAR2**，PAY_AMOUNT / REFUND_AMOUNT / TRANS_TIME 都是字符串，
--      查询侧只能 TO_NUMBER / TO_DATE(TRANS_TIME,...)，既走不到索引，又因存量 TRANS_TIME 格式
--      不统一（既有 '2026-07-28 16:59:55' 也有毫秒时间戳 '1785229085685'）而无法安全比较。
--   2) ALIPAY_PAY_LOG 没有 CREATE_TIME / UPDATE_TIME 列，排序只能落到 UUID 主键 PAY_SEQ，等于随机序。
--   3) 旧表没有任何唯一索引，「唯一索引 + DuplicateKeyException 兜底」这条项目主幂等写法无处落地。
--   4) 旧表没有 REQUEST_COUNT / NEXT_REQUEST_TIME，扫表补偿无列可依。
--
-- 本脚本只服务「新建这两张表」。**它不是迁移脚本**：存量 ALIPAY_PAY_LOG / ALIPAY_REFUND_LOG
-- 的处置（迁移 / 双读 / 冻结）尚未裁决，选定后 MUST 另出 *-migration.sql。
--
-- 分区列表从 P202606 起、共 8 个分区，与 AFCITPDB 里 PAY_TXN_DETAIL / PAY_REFUND_DETAIL
-- 实测的分区布局逐个对齐（2026-09-15 查 USER_TAB_PARTITIONS：两表都是 P202606~P202612 + P_MAX）。
-- NEVER 把最早分区改成 P202609：存量 ALIPAY_PAY_LOG 33 行的 TRANS_TIME 最大值是 2026-07-28，
-- 若后续裁决为「迁移存量」，那些 TXN_DATE=202607 的行会全部挤进 P202609 这个九月分区，
-- 分区裁剪与将来按月归档都会失准，而且建表时看不出任何异常。
--
-- 执行状态：**本脚本已于 2026-09-16 在 AFCITPDB 全量执行并回查通过**（2 张表 × 8 分区
-- P202606~P202612 + P_MAX、2 个序列、10 个 LOCAL 索引 PARTITIONED=YES、41 条列注释）。
-- 重复执行会报对象已存在，MUST 先确认差异再补单条，NEVER 整段重跑。
--
-- 执行方式：现在可以经 mcp_database_qd 执行。原先「MCP 跑不了分区表」的限制已于
-- 2026-09-16 消除 —— 那是 MCP 服务端 SQL 校验器的两个缺陷，已在 database-mcp-server
-- 侧修好并部署（镜像 itp/database-server:1.0.7 -> 1.0.8，Deployment `database` / ns `itp`）：
--   1) jsqlparser 5.3 -> 5.4，PARTITION BY RANGE 从此能解析（5.3 报
--      「Encountered unexpected token: "RANGE"」）；
--   2) 新增 SqlTailNormalizer 兜底钩子，仅在 jsqlparser 解析失败后触发，只摘除
--      CREATE INDEX 末尾的 LOCAL / GLOBAL 关键字尾巴（纯关键字、必须是严格前缀，
--      带堆叠语句 / 注释 / 标点的尾巴一律拒绝），成功路径零变化。
-- 注意 executeDdl / validateDdl 的入参名不同：executeDdl 用 `sql`（单条），
-- validateDdl 与 executeDdlBatch 用 `statements`（数组）。
-- AGENTS.md §8 记的 BEGIN EXECUTE IMMEDIATE 绕法在这里依然不行（返
-- 「DDL statement not allowed: Block」），不需要它了。
-- NEVER 为了让 MCP 能跑就去掉分区或 LOCAL —— 参照表在同一个库里就是分区的。
--
-- 状态词表与 pay-sign-server 保持逐字一致，NEVER 换成 ALIPAY_* 旧表那套：
--   PAY_STATUS    INIT / PROCESSING / SUCCESS / FAIL / RETRY / CLOSED
--   REFUND_STATUS NONE / PROCESSING / PARTIAL / SUCCESS / FAIL（主表）
--                 INIT / PROCESSING / SUCCESS / FAIL / RETRY / CLOSED（明细表）

CREATE TABLE ALIPAY_PAY_TXN_DETAIL (
    ID                   NUMBER(22) NOT NULL,

    ORDER_NO             VARCHAR2(128 CHAR) NOT NULL,
    PAY_TYPE             VARCHAR2(32 CHAR) DEFAULT 'PAY' NOT NULL,
    PAY_STATUS           VARCHAR2(32 CHAR) DEFAULT 'INIT' NOT NULL,

    THIRD_USER_ID        VARCHAR2(128 CHAR),
    CARD_ID              VARCHAR2(64 CHAR),
    CARD_TYPE            VARCHAR2(64 CHAR),

    PAYMENT_VENDOR       VARCHAR2(32 CHAR),
    PAY_CHANNEL_CODE     VARCHAR2(32 CHAR),
    REQUEST_SIGN_SEQ     VARCHAR2(256 CHAR),
    CHANNEL_AGREEMENT_NO VARCHAR2(256 CHAR),

    AMOUNT               NUMBER(22) DEFAULT 0 NOT NULL,
    TOTAL_AMOUNT         NUMBER(22),
    CASH_AMOUNT          NUMBER(22),
    COUPON_AMOUNT        NUMBER(22),

    REFUND_STATUS        VARCHAR2(32 CHAR) DEFAULT 'NONE' NOT NULL,
    REFUND_AMOUNT        NUMBER(22) DEFAULT 0 NOT NULL,
    LAST_REFUND_TIME     TIMESTAMP(6),

    MERCHANT_ORDER_NO    VARCHAR2(128 CHAR),
    PAY_CENTER_ORDER_NO  VARCHAR2(128 CHAR),
    CHANNEL_ORDER_NO     VARCHAR2(256 CHAR),
    PAY_USER_ID          VARCHAR2(256 CHAR),

    REQUEST_COUNT        NUMBER(22) DEFAULT 0 NOT NULL,
    NEXT_REQUEST_TIME    TIMESTAMP(6),
    LAST_REQUEST_TIME    TIMESTAMP(6),
    FIRST_REQUEST_TIME   TIMESTAMP(6),
    RESPONSE_TIME        TIMESTAMP(6),
    PAY_TIME             VARCHAR2(28 CHAR),
    TXN_DATE             VARCHAR2(8 CHAR) NOT NULL,

    SCENE                VARCHAR2(32 CHAR),
    INDUSTRY_TYPE        VARCHAR2(32 CHAR),
    SUBJECT              VARCHAR2(256 CHAR),
    BODY                 VARCHAR2(512 CHAR),
    AUTH_CODE            VARCHAR2(128 CHAR),
    NOTIFY_URL           VARCHAR2(512 CHAR),
    RETURN_URL           VARCHAR2(512 CHAR),
    IP_ADDRESS           VARCHAR2(64 CHAR),
    ORDER_TIME_OUT       NUMBER(22),
    INDUSTRY_DETAIL      CLOB,

    ENTRY_ID             VARCHAR2(128 CHAR),
    EXIT_ID              VARCHAR2(128 CHAR),
    INVOICE              VARCHAR2(32 CHAR),

    DISCOUNT_INFO        VARCHAR2(512 CHAR),
    DEBIT_REQUEST_RESULT VARCHAR2(16 CHAR),
    DISCOUNT_FEE         NUMBER(22),

    RESULT_CODE          VARCHAR2(32 CHAR),
    RESULT_MSG           VARCHAR2(512 CHAR),
    REMARK               VARCHAR2(512 CHAR),
    REQUEST_BODY         CLOB,
    RESPONSE_BODY        CLOB,

    CREATE_TIME          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ALIPAY_PAY_TXN_DETAIL PRIMARY KEY (ID)
)
PARTITION BY RANGE (TXN_DATE) (
    PARTITION P202606 VALUES LESS THAN ('20260701'),
    PARTITION P202607 VALUES LESS THAN ('20260801'),
    PARTITION P202608 VALUES LESS THAN ('20260901'),
    PARTITION P202609 VALUES LESS THAN ('20261001'),
    PARTITION P202610 VALUES LESS THAN ('20261101'),
    PARTITION P202611 VALUES LESS THAN ('20261201'),
    PARTITION P202612 VALUES LESS THAN ('20270101'),
    PARTITION P_MAX   VALUES LESS THAN (MAXVALUE)
);

CREATE SEQUENCE SEQ_ALIPAY_PAY_TXN_DETAIL
    START WITH 1
    INCREMENT BY 1
    CACHE 1000
    NOCYCLE;

-- 业务唯一键。这是本表的幂等地基：并发 requestPay 时两条请求可能都看不到已存在的行，
-- 第二条 INSERT 撞这条索引即可被 catch 成「重推」而不是错误（写法照 card-pool-server 的
-- isIntegrityViolation 沿 getCause 链判定，NEVER 只 catch 最外层 DuplicateKeyException）。
CREATE UNIQUE INDEX UK_APTD_ORDER
ON ALIPAY_PAY_TXN_DETAIL (ORDER_NO, TXN_DATE) LOCAL;

CREATE INDEX IDX_APTD_STATUS
ON ALIPAY_PAY_TXN_DETAIL (PAY_STATUS, TXN_DATE, NEXT_REQUEST_TIME) LOCAL;

-- 欠费盘点 countUnsettledByCardId 的支撑索引。旧表这条查询是全表扫。
CREATE INDEX IDX_APTD_CARD_STATUS
ON ALIPAY_PAY_TXN_DETAIL (CARD_ID, PAY_STATUS) LOCAL;

CREATE INDEX IDX_APTD_USER_DATE
ON ALIPAY_PAY_TXN_DETAIL (THIRD_USER_ID, TXN_DATE) LOCAL;

CREATE INDEX IDX_APTD_CHANNEL_ORDER
ON ALIPAY_PAY_TXN_DETAIL (CHANNEL_ORDER_NO, TXN_DATE) LOCAL;

-- 进出站关联查询（payLog/entryId、payLog/exitId、findTravelDetail）。
-- 这两列在旧表上无索引，FETCH FIRST 1 ROWS ONLY 靠全表扫。
CREATE INDEX IDX_APTD_ENTRY_ID
ON ALIPAY_PAY_TXN_DETAIL (ENTRY_ID) LOCAL;

CREATE INDEX IDX_APTD_EXIT_ID
ON ALIPAY_PAY_TXN_DETAIL (EXIT_ID) LOCAL;

COMMENT ON TABLE  ALIPAY_PAY_TXN_DETAIL IS '支付宝出行渠道支付交易明细表';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.ORDER_NO IS '地铁侧订单号，同时作为支付中心接口的 orderNo';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_TYPE IS '交易类型：PAY支付，REFUND退款';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_STATUS IS '支付状态：INIT初始化，PROCESSING处理中，SUCCESS成功，FAIL失败，RETRY待重试，CLOSED关闭';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.THIRD_USER_ID IS '支付宝侧用户标识';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CARD_ID IS '逻辑卡号';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CARD_TYPE IS '票卡类型';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAYMENT_VENDOR IS '支付方式';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_CHANNEL_CODE IS '支付通道编码';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.REQUEST_SIGN_SEQ IS '我方签约流水号，取 ALIPAY_SIGN_INFO.AGREEMENT_CODE';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CHANNEL_AGREEMENT_NO IS '渠道协议号，取 ALIPAY_SIGN_INFO.CHANNEL_AGREEMENT_CODE；与上一列不是同一个号，销卡通知只认这个';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.AMOUNT IS '请求支付金额，单位分';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.TOTAL_AMOUNT IS '订单总金额，单位分';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CASH_AMOUNT IS '实付金额，单位分';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.COUPON_AMOUNT IS '优惠金额，单位分';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.REFUND_STATUS IS '退款状态：NONE未退款，PROCESSING退款中，PARTIAL部分退款，SUCCESS已全额退款，FAIL退款失败';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.REFUND_AMOUNT IS '已退款总金额（单位分），由 ALIPAY_REFUND_TXN_DETAIL 重算得出，NEVER 累加写入';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.MERCHANT_ORDER_NO IS '商户订单号';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_CENTER_ORDER_NO IS '支付中心支付订单号；退款报文的「原支付订单号」取此列，缺它退款必失败';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CHANNEL_ORDER_NO IS '渠道订单号，即支付宝交易号（旧表 TRADE_NO）';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_USER_ID IS '支付渠道账户或买家账户';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.REQUEST_COUNT IS '已发起支付请求次数';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.NEXT_REQUEST_TIME IS '下次允许重试支付时间';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_TIME IS '支付完成时间，格式YYYYMMDDHH24MISS，回调原文直存';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.TXN_DATE IS '订单日期，格式YYYYMMDD，用于月分区与唯一键';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.ORDER_TIME_OUT IS '订单超时时间，单位秒（旧表是字符串）';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.INDUSTRY_DETAIL IS '行业详情JSON，由 fep-dev-server 组装、BizDataBuilder 补渠道协议号';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.ENTRY_ID IS '进站交易ID';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.EXIT_ID IS '出站交易ID';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.DEBIT_REQUEST_RESULT IS '扣款结果：PROCESSING/SUCCESS/FAIL；与对外契约字段 debitRequestResult 的 0/1 值域同名不同义，NEVER 混用';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.RESULT_CODE IS '支付中心业务应答码';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.RESULT_MSG IS '支付中心业务应答文案；NEVER 把它当 debitRequestResult 直接对外返回';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.UPDATE_TIME IS '更新时间';

-- 退款明细表。一笔支付订单可有多笔退款，退款结果由 updateRefundSummary
-- 反向重算 ALIPAY_PAY_TXN_DETAIL.REFUND_STATUS / REFUND_AMOUNT。
-- 与旧 ALIPAY_REFUND_LOG 的三处关键差异：
--   1) REFUND_AMOUNT 是 NUMBER（旧表 VARCHAR2，汇总要 TO_NUMBER 再 TO_CHAR 回写）；
--   2) 有 (REFUND_ORDER_NO, TXN_DATE) 唯一索引 —— 旧表的 UK_ARL_REFUND_ORDER_NO 因存量
--      7 行重复（联调造数固定号 REFUND20260715120000001）撞 ORA-01452，至今没建成；
--   3) 有 REQUEST_COUNT / NEXT_REQUEST_TIME，退款回查补偿才有列可依。
-- 本表**不带 DELETE_FLAG**：旧表那套逻辑删除在退款账本上没有语义（退款明细不该被删），
-- 且每条查询都要记得带 DELETE_FLAG='0'，漏一次就把已删行算进汇总。

CREATE TABLE ALIPAY_REFUND_TXN_DETAIL (
    ID                  NUMBER(22) NOT NULL,

    REFUND_ORDER_NO     VARCHAR2(128 CHAR) NOT NULL,
    ORDER_NO            VARCHAR2(128 CHAR) NOT NULL,
    REFUND_STATUS       VARCHAR2(32 CHAR) DEFAULT 'INIT' NOT NULL,

    REFUND_AMOUNT       NUMBER(22) NOT NULL,
    REFUND_REASON       VARCHAR2(1024 CHAR),

    THIRD_USER_ID       VARCHAR2(128 CHAR),
    CARD_ID             VARCHAR2(64 CHAR),
    CARD_ISSUE_CODE     VARCHAR2(32 CHAR),

    MERCHANT_REFUND_NO  VARCHAR2(128 CHAR),
    REFUND_NO           VARCHAR2(128 CHAR),
    CHANNEL_REFUND_NO   VARCHAR2(256 CHAR),

    REQUEST_COUNT       NUMBER(22) DEFAULT 0 NOT NULL,
    NEXT_REQUEST_TIME   TIMESTAMP(6),
    LAST_REQUEST_TIME   TIMESTAMP(6),

    REFUND_TIME         VARCHAR2(28 CHAR),
    TXN_DATE            VARCHAR2(8 CHAR) NOT NULL,

    RET_CODE            VARCHAR2(32 CHAR),
    RET_MSG             VARCHAR2(512 CHAR),
    PAY_CENTER_CODE     VARCHAR2(32 CHAR),
    PAY_CENTER_MSG      VARCHAR2(1024 CHAR),

    OPERATOR            VARCHAR2(64 CHAR),
    IP_ADDRESS          VARCHAR2(64 CHAR),
    REMARK              VARCHAR2(512 CHAR),

    REQUEST_BODY        CLOB,
    RESPONSE_BODY       CLOB,

    CREATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ALIPAY_REFUND_TXN_DETAIL PRIMARY KEY (ID)
)
PARTITION BY RANGE (TXN_DATE) (
    PARTITION P202606 VALUES LESS THAN ('20260701'),
    PARTITION P202607 VALUES LESS THAN ('20260801'),
    PARTITION P202608 VALUES LESS THAN ('20260901'),
    PARTITION P202609 VALUES LESS THAN ('20261001'),
    PARTITION P202610 VALUES LESS THAN ('20261101'),
    PARTITION P202611 VALUES LESS THAN ('20261201'),
    PARTITION P202612 VALUES LESS THAN ('20270101'),
    PARTITION P_MAX   VALUES LESS THAN (MAXVALUE)
);

CREATE SEQUENCE SEQ_ALIPAY_REFUND_TXN_DETAIL
    START WITH 1
    INCREMENT BY 1
    CACHE 1000
    NOCYCLE;

CREATE UNIQUE INDEX UK_ARTD_REFUND_ORDER
ON ALIPAY_REFUND_TXN_DETAIL (REFUND_ORDER_NO, TXN_DATE) LOCAL;

-- updateRefundSummary 的相关子查询按 (ORDER_NO, REFUND_STATUS) 求和，两列都进索引。
CREATE INDEX IDX_ARTD_ORDER_STATUS
ON ALIPAY_REFUND_TXN_DETAIL (ORDER_NO, REFUND_STATUS) LOCAL;

CREATE INDEX IDX_ARTD_STATUS
ON ALIPAY_REFUND_TXN_DETAIL (REFUND_STATUS, TXN_DATE, NEXT_REQUEST_TIME) LOCAL;

COMMENT ON TABLE  ALIPAY_REFUND_TXN_DETAIL IS '支付宝出行渠道退款明细表';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.REFUND_ORDER_NO IS '内部退款单号，由本模块生成';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.ORDER_NO IS '原支付订单号，对应 ALIPAY_PAY_TXN_DETAIL.ORDER_NO';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.REFUND_STATUS IS '退款状态：INIT初始化，PROCESSING处理中，SUCCESS成功，FAIL失败，RETRY待重试，CLOSED关闭；拿不到业务应答时 MUST 保持 PROCESSING，NEVER 置 FAIL';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.REFUND_AMOUNT IS '退款金额，单位分';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.REQUEST_COUNT IS '已发起退款请求次数';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.NEXT_REQUEST_TIME IS '下次允许重试退款时间';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.TXN_DATE IS '退款发起日期，格式YYYYMMDD，用于月分区与唯一键；与原支付单的 TXN_DATE 各自独立，NEVER 复用原单日期';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.PAY_CENTER_CODE IS '支付中心应答码，与我方 RET_CODE 分列存放';

-- 后续月分区维护示例：
--
-- ALTER TABLE ALIPAY_PAY_TXN_DETAIL
-- SPLIT PARTITION P_MAX AT ('20270201')
-- INTO (PARTITION P202701, PARTITION P_MAX);
--
-- ALTER TABLE ALIPAY_REFUND_TXN_DETAIL
-- SPLIT PARTITION P_MAX AT ('20270201')
-- INTO (PARTITION P202701, PARTITION P_MAX);
