-- 支付宝出行付款链路：回调凭据表 ALIPAY_PAY_CALLBACK_LOG + 退款幂等唯一索引（2026-09-14）

CREATE TABLE ALIPAY_PAY_CALLBACK_LOG (
    CALLBACK_SEQ        VARCHAR2(64)  NOT NULL,
    ORDER_NO            VARCHAR2(64),
    CALLBACK_TYPE       VARCHAR2(16),
    TRANS_STATUS        VARCHAR2(8),
    PAY_STATUS          VARCHAR2(16),
    CHANNEL_VOUCHER_ID  VARCHAR2(64),
    TRANS_AMOUNT        VARCHAR2(32),
    TRANS_TIME          VARCHAR2(32),
    CARD_NO             VARCHAR2(64),
    RAW_BODY            VARCHAR2(4000),
    HANDLE_STATUS       VARCHAR2(16),
    HANDLE_MSG          VARCHAR2(500),
    CREATE_TIME         DATE,
    UPDATE_TIME         DATE,
    CONSTRAINT PK_ALIPAY_PAY_CALLBACK_LOG PRIMARY KEY (CALLBACK_SEQ)
);

COMMENT ON TABLE ALIPAY_PAY_CALLBACK_LOG IS '支付宝出行支付结果回调凭据表';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.CALLBACK_SEQ IS '回调流水号，本服务生成的 UUID';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.ORDER_NO IS '我方订单号，与 GATE_TXN_PAY.ORDER_NO 同源';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.CALLBACK_TYPE IS '回调类型，当前只有 PAY';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.TRANS_STATUS IS '报文原始交易状态，1 成功 2 失败';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.PAY_STATUS IS '映射后的支付状态 SUCCESS / FAIL';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.HANDLE_STATUS IS '本次处理结果 SUCCESS / FAIL / MANUAL，MANUAL 需运维巡检';
COMMENT ON COLUMN ALIPAY_PAY_CALLBACK_LOG.HANDLE_MSG IS '处理结果说明，失败原因截断 500 字';

CREATE INDEX IDX_APCL_ORDER_NO_TYPE ON ALIPAY_PAY_CALLBACK_LOG (ORDER_NO, CALLBACK_TYPE);

CREATE INDEX IDX_APCL_HANDLE_STATUS ON ALIPAY_PAY_CALLBACK_LOG (HANDLE_STATUS);

-- 退款单号唯一索引 UK_ARL_REFUND_ORDER_NO：存量有重复，尚未执行
CREATE UNIQUE INDEX UK_ARL_REFUND_ORDER_NO ON ALIPAY_REFUND_LOG (REFUND_ORDER_NO);
