-- 支付宝出行渠道 支付交易明细 / 退款明细。

CREATE TABLE ALIPAY_PAY_TXN_DETAIL (
    ID                   NUMBER(22) NOT NULL,

    ORDER_NO             VARCHAR2(128 CHAR) NOT NULL,
    PAY_TYPE             VARCHAR2(32 CHAR) DEFAULT 'PAY' NOT NULL,
    PAY_STATUS           VARCHAR2(32 CHAR) DEFAULT 'INIT' NOT NULL,

    THIRD_USER_ID        VARCHAR2(128 CHAR),
    CARD_ID              VARCHAR2(64 CHAR),
    CARD_TYPE            VARCHAR2(64 CHAR),

    PAYMENT_VENDOR       VARCHAR2(32 CHAR),
    PAY_CHANNEL_CODE     VARCHAR2(32 CHAR),
    REQUEST_SIGN_SEQ     VARCHAR2(256 CHAR),
    CHANNEL_AGREEMENT_NO VARCHAR2(256 CHAR),

    AMOUNT               NUMBER(22) DEFAULT 0 NOT NULL,
    TOTAL_AMOUNT         NUMBER(22),
    CASH_AMOUNT          NUMBER(22),
    COUPON_AMOUNT        NUMBER(22),

    REFUND_STATUS        VARCHAR2(32 CHAR) DEFAULT 'NONE' NOT NULL,
    REFUND_AMOUNT        NUMBER(22) DEFAULT 0 NOT NULL,
    LAST_REFUND_TIME     TIMESTAMP(6),

    MERCHANT_ORDER_NO    VARCHAR2(128 CHAR),
    PAY_CENTER_ORDER_NO  VARCHAR2(128 CHAR),
    CHANNEL_ORDER_NO     VARCHAR2(256 CHAR),
    PAY_USER_ID          VARCHAR2(256 CHAR),

    REQUEST_COUNT        NUMBER(22) DEFAULT 0 NOT NULL,
    NEXT_REQUEST_TIME    TIMESTAMP(6),
    LAST_REQUEST_TIME    TIMESTAMP(6),
    FIRST_REQUEST_TIME   TIMESTAMP(6),
    RESPONSE_TIME        TIMESTAMP(6),
    PAY_TIME             VARCHAR2(28 CHAR),
    TXN_DATE             VARCHAR2(8 CHAR) NOT NULL,

    SCENE                VARCHAR2(32 CHAR),
    INDUSTRY_TYPE        VARCHAR2(32 CHAR),
    SUBJECT              VARCHAR2(256 CHAR),
    BODY                 VARCHAR2(512 CHAR),
    AUTH_CODE            VARCHAR2(128 CHAR),
    NOTIFY_URL           VARCHAR2(512 CHAR),
    RETURN_URL           VARCHAR2(512 CHAR),
    IP_ADDRESS           VARCHAR2(64 CHAR),
    ORDER_TIME_OUT       NUMBER(22),
    INDUSTRY_DETAIL      CLOB,

    ENTRY_ID             VARCHAR2(128 CHAR),
    EXIT_ID              VARCHAR2(128 CHAR),
    INVOICE              VARCHAR2(32 CHAR),

    DISCOUNT_INFO        VARCHAR2(512 CHAR),
    DEBIT_REQUEST_RESULT VARCHAR2(16 CHAR),
    DISCOUNT_FEE         NUMBER(22),

    RESULT_CODE          VARCHAR2(32 CHAR),
    RESULT_MSG           VARCHAR2(512 CHAR),
    REMARK               VARCHAR2(512 CHAR),
    REQUEST_BODY         CLOB,
    RESPONSE_BODY        CLOB,

    CREATE_TIME          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ALIPAY_PAY_TXN_DETAIL PRIMARY KEY (ID)
)
PARTITION BY RANGE (TXN_DATE) (
    PARTITION P202606 VALUES LESS THAN ('20260701'),
    PARTITION P202607 VALUES LESS THAN ('20260801'),
    PARTITION P202608 VALUES LESS THAN ('20260901'),
    PARTITION P202609 VALUES LESS THAN ('20261001'),
    PARTITION P202610 VALUES LESS THAN ('20261101'),
    PARTITION P202611 VALUES LESS THAN ('20261201'),
    PARTITION P202612 VALUES LESS THAN ('20270101'),
    PARTITION P_MAX   VALUES LESS THAN (MAXVALUE)
);

CREATE SEQUENCE SEQ_ALIPAY_PAY_TXN_DETAIL
    START WITH 1
    INCREMENT BY 1
    CACHE 1000
    NOCYCLE;

-- 业务唯一键。
CREATE UNIQUE INDEX UK_APTD_ORDER
ON ALIPAY_PAY_TXN_DETAIL (ORDER_NO, TXN_DATE) LOCAL;

CREATE INDEX IDX_APTD_STATUS
ON ALIPAY_PAY_TXN_DETAIL (PAY_STATUS, TXN_DATE, NEXT_REQUEST_TIME) LOCAL;

-- 欠费盘点 countUnsettledByCardId 的支撑索引。旧表这条查询是全表扫。
CREATE INDEX IDX_APTD_CARD_STATUS
ON ALIPAY_PAY_TXN_DETAIL (CARD_ID, PAY_STATUS) LOCAL;

CREATE INDEX IDX_APTD_USER_DATE
ON ALIPAY_PAY_TXN_DETAIL (THIRD_USER_ID, TXN_DATE) LOCAL;

CREATE INDEX IDX_APTD_CHANNEL_ORDER
ON ALIPAY_PAY_TXN_DETAIL (CHANNEL_ORDER_NO, TXN_DATE) LOCAL;

-- 进出站关联查询（payLog/entryId、payLog/exitId、findTravelDetail）。
CREATE INDEX IDX_APTD_ENTRY_ID
ON ALIPAY_PAY_TXN_DETAIL (ENTRY_ID) LOCAL;

CREATE INDEX IDX_APTD_EXIT_ID
ON ALIPAY_PAY_TXN_DETAIL (EXIT_ID) LOCAL;

COMMENT ON TABLE  ALIPAY_PAY_TXN_DETAIL IS '支付宝出行渠道支付交易明细表';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.ORDER_NO IS '地铁侧订单号，同时作为支付中心接口的 orderNo';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_TYPE IS '交易类型：PAY支付，REFUND退款';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_STATUS IS '支付状态：INIT初始化，PROCESSING处理中，SUCCESS成功，FAIL失败，RETRY待重试，CLOSED关闭';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.THIRD_USER_ID IS '支付宝侧用户标识';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CARD_ID IS '逻辑卡号';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CARD_TYPE IS '票卡类型';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAYMENT_VENDOR IS '支付方式';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_CHANNEL_CODE IS '支付通道编码';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.REQUEST_SIGN_SEQ IS '我方签约流水号，取 ALIPAY_SIGN_INFO.AGREEMENT_CODE';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CHANNEL_AGREEMENT_NO IS '渠道协议号，取 ALIPAY_SIGN_INFO.CHANNEL_AGREEMENT_CODE；与上一列不是同一个号，销卡通知只认这个';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.AMOUNT IS '请求支付金额，单位分';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.TOTAL_AMOUNT IS '订单总金额，单位分';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CASH_AMOUNT IS '实付金额，单位分';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.COUPON_AMOUNT IS '优惠金额，单位分';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.REFUND_STATUS IS '退款状态：NONE未退款，PROCESSING退款中，PARTIAL部分退款，SUCCESS已全额退款，FAIL退款失败';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.REFUND_AMOUNT IS '已退款总金额（单位分），由 ALIPAY_REFUND_TXN_DETAIL 重算得出，NEVER 累加写入';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.MERCHANT_ORDER_NO IS '商户订单号';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_CENTER_ORDER_NO IS '支付中心支付订单号；退款报文的「原支付订单号」取此列，缺它退款必失败';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CHANNEL_ORDER_NO IS '渠道订单号，即支付宝交易号（旧表 TRADE_NO）';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_USER_ID IS '支付渠道账户或买家账户';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.REQUEST_COUNT IS '已发起支付请求次数';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.NEXT_REQUEST_TIME IS '下次允许重试支付时间';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.PAY_TIME IS '支付完成时间，格式YYYYMMDDHH24MISS，回调原文直存';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.TXN_DATE IS '订单日期，格式YYYYMMDD，用于月分区与唯一键';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.ORDER_TIME_OUT IS '订单超时时间，单位秒（旧表是字符串）';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.INDUSTRY_DETAIL IS '行业详情JSON，由 fep-dev-server 组装、BizDataBuilder 补渠道协议号';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.ENTRY_ID IS '进站交易ID';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.EXIT_ID IS '出站交易ID';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.DEBIT_REQUEST_RESULT IS '扣款结果：PROCESSING/SUCCESS/FAIL；与对外契约字段 debitRequestResult 的 0/1 值域同名不同义，NEVER 混用';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.RESULT_CODE IS '支付中心业务应答码';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.RESULT_MSG IS '支付中心业务应答文案；NEVER 把它当 debitRequestResult 直接对外返回';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN ALIPAY_PAY_TXN_DETAIL.UPDATE_TIME IS '更新时间';

-- 退款明细表。

CREATE TABLE ALIPAY_REFUND_TXN_DETAIL (
    ID                  NUMBER(22) NOT NULL,

    REFUND_ORDER_NO     VARCHAR2(128 CHAR) NOT NULL,
    ORDER_NO            VARCHAR2(128 CHAR) NOT NULL,
    REFUND_STATUS       VARCHAR2(32 CHAR) DEFAULT 'INIT' NOT NULL,

    REFUND_AMOUNT       NUMBER(22) NOT NULL,
    REFUND_REASON       VARCHAR2(1024 CHAR),

    THIRD_USER_ID       VARCHAR2(128 CHAR),
    CARD_ID             VARCHAR2(64 CHAR),
    CARD_ISSUE_CODE     VARCHAR2(32 CHAR),

    MERCHANT_REFUND_NO  VARCHAR2(128 CHAR),
    REFUND_NO           VARCHAR2(128 CHAR),
    CHANNEL_REFUND_NO   VARCHAR2(256 CHAR),

    REQUEST_COUNT       NUMBER(22) DEFAULT 0 NOT NULL,
    NEXT_REQUEST_TIME   TIMESTAMP(6),
    LAST_REQUEST_TIME   TIMESTAMP(6),

    REFUND_TIME         VARCHAR2(28 CHAR),
    TXN_DATE            VARCHAR2(8 CHAR) NOT NULL,

    RET_CODE            VARCHAR2(32 CHAR),
    RET_MSG             VARCHAR2(512 CHAR),
    PAY_CENTER_CODE     VARCHAR2(32 CHAR),
    PAY_CENTER_MSG      VARCHAR2(1024 CHAR),

    OPERATOR            VARCHAR2(64 CHAR),
    IP_ADDRESS          VARCHAR2(64 CHAR),
    REMARK              VARCHAR2(512 CHAR),

    REQUEST_BODY        CLOB,
    RESPONSE_BODY       CLOB,

    CREATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ALIPAY_REFUND_TXN_DETAIL PRIMARY KEY (ID)
)
PARTITION BY RANGE (TXN_DATE) (
    PARTITION P202606 VALUES LESS THAN ('20260701'),
    PARTITION P202607 VALUES LESS THAN ('20260801'),
    PARTITION P202608 VALUES LESS THAN ('20260901'),
    PARTITION P202609 VALUES LESS THAN ('20261001'),
    PARTITION P202610 VALUES LESS THAN ('20261101'),
    PARTITION P202611 VALUES LESS THAN ('20261201'),
    PARTITION P202612 VALUES LESS THAN ('20270101'),
    PARTITION P_MAX   VALUES LESS THAN (MAXVALUE)
);

CREATE SEQUENCE SEQ_ALIPAY_REFUND_TXN_DETAIL
    START WITH 1
    INCREMENT BY 1
    CACHE 1000
    NOCYCLE;

CREATE UNIQUE INDEX UK_ARTD_REFUND_ORDER
ON ALIPAY_REFUND_TXN_DETAIL (REFUND_ORDER_NO, TXN_DATE) LOCAL;

-- updateRefundSummary 的相关子查询按 (ORDER_NO, REFUND_STATUS) 求和，两列都进索引。
CREATE INDEX IDX_ARTD_ORDER_STATUS
ON ALIPAY_REFUND_TXN_DETAIL (ORDER_NO, REFUND_STATUS) LOCAL;

CREATE INDEX IDX_ARTD_STATUS
ON ALIPAY_REFUND_TXN_DETAIL (REFUND_STATUS, TXN_DATE, NEXT_REQUEST_TIME) LOCAL;

COMMENT ON TABLE  ALIPAY_REFUND_TXN_DETAIL IS '支付宝出行渠道退款明细表';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.REFUND_ORDER_NO IS '内部退款单号，由本模块生成';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.ORDER_NO IS '原支付订单号，对应 ALIPAY_PAY_TXN_DETAIL.ORDER_NO';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.REFUND_STATUS IS '退款状态：INIT初始化，PROCESSING处理中，SUCCESS成功，FAIL失败，RETRY待重试，CLOSED关闭；拿不到业务应答时 MUST 保持 PROCESSING，NEVER 置 FAIL';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.REFUND_AMOUNT IS '退款金额，单位分';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.REQUEST_COUNT IS '已发起退款请求次数';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.NEXT_REQUEST_TIME IS '下次允许重试退款时间';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.TXN_DATE IS '退款发起日期，格式YYYYMMDD，用于月分区与唯一键；与原支付单的 TXN_DATE 各自独立，NEVER 复用原单日期';
COMMENT ON COLUMN ALIPAY_REFUND_TXN_DETAIL.PAY_CENTER_CODE IS '支付中心应答码，与我方 RET_CODE 分列存放';

-- 后续月分区维护示例。
