apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    security: 'true'
  labels:
    app: account
  name: account
  namespace: itp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - env:
        - name: employee-card.format
          value: json
        - name: itp.format
          value: json
        - name: employee-card.read-timeout-ms
          value: '10000'
        - name: other.sql.double-datasource
          value: 'false'
        - name: other.web.enableLogRequestInFilter
          value: 'true'
        - name: other.web.enableBodyCacheFilter
          value: 'true'
        - name: account.card-pool.debug-manual-card-id
          value: '9900000000000001'
        - name: itp.charset
          value: UTF-8
        - name: account.card-pool.debug-manual-allocate
          value: 'true'
        - name: mybatis.mapper-locations
          value: classpath*:mapper/*.xml
        - name: knife4j.production
          value: 'false'
        - name: service.ticket.url
          value: http://172.20.211.200:30014
        - name: server.port
          value: '9098'
        - name: other.sql.username
          value: qditp
        - name: account.card-pool.threshold
          value: '10'
        - name: service.ticket.openLogger
          value: 'true'
        - name: employee-card.acc-query-url
          value: http://172.20.211.11:32605/api/v1/employee_card/query
        - name: employee-card.provider-id
          value: '06'
        - name: other.web.enableLogTakeTimesInInterceptor
          value: 'true'
        - name: VLOGS_URL
          value: http://victoria-logs-pbi6a-svc.itp.svc:30032
        - name: other.sql.host
          value: 172.20.222.3:1521
        - name: service.security.url
          value: http://172.20.211.200:30012
        - name: service.paySign.url
          value: http://172.20.211.23:30016
        - name: service.security.hce-card-data.url
          value: http://172.20.201.2:12301/secret-web/ci/itp/requestHceCardData
        - name: service.cardPool.openLogger
          value: 'true'
        - name: spring.application.name
          value: account
        - name: itp.signKey
          valueFrom:
            secretKeyRef:
              name: itp-secrets
              key: itp.signKey
        - name: employee-card.device-id
          value: ITP
        - name: service.gateTxnPay.url
          value: http://gate-txn-pay-server-jomf4-svc.itp.svc:30019
        - name: account.card-pool.batch-size
          value: '20'
        - name: employee-card.app-register-url
          value: https://dtcustomer.bestonepay.com/testngbackV2/ci/app/v2/employeeCardSync
        - name: employee-card.connect-timeout-ms
          value: '3000'
        - name: service.cardPool.url
          value: ${CARD_POOL_URL:http://card-pool-server-86mc1-svc.itp.svc:30033}
        - name: other.sql.page.type
          value: oracle
        - name: other.web.unSafeUrlChars
          value: 'null'
        - name: employee-card.sign-type
          value: '00'
        - name: other.sql.password
          valueFrom:
            secretKeyRef:
              name: itp-secrets
              key: other.sql.password
        - name: itp.providerId
          value: '01'
        - name: other.sql.database
          value: AFCITPDB
        - name: other.sql.type
          value: oracle
        - name: employee-card.charset
          value: UTF-8
        - name: service.paySign.openLogger
          value: 'true'
        - name: employee-card.app-batch-size
          value: '200'
        - name: SERVICE_NAME
          value: account
        - name: NAMESPACE
          value: itp
        image: os-harbor-svc.default.svc.cloudos:443/itp/account-server:2.0.77
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: account
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi
        securityContext:
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /etc/localtime
          name: hostpath-hxb74wr80
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ''
        name: hostpath-hxb74wr80
