apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    security: 'true'
  labels:
    app: daily-ticket-server
  name: daily-ticket-server
  namespace: itp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daily-ticket-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: daily-ticket-server
    spec:
      containers:
      - env:
        - name: other.web.enableLogRequestInFilter
          value: 'true'
        - name: other.web.enableBodyCacheFilter
          value: 'true'
        - name: other.sql.double-datasource
          value: 'false'
        - name: daily-ticket.pay.api-version
          value: ${DAILY_TICKET_PAY_API_VERSION:1.0}
        - name: daily-ticket.pay.sign-type
          value: ${DAILY_TICKET_PAY_SIGN_TYPE:RSA2}
        - name: mybatis.mapper-locations
          value: classpath*:mapper/*.xml
        - name: knife4j.production
          value: 'true'
        - name: server.port
          value: '9108'
        - name: other.sql.username
          value: ${DB_USERNAME:qditp}
        - name: other.web.enableLogTakeTimesInInterceptor
          value: 'true'
        - name: VLOGS_URL
          value: http://victoria-logs-pbi6a-svc.itp.svc:30032
        - name: other.sql.host
          value: ${DB_HOST:172.20.222.3:1521}
        - name: daily-ticket.pay.notify-url
          value: ${DAILY_TICKET_PAY_NOTIFY_URL:http://58.56.166.170:48000/fep-app/app/payment/receivePayResult}
        - name: daily-ticket.pay.gateway-url
          value: ${DAILY_TICKET_PAY_GATEWAY_URL:http://dtcustomer.bestonepay.com/ngpayment-gateway}
        - name: daily-ticket.pay.return-url
          value: ${DAILY_TICKET_PAY_RETURN_URL:}
        - name: service.cardPool.openLogger
          value: 'true'
        - name: spring.application.name
          value: daily-ticket-server
        - name: daily-ticket.pay.body
          value: el-ticket
        - name: service.cardPool.url
          value: ${CARD_POOL_URL:http://card-pool-server-86mc1-svc.itp.svc:30033}
        - name: other.web.unSafeUrlChars
          value: 'null'
        - name: other.sql.page.type
          value: oracle
        - name: other.sql.password
          valueFrom:
            secretKeyRef:
              name: itp-secrets
              key: other.sql.password
        - name: daily-ticket.pay.request-pay-path
          value: ${DAILY_TICKET_PAY_REQUEST_PAY_PATH:/api/v1/payment/requestPay}
        - name: other.sql.database
          value: ${DB_NAME:AFCITPDB}
        - name: other.sql.type
          value: oracle
        - name: daily-ticket.pay.subject
          value: el-ticket
        - name: daily-ticket.pay.merchant-no
          value: ${DAILY_TICKET_PAY_MERCHANT_NO:JOPJ490HLK9Z}
        - name: daily-ticket.pay.charset
          value: ${DAILY_TICKET_PAY_CHARSET:UTF-8}
        - name: daily-ticket.pay.request-refund-path
          value: ${DAILY_TICKET_PAY_REQUEST_REFUND_PATH:/api/v1/refund/requestRefund}
        - name: daily-ticket.pay.industry-type
          value: '1'
        - name: SERVICE_NAME
          value: daily-ticket-server
        - name: NAMESPACE
          value: itp
        - name: RECON_INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: itp-secrets
              key: RECON_INTERNAL_TOKEN
        - name: SERVICE_RECON_URL
          value: http://recon-server-bjzdy-svc.itp.svc:30034
        - name: DAILY_TICKET_NOTIFY_APP_REFUND_RESULT_URL
          value: https://dtcustomer.bestonepay.com/testngbackV2/ci/app/v2/receiveRefundResult
        - name: DAILY_TICKET_NOTIFY_APP_PAY_RESULT_URL
          value: https://dtcustomer.bestonepay.com/testngbackV2/ci/app/v2/receivePaymentResult
        - name: daily-ticket.pay.refund-notify-url
          value: http://58.56.166.170:48000/fep-app/app/payment/receiveRefundResult
        image: os-harbor-svc.default.svc.cloudos:443/itp/daily-ticket-server:1.0.63
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: daily-ticket-server
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 2Gi
        securityContext:
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /etc/localtime
          name: hostpath-49x8t0hf0
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ''
        name: hostpath-49x8t0hf0
