-- ============================================
-- 支付宝出行接口建表语句
-- 生成日期：2026-07-02
-- 说明：支付宝独立表结构，与地铁APP表完全隔离
-- ============================================

-- 7. 支付宝乘车记录表 ALIPAY_TRAVEL_RECORD
CREATE TABLE ALIPAY_TRAVEL_RECORD (
    ORDER_NO VARCHAR2(64) NOT NULL,
    THIRD_USER_ID VARCHAR2(64) NOT NULL,
    CARD_ID VARCHAR2(32) NOT NULL,
    CARD_TYPE VARCHAR2(16) NOT NULL,
    CHANNEL VARCHAR2(32) NOT NULL,
    TRADE_ORDER_NO VARCHAR2(64),
    TXN_SEQ VARCHAR2(32),
    ENTRY_STATION_NAME VARCHAR2(64),
    ENTRY_DATE VARCHAR2(16),
    GATE_IN_STATION VARCHAR2(64),
    EXIT_STATION_NAME VARCHAR2(64),
    EXIT_DATE VARCHAR2(16),
    GATE_OUT_STATION VARCHAR2(64),
    PAY_METHOD VARCHAR2(16),
    TOTAL_AMOUNT VARCHAR2(16),
    DISCOUNT_AMOUNT VARCHAR2(16),
    PAY_AMOUNT VARCHAR2(16),
    STATUS VARCHAR2(16),
    DELETE_FLAG VARCHAR2(1) DEFAULT '0',
    VERSION VARCHAR2(32) DEFAULT '1',
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    CREATE_BY VARCHAR2(32),
    CONSTRAINT PK_ALIPAY_TRAVEL_RECORD PRIMARY KEY (ORDER_NO)
);

-- 索引
CREATE INDEX IDX_ALIPAY_TRAVEL_USER ON ALIPAY_TRAVEL_RECORD (THIRD_USER_ID, CHANNEL);
CREATE INDEX IDX_ALIPAY_TRAVEL_CARD ON ALIPAY_TRAVEL_RECORD (CARD_ID);
CREATE INDEX IDX_ALIPAY_TRAVEL_DATE ON ALIPAY_TRAVEL_RECORD (ENTRY_DATE);

-- 注释
COMMENT ON TABLE ALIPAY_TRAVEL_RECORD IS '支付宝乘车记录表';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.ORDER_NO IS '订单号（主键）';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.THIRD_USER_ID IS '支付宝用户ID';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.CARD_ID IS '逻辑卡号';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.CARD_TYPE IS '发卡类型代码';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.CHANNEL IS '支付渠道';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.TRADE_ORDER_NO IS '交易订单号';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.TXN_SEQ IS '交易序列号';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.ENTRY_STATION_NAME IS '进站站点名称';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.ENTRY_DATE IS '进站时间';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.GATE_IN_STATION IS '进站闸机';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.EXIT_STATION_NAME IS '出站站点名称';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.EXIT_DATE IS '出站时间';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.GATE_OUT_STATION IS '出站闸机';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.PAY_METHOD IS '支付方式';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.TOTAL_AMOUNT IS '总金额（分）';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.DISCOUNT_AMOUNT IS '优惠金额（分）';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.PAY_AMOUNT IS '实付金额（分）';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.STATUS IS '记录状态';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.DELETE_FLAG IS '删除标记（0:正常 1:删除）';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.VERSION IS '乐观锁版本号';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN ALIPAY_TRAVEL_RECORD.CREATE_BY IS '创建人';
