ALTER TABLE RECON_BATCH ADD (FAIL_REASON VARCHAR2(1024));

ALTER TABLE RECON_BATCH_PART ADD (AMOUNT_TOTAL NUMBER(19) DEFAULT 0 NOT NULL);

ALTER TABLE RECON_BATCH_PART ADD (RETRY_COUNT NUMBER(8) DEFAULT 0 NOT NULL);

ALTER TABLE RECON_BATCH_FILE ADD (AMOUNT_TOTAL NUMBER(19) DEFAULT 0 NOT NULL);

CREATE TABLE RECON_BATCH_SOURCE (
    BATCH_ID VARCHAR2(64) NOT NULL,
    SOURCE_NAME VARCHAR2(32) NOT NULL,
    FILE_TYPE VARCHAR2(16) NOT NULL,
    STATUS VARCHAR2(24) NOT NULL,
    DECLARED_PARTS NUMBER(10) DEFAULT 0 NOT NULL,
    DECLARED_RECORDS NUMBER(19) DEFAULT 0 NOT NULL,
    DECLARED_AMOUNT NUMBER(19) DEFAULT 0 NOT NULL,
    RETRY_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    FAIL_REASON VARCHAR2(1024),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECON_BATCH_SOURCE PRIMARY KEY (BATCH_ID, SOURCE_NAME, FILE_TYPE),
    CONSTRAINT FK_RECON_SOURCE_BATCH FOREIGN KEY (BATCH_ID) REFERENCES RECON_BATCH(BATCH_ID)
);

CREATE INDEX IDX_RECON_SOURCE_STATUS ON RECON_BATCH_SOURCE (BATCH_ID, STATUS);
