CREATE TABLE RECON_BATCH (
    BATCH_ID VARCHAR2(64) NOT NULL,
    BUSINESS_DATE VARCHAR2(8) NOT NULL,
    WINDOW_START VARCHAR2(32) NOT NULL,
    WINDOW_END VARCHAR2(32) NOT NULL,
    STATUS VARCHAR2(24) NOT NULL,
    FAIL_REASON VARCHAR2(1024),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECON_BATCH PRIMARY KEY (BATCH_ID)
);

CREATE TABLE RECON_BATCH_SOURCE (
    BATCH_ID VARCHAR2(64) NOT NULL,
    SOURCE_NAME VARCHAR2(32) NOT NULL,
    FILE_TYPE VARCHAR2(16) NOT NULL,
    STATUS VARCHAR2(24) NOT NULL,
    DECLARED_PARTS NUMBER(10) DEFAULT 0 NOT NULL,
    DECLARED_RECORDS NUMBER(19) DEFAULT 0 NOT NULL,
    DECLARED_AMOUNT NUMBER(19) DEFAULT 0 NOT NULL,
    RETRY_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    FAIL_REASON VARCHAR2(1024),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECON_BATCH_SOURCE PRIMARY KEY (BATCH_ID, SOURCE_NAME, FILE_TYPE),
    CONSTRAINT FK_RECON_SOURCE_BATCH FOREIGN KEY (BATCH_ID) REFERENCES RECON_BATCH(BATCH_ID)
);

CREATE INDEX IDX_RECON_SOURCE_STATUS ON RECON_BATCH_SOURCE (BATCH_ID, STATUS);

CREATE TABLE RECON_BATCH_PART (
    BATCH_ID VARCHAR2(64) NOT NULL,
    SOURCE_NAME VARCHAR2(32) NOT NULL,
    FILE_TYPE VARCHAR2(16) NOT NULL,
    PART_NO NUMBER(10) NOT NULL,
    BYTE_COUNT NUMBER(19) NOT NULL,
    RECORD_COUNT NUMBER(19) NOT NULL,
    AMOUNT_TOTAL NUMBER(19) DEFAULT 0 NOT NULL,
    SHA256 VARCHAR2(64) NOT NULL,
    FILE_PATH VARCHAR2(512) NOT NULL,
    STATUS VARCHAR2(24) NOT NULL,
    RETRY_COUNT NUMBER(8) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECON_BATCH_PART PRIMARY KEY (BATCH_ID, SOURCE_NAME, FILE_TYPE, PART_NO),
    CONSTRAINT FK_RECON_PART_BATCH FOREIGN KEY (BATCH_ID) REFERENCES RECON_BATCH(BATCH_ID)
);

CREATE INDEX IDX_RECON_PART_STATUS ON RECON_BATCH_PART (BATCH_ID, STATUS);

CREATE TABLE RECON_BATCH_FILE (
    BATCH_ID VARCHAR2(64) NOT NULL,
    FILE_TYPE VARCHAR2(16) NOT NULL,
    FILE_NAME VARCHAR2(128) NOT NULL,
    FILE_PATH VARCHAR2(512) NOT NULL,
    BYTE_COUNT NUMBER(19) NOT NULL,
    RECORD_COUNT NUMBER(19) NOT NULL,
    AMOUNT_TOTAL NUMBER(19) DEFAULT 0 NOT NULL,
    SHA256 VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(24) NOT NULL,
    REMOTE_PATH VARCHAR2(512),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECON_BATCH_FILE PRIMARY KEY (BATCH_ID, FILE_TYPE),
    CONSTRAINT FK_RECON_FILE_BATCH FOREIGN KEY (BATCH_ID) REFERENCES RECON_BATCH(BATCH_ID)
);
