CREATE TABLE ALIPAY_PHONE_CHANGE_LOG (
    ID NUMBER NOT NULL,
    THIRD_USER_ID VARCHAR2(128 CHAR) NOT NULL,
    OLD_MSISDN VARCHAR2(32 CHAR),
    NEW_MSISDN VARCHAR2(32 CHAR) NOT NULL,
    OPER_TYPE VARCHAR2(32 CHAR) NOT NULL,
    OPER_TIME TIMESTAMP(6) NOT NULL,
    OPERATOR VARCHAR2(64 CHAR),
    REMARK VARCHAR2(256 CHAR),
    CREATE_TMS TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_ALIPAY_PHONE_CHANGE_LOG PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ALIPAY_PHONE_CHANGE_LOG START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_ALIPAY_PHONE_CHG_USER_ID
    ON ALIPAY_PHONE_CHANGE_LOG (THIRD_USER_ID);

CREATE INDEX IDX_ALIPAY_PHONE_CHG_TIME
    ON ALIPAY_PHONE_CHANGE_LOG (OPER_TIME);

COMMENT ON TABLE ALIPAY_PHONE_CHANGE_LOG IS '支付宝渠道用户手机号更换历史记录表，由 alipay-account-server 独占写入';
COMMENT ON COLUMN ALIPAY_PHONE_CHANGE_LOG.ID IS '主键，取 SEQ_ALIPAY_PHONE_CHANGE_LOG';
COMMENT ON COLUMN ALIPAY_PHONE_CHANGE_LOG.THIRD_USER_ID IS '支付宝用户标识，对应 ALIPAY_USER_INFO.THIRD_USER_ID';
COMMENT ON COLUMN ALIPAY_PHONE_CHANGE_LOG.OLD_MSISDN IS '变更前手机号，首次登记时可为空';
COMMENT ON COLUMN ALIPAY_PHONE_CHANGE_LOG.NEW_MSISDN IS '变更后手机号';
COMMENT ON COLUMN ALIPAY_PHONE_CHANGE_LOG.OPER_TYPE IS '操作类型：CHANGE_PHONE-更换手机号';
COMMENT ON COLUMN ALIPAY_PHONE_CHANGE_LOG.OPER_TIME IS '操作发生时间';
COMMENT ON COLUMN ALIPAY_PHONE_CHANGE_LOG.OPERATOR IS '操作人，系统触发填 SYSTEM';
COMMENT ON COLUMN ALIPAY_PHONE_CHANGE_LOG.REMARK IS '操作说明';
COMMENT ON COLUMN ALIPAY_PHONE_CHANGE_LOG.CREATE_TMS IS '记录落库时间';
