server.port=9099
spring.application.name=online-server

other.web.unSafeUrlChars=null
other.web.enableLogRequestInFilter=true
other.web.enableBodyCacheFilter=true
other.web.enableLogTakeTimesInInterceptor=true

knife4j.production=true

service.token.url=
service.token.openLogger=true

server.tomcat.basedir=${LOG_PATH:./logs}
logging.file.path=${LOG_PATH:./logs}

service.route.mapping.default=

online.pay.base-url=http://127.0.0.1:9099/qd_itp/requestPay
online.default-provider-id=01
online.default-card-type=0441
online.default-issue-channel-code=01
online.default-sign-channel-code=04
online.max-topup-amount=1000
