ALTER TABLE TICKET_COLLECT_INFO ADD (CASH_AMOUNT NUMBER(12));

ALTER TABLE TICKET_COLLECT_INFO ADD (COUPON_AMOUNT NUMBER(12));

COMMENT ON COLUMN TICKET_COLLECT_INFO.CASH_AMOUNT IS '实付现金金额,单位分,取支付中心支付结果回调的cashAmount原值';

COMMENT ON COLUMN TICKET_COLLECT_INFO.COUPON_AMOUNT IS '优惠金额,单位分,取支付中心支付结果回调的couponAmount原值';

SELECT COLUMN_NAME, DATA_TYPE, DATA_PRECISION, NULLABLE
FROM USER_TAB_COLS
WHERE TABLE_NAME = 'TICKET_COLLECT_INFO'
  AND COLUMN_NAME IN ('CASH_AMOUNT', 'COUPON_AMOUNT');
