-- 扩展 COM_DEVICE_SYN_KEY 表，增加响应状态和耗时字段
ALTER TABLE COM_DEVICE_SYN_KEY ADD (
    RESP_RET_CODE VARCHAR2(10 CHAR),
    RESP_RET_MSG VARCHAR2(200 CHAR),
    RESP_KEY_VERSION_COUNT NUMBER(10) DEFAULT 0,
    PROCESS_DURATION_MS NUMBER(10),
    STATUS VARCHAR2(20 CHAR) DEFAULT 'SUCCESS',
    ERROR_MSG VARCHAR2(512 CHAR)
);

COMMENT ON COLUMN COM_DEVICE_SYN_KEY.RESP_RET_CODE IS '响应返回码（0000=成功）';
COMMENT ON COLUMN COM_DEVICE_SYN_KEY.RESP_RET_MSG IS '响应返回信息';
COMMENT ON COLUMN COM_DEVICE_SYN_KEY.RESP_KEY_VERSION_COUNT IS '下发给设备的密钥版本数量';
COMMENT ON COLUMN COM_DEVICE_SYN_KEY.PROCESS_DURATION_MS IS '处理耗时（毫秒）';
COMMENT ON COLUMN COM_DEVICE_SYN_KEY.STATUS IS '同步状态：SUCCESS=成功, FAIL=失败';
COMMENT ON COLUMN COM_DEVICE_SYN_KEY.ERROR_MSG IS '失败原因';
