server.port=9103
spring.application.name=key

other.web.unSafeUrlChars=null
other.web.enableLogRequestInFilter=true
other.web.enableBodyCacheFilter=true
other.web.enableLogTakeTimesInInterceptor=true

knife4j.production=false

other.sql.host=${DB_HOST:127.0.0.1:1521}
other.sql.double-datasource=false
other.sql.type=oracle
other.sql.page.type=oracle
other.sql.database=${DB_NAME:orcl}
other.sql.username=${DB_USERNAME:}
other.sql.password=${DB_PASSWORD:}

mybatis.mapper-locations=classpath*:mapper/*.xml

service.security.url=http://127.0.0.1:9012
service.security.openLogger=true

appserver.3des.key=505152535455565758595A5B5C5D5E5F
acc.3des.key=404142434445464748494A4B4C4D4E4F4041424344454647

key.sync.days=7
key.sync.kek-idx=0012
