<template>
  <div class="app-container">
    <el-form :model="query" :inline="true"><el-form-item label="风险组名称"><el-input v-model="query.groupName" clearable placeholder="请输入风险组名称" @keyup.enter="search" /></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="search">查询</el-button><el-button icon="Refresh" @click="resetQuery">重置</el-button></el-form-item></el-form>
    <el-row class="mb8"><el-col :span="1.5"><el-button v-hasPermi="['para:risk-group:add']" type="primary" plain icon="Plus" @click="add">新增</el-button></el-col></el-row>
    <el-table v-loading="loading" :data="rows" border><el-table-column label="序号" width="70" align="center"><template #default="s">{{ (query.pageNum - 1) * query.pageSize + s.$index + 1 }}</template></el-table-column><el-table-column label="风险组名称" prop="groupName" min-width="220"/><el-table-column label="风险组描述" prop="groupDesc" min-width="350" show-overflow-tooltip/><el-table-column label="创建时间" width="180" align="center"><template #default="{ row }">{{ parseTime(row.createTime) || '-' }}</template></el-table-column><el-table-column label="修改时间" width="180" align="center"><template #default="{ row }">{{ parseTime(row.updateTime) || '-' }}</template></el-table-column><el-table-column label="操作" width="120" align="center"><template #default="{ row }"><el-tooltip content="修改"><el-button v-hasPermi="['para:risk-group:edit']" link type="primary" icon="Edit" @click="edit(row)" /></el-tooltip><el-tooltip content="删除"><el-button v-hasPermi="['para:risk-group:remove']" link type="danger" icon="Delete" @click="remove(row)" /></el-tooltip></template></el-table-column></el-table>
    <pagination v-show="total > 0" v-model:page="query.pageNum" v-model:limit="query.pageSize" :total="total" @pagination="load"/>
    <el-dialog v-model="open" :title="title" width="520px" append-to-body destroy-on-close><el-form ref="formRef" :model="form" :rules="rules" label-width="100px"><el-form-item label="风险组名称" prop="groupName"><el-input v-model="form.groupName" maxlength="100"/></el-form-item><el-form-item label="风险组描述" prop="groupDesc"><el-input v-model="form.groupDesc" type="textarea" :rows="4" maxlength="500" show-word-limit/></el-form-item></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" :loading="saving" @click="submit">确定</el-button></template></el-dialog>
  </div>
</template>
<script setup name="RiskGroup">
import { addRiskGroup, delRiskGroup, listRiskGroups, updateRiskGroup } from '@/api/para/risk'
// 风险组删除受后端规则引用校验保护，页面直接展示业务错误。
const { proxy } = getCurrentInstance(); const loading=ref(false), saving=ref(false), open=ref(false), editing=ref(false), title=ref(''), rows=ref([]), total=ref(0)
const query=reactive({ groupName:'', pageNum:1, pageSize:10 }); const form=reactive({ groupId:null, groupName:'', groupDesc:'' }); const rules={ groupName:[{required:true,message:'请输入风险组名称',trigger:'blur'}] }
function load(){ loading.value=true; listRiskGroups({...query}).then(r=>{rows.value=r.data?.list||[];total.value=Number(r.data?.total||0)}).finally(()=>loading.value=false) }
function search(){query.pageNum=1;load()} function resetQuery(){query.groupName='';search()} function resetForm(){Object.assign(form,{groupId:null,groupName:'',groupDesc:''});proxy.resetForm('formRef')}
function add(){resetForm();editing.value=false;title.value='新增风险组';open.value=true} function edit(row){resetForm();Object.assign(form,row);editing.value=true;title.value='修改风险组';open.value=true}
function submit(){proxy.$refs.formRef.validate(valid=>{if(!valid)return;saving.value=true;const data={groupName:form.groupName.trim(),groupDesc:form.groupDesc.trim()||null};(editing.value?updateRiskGroup(form.groupId,data):addRiskGroup(data)).then(()=>{proxy.$modal.msgSuccess(editing.value?'修改成功':'新增成功');open.value=false;load()}).finally(()=>saving.value=false)})}
function remove(row){proxy.$modal.confirm(`确认删除风险组“${row.groupName}”吗？`).then(()=>delRiskGroup(row.groupId)).then(()=>{proxy.$modal.msgSuccess('删除成功');load()}).catch(()=>{})} onMounted(load)
</script>
