server.port=9097
spring.application.name=wallet

other.web.unSafeUrlChars=null
other.web.enableLogRequestInFilter=true
other.web.enableBodyCacheFilter=true
other.web.enableLogTakeTimesInInterceptor=true

knife4j.production=true

service.token.url=
service.token.openLogger=true

server.tomcat.basedir=/Users/zhoucong/logs
logging.file.path=/Users/zhoucong/logs

service.route.mapping.default=

wallet.sign.alipay.app-id=60000157
wallet.sign.alipay.merchant-app-id=2015101000413186
wallet.sign.wechat.app-id=wx426a3015555a46be
wallet.sign.wechat.entrust-url=https://api.mch.weixin.qq.com/papay/entrustweb
