CREATE TABLE STATION_INFO (
    STATION_CODE     VARCHAR2(16 CHAR)  NOT NULL,
    LINE_CODE        VARCHAR2(8 CHAR)   NOT NULL,
    STATION_NAME     VARCHAR2(128 CHAR) NOT NULL,
    STATION_EN_NAME  VARCHAR2(256 CHAR),
    CONSTRAINT PK_STATION_INFO PRIMARY KEY (STATION_CODE)
);

COMMENT ON TABLE STATION_INFO IS '车站信息表';

COMMENT ON COLUMN STATION_INFO.STATION_CODE IS '车站编号';
COMMENT ON COLUMN STATION_INFO.LINE_CODE IS '线路编号';
COMMENT ON COLUMN STATION_INFO.STATION_NAME IS '车站名称';
COMMENT ON COLUMN STATION_INFO.STATION_EN_NAME IS '车站英文名称';

CREATE INDEX IDX_STATION_INFO_LINE
    ON STATION_INFO (LINE_CODE);


-- 初始化青岛地铁车站信息。
MERGE INTO STATION_INFO T
USING (
    SELECT '0121' AS STATION_CODE, '01' AS LINE_CODE, '王家港' AS STATION_NAME, 'Wangjiagang' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0122' AS STATION_CODE, '01' AS LINE_CODE, '石油大学' AS STATION_NAME, 'China University of Petroleum' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0123' AS STATION_CODE, '01' AS LINE_CODE, '太行山路' AS STATION_NAME, 'Taihangshan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0124' AS STATION_CODE, '01' AS LINE_CODE, '井冈山路' AS STATION_NAME, 'Jinggangshan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0125' AS STATION_CODE, '01' AS LINE_CODE, '丁家河' AS STATION_NAME, 'Dingjiahe' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0126' AS STATION_CODE, '01' AS LINE_CODE, '薛家岛' AS STATION_NAME, 'Xuejiadao' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0127' AS STATION_CODE, '01' AS LINE_CODE, '天目山路' AS STATION_NAME, 'Tianmushan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0128' AS STATION_CODE, '01' AS LINE_CODE, '安子' AS STATION_NAME, 'Anzi' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0129' AS STATION_CODE, '01' AS LINE_CODE, '新港山路' AS STATION_NAME, 'Xingangshan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0130' AS STATION_CODE, '01' AS LINE_CODE, '南北屯' AS STATION_NAME, 'Nanbeitun' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0131' AS STATION_CODE, '01' AS LINE_CODE, '山里' AS STATION_NAME, 'Shanli' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0132' AS STATION_CODE, '01' AS LINE_CODE, '凤凰岛' AS STATION_NAME, 'Fenghuangdao' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0133' AS STATION_CODE, '01' AS LINE_CODE, '团岛' AS STATION_NAME, 'Tuandao' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0134' AS STATION_CODE, '01' AS LINE_CODE, '西镇' AS STATION_NAME, 'Xizhen' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0135' AS STATION_CODE, '01' AS LINE_CODE, '青岛站' AS STATION_NAME, 'Qingdao Railway Station' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0136' AS STATION_CODE, '01' AS LINE_CODE, '中山路' AS STATION_NAME, 'Zhongshan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0137' AS STATION_CODE, '01' AS LINE_CODE, '观象山(市立医院)' AS STATION_NAME, 'Guanxiangshan (Qingdao Municipal Hospital)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0138' AS STATION_CODE, '01' AS LINE_CODE, '广饶路' AS STATION_NAME, 'Guangrao Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0139' AS STATION_CODE, '01' AS LINE_CODE, '台东' AS STATION_NAME, 'Taidong' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0140' AS STATION_CODE, '01' AS LINE_CODE, '海泊桥(海慈医疗)' AS STATION_NAME, 'Haipo Bridge (Hiser Hospital)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0141' AS STATION_CODE, '01' AS LINE_CODE, '小村庄' AS STATION_NAME, 'Xiaocunzhuang' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0142' AS STATION_CODE, '01' AS LINE_CODE, '北岭' AS STATION_NAME, 'Beiling' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0143' AS STATION_CODE, '01' AS LINE_CODE, '水清沟' AS STATION_NAME, 'Shuiqinggou' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0144' AS STATION_CODE, '01' AS LINE_CODE, '中心医院' AS STATION_NAME, 'Qingdao Central Hospital' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0145' AS STATION_CODE, '01' AS LINE_CODE, '胜利桥(纺织谷)' AS STATION_NAME, 'Shengli Bridge (Textile Valley)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0146' AS STATION_CODE, '01' AS LINE_CODE, '安顺路' AS STATION_NAME, 'Anshun Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0147' AS STATION_CODE, '01' AS LINE_CODE, '青岛北站' AS STATION_NAME, 'Qingdao North Railway Station' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0148' AS STATION_CODE, '01' AS LINE_CODE, '沧安路' AS STATION_NAME, 'Cang''an Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0149' AS STATION_CODE, '01' AS LINE_CODE, '永年路' AS STATION_NAME, 'Yongnian Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0150' AS STATION_CODE, '01' AS LINE_CODE, '兴国路' AS STATION_NAME, 'Xingguo Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0151' AS STATION_CODE, '01' AS LINE_CODE, '南岭' AS STATION_NAME, 'Nanling' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0152' AS STATION_CODE, '01' AS LINE_CODE, '遵义路' AS STATION_NAME, 'Zunyi Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0153' AS STATION_CODE, '01' AS LINE_CODE, '瑞金路' AS STATION_NAME, 'Ruijin Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0154' AS STATION_CODE, '01' AS LINE_CODE, '仙家寨(汽车北站)' AS STATION_NAME, 'Xianjiazhai (North Coach Station)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0155' AS STATION_CODE, '01' AS LINE_CODE, '流亭' AS STATION_NAME, 'Liuting' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0156' AS STATION_CODE, '01' AS LINE_CODE, '凤岗路' AS STATION_NAME, 'Fenggang Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0157' AS STATION_CODE, '01' AS LINE_CODE, '小寨子' AS STATION_NAME, 'Xiaozhaizi' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0158' AS STATION_CODE, '01' AS LINE_CODE, '正阳中路' AS STATION_NAME, 'Zhengyang Middle Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0159' AS STATION_CODE, '01' AS LINE_CODE, '农业大学' AS STATION_NAME, 'Qingdao Agricultural University' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0160' AS STATION_CODE, '01' AS LINE_CODE, '沟岔' AS STATION_NAME, 'Goucha' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0161' AS STATION_CODE, '01' AS LINE_CODE, '东郭庄' AS STATION_NAME, 'Dongguozhuang' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0218' AS STATION_CODE, '02' AS LINE_CODE, '四川路(轮渡)' AS STATION_NAME, 'Sichuan Rd (Qingdao Ferry Terminal)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0219' AS STATION_CODE, '02' AS LINE_CODE, '小港' AS STATION_NAME, 'Xiaogang' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0220' AS STATION_CODE, '02' AS LINE_CODE, '国际邮轮港' AS STATION_NAME, 'Qingdao International Cruise Terminal' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0221' AS STATION_CODE, '02' AS LINE_CODE, '泰山路' AS STATION_NAME, 'Taishan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0222' AS STATION_CODE, '02' AS LINE_CODE, '利津路' AS STATION_NAME, 'Lijin Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0223' AS STATION_CODE, '02' AS LINE_CODE, '台东' AS STATION_NAME, 'Taidong' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0224' AS STATION_CODE, '02' AS LINE_CODE, '海信桥' AS STATION_NAME, 'Haixin Bridge' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0225' AS STATION_CODE, '02' AS LINE_CODE, '芝泉路' AS STATION_NAME, 'Zhiquan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0226' AS STATION_CODE, '02' AS LINE_CODE, '五四广场' AS STATION_NAME, 'May 4[sup]th[/sup] Square' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0227' AS STATION_CODE, '02' AS LINE_CODE, '浮山所' AS STATION_NAME, 'Fushansuo' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0228' AS STATION_CODE, '02' AS LINE_CODE, '燕儿岛路' AS STATION_NAME, 'Yan''erdao Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0229' AS STATION_CODE, '02' AS LINE_CODE, '高雄路' AS STATION_NAME, 'Gaoxiong Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0230' AS STATION_CODE, '02' AS LINE_CODE, '麦岛' AS STATION_NAME, 'Maidao' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0231' AS STATION_CODE, '02' AS LINE_CODE, '海游路' AS STATION_NAME, 'Haiyou Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0232' AS STATION_CODE, '02' AS LINE_CODE, '海川路' AS STATION_NAME, 'Haichuan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0233' AS STATION_CODE, '02' AS LINE_CODE, '海安路' AS STATION_NAME, 'Hai''an Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0234' AS STATION_CODE, '02' AS LINE_CODE, '石老人浴场' AS STATION_NAME, 'Shilaoren Beach' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0235' AS STATION_CODE, '02' AS LINE_CODE, '苗岭路' AS STATION_NAME, 'Miaoling Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0236' AS STATION_CODE, '02' AS LINE_CODE, '同安路' AS STATION_NAME, 'Tong''an Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0237' AS STATION_CODE, '02' AS LINE_CODE, '辽阳东路' AS STATION_NAME, 'Liaoyang East Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0238' AS STATION_CODE, '02' AS LINE_CODE, '东韩' AS STATION_NAME, 'Donghan' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0239' AS STATION_CODE, '02' AS LINE_CODE, '华楼山路' AS STATION_NAME, 'Hualoushan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0240' AS STATION_CODE, '02' AS LINE_CODE, '枣山路' AS STATION_NAME, 'Zaoshan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0241' AS STATION_CODE, '02' AS LINE_CODE, '李村' AS STATION_NAME, 'Licun' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0242' AS STATION_CODE, '02' AS LINE_CODE, '李村公园' AS STATION_NAME, 'Licun Park' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0340' AS STATION_CODE, '03' AS LINE_CODE, '青岛站' AS STATION_NAME, 'Qingdao Railway Station' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0341' AS STATION_CODE, '03' AS LINE_CODE, '人民会堂' AS STATION_NAME, 'Hall of the People' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0342' AS STATION_CODE, '03' AS LINE_CODE, '汇泉广场' AS STATION_NAME, 'Huiquan Square' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0343' AS STATION_CODE, '03' AS LINE_CODE, '中山公园' AS STATION_NAME, 'Zhongshan Park' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0344' AS STATION_CODE, '03' AS LINE_CODE, '太平角公园' AS STATION_NAME, 'Taipingjiao Park' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0345' AS STATION_CODE, '03' AS LINE_CODE, '延安三路' AS STATION_NAME, 'Yan''an 3[sup]rd[/sup] Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0346' AS STATION_CODE, '03' AS LINE_CODE, '五四广场' AS STATION_NAME, 'May 4[sup]th[/sup] Square' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0347' AS STATION_CODE, '03' AS LINE_CODE, '江西路' AS STATION_NAME, 'Jiangxi Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0348' AS STATION_CODE, '03' AS LINE_CODE, '宁夏路' AS STATION_NAME, 'Ningxia Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0349' AS STATION_CODE, '03' AS LINE_CODE, '敦化路' AS STATION_NAME, 'Dunhua Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0350' AS STATION_CODE, '03' AS LINE_CODE, '错埠岭' AS STATION_NAME, 'Cuobuling' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0351' AS STATION_CODE, '03' AS LINE_CODE, '清江路' AS STATION_NAME, 'Qingjiang Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0352' AS STATION_CODE, '03' AS LINE_CODE, '双山' AS STATION_NAME, 'Shuangshan' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0353' AS STATION_CODE, '03' AS LINE_CODE, '长沙路' AS STATION_NAME, 'Changsha Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0354' AS STATION_CODE, '03' AS LINE_CODE, '地铁大厦' AS STATION_NAME, 'Metro Building' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0355' AS STATION_CODE, '03' AS LINE_CODE, '海尔路' AS STATION_NAME, 'Hai''er Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0356' AS STATION_CODE, '03' AS LINE_CODE, '万年泉路' AS STATION_NAME, 'Wannianquan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0357' AS STATION_CODE, '03' AS LINE_CODE, '李村' AS STATION_NAME, 'Licun' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0358' AS STATION_CODE, '03' AS LINE_CODE, '君峰路' AS STATION_NAME, 'Junfeng Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0359' AS STATION_CODE, '03' AS LINE_CODE, '振华路' AS STATION_NAME, 'Zhenhua Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0360' AS STATION_CODE, '03' AS LINE_CODE, '永平路' AS STATION_NAME, 'Yongping Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0361' AS STATION_CODE, '03' AS LINE_CODE, '青岛北站' AS STATION_NAME, 'Qingdao North Railway Station' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0421' AS STATION_CODE, '04' AS LINE_CODE, '人民会堂' AS STATION_NAME, 'Hall of the People' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0422' AS STATION_CODE, '04' AS LINE_CODE, '信号山(青大附院)' AS STATION_NAME, 'Xinhaoshan (The Affiliated Hospital of Qingdao University)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0423' AS STATION_CODE, '04' AS LINE_CODE, '观象山(市立医院)' AS STATION_NAME, 'Guanxiangshan (Qingdao Municipal Hospital)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0424' AS STATION_CODE, '04' AS LINE_CODE, '泰山路' AS STATION_NAME, 'Taishan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0425' AS STATION_CODE, '04' AS LINE_CODE, '昌乐路' AS STATION_NAME, 'Changle Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0426' AS STATION_CODE, '04' AS LINE_CODE, '海泊河公园' AS STATION_NAME, 'Haipohe Park' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0427' AS STATION_CODE, '04' AS LINE_CODE, '海泊桥(海慈医疗)' AS STATION_NAME, 'Haipo Bridge (Hiser Hospital)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0428' AS STATION_CODE, '04' AS LINE_CODE, '西吴家村' AS STATION_NAME, 'Xiwujiacun' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0429' AS STATION_CODE, '04' AS LINE_CODE, '错埠岭' AS STATION_NAME, 'Cuobuling' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0430' AS STATION_CODE, '04' AS LINE_CODE, '福辽立交桥' AS STATION_NAME, 'Fuliao Flyover' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0431' AS STATION_CODE, '04' AS LINE_CODE, '洪山坡(妇儿医院)' AS STATION_NAME, 'Hongshanpo (Qingdao Women and Children??s Hospital)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0432' AS STATION_CODE, '04' AS LINE_CODE, '劲松三路' AS STATION_NAME, 'Jingsong 3[sup]rd[/sup] Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0433' AS STATION_CODE, '04' AS LINE_CODE, '埠西' AS STATION_NAME, 'Buxi' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0434' AS STATION_CODE, '04' AS LINE_CODE, '大埠东' AS STATION_NAME, 'Dabudong' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0435' AS STATION_CODE, '04' AS LINE_CODE, '辽阳东路' AS STATION_NAME, 'Liaoyang East Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0436' AS STATION_CODE, '04' AS LINE_CODE, '董家下庄' AS STATION_NAME, 'Dongjiaxiazhuang' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0437' AS STATION_CODE, '04' AS LINE_CODE, '科苑经七路' AS STATION_NAME, 'Keyuanjing 7[sup]th[/sup] Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0438' AS STATION_CODE, '04' AS LINE_CODE, '张村' AS STATION_NAME, 'Zhangcun' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0439' AS STATION_CODE, '04' AS LINE_CODE, '彭家庄' AS STATION_NAME, 'Pengjiazhuang' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0440' AS STATION_CODE, '04' AS LINE_CODE, '南宅科' AS STATION_NAME, 'Nanzhaike' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0441' AS STATION_CODE, '04' AS LINE_CODE, '小崂山' AS STATION_NAME, 'Xiaolaoshan' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0442' AS STATION_CODE, '04' AS LINE_CODE, '沙子口' AS STATION_NAME, 'Shazikou' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0443' AS STATION_CODE, '04' AS LINE_CODE, '段家埠' AS STATION_NAME, 'Duanjiabu' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0444' AS STATION_CODE, '04' AS LINE_CODE, '登瀛' AS STATION_NAME, 'Dengying' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0445' AS STATION_CODE, '04' AS LINE_CODE, '大河东' AS STATION_NAME, 'Dahedong' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0621' AS STATION_CODE, '06' AS LINE_CODE, '灵山湾' AS STATION_NAME, 'Lingshan Bay' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0622' AS STATION_CODE, '06' AS LINE_CODE, '辛屯' AS STATION_NAME, 'Xintun' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0623' AS STATION_CODE, '06' AS LINE_CODE, '华山' AS STATION_NAME, 'Huashan' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0624' AS STATION_CODE, '06' AS LINE_CODE, '星海滩路' AS STATION_NAME, 'Xinghaitan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0625' AS STATION_CODE, '06' AS LINE_CODE, '赵家庙(影视产业园)' AS STATION_NAME, 'Zhaojiamiao (Film Metropolis)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0626' AS STATION_CODE, '06' AS LINE_CODE, '毛家山(黄海学院)' AS STATION_NAME, 'Maojiashan (Qingdao Huanghai University)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0627' AS STATION_CODE, '06' AS LINE_CODE, '西门外' AS STATION_NAME, 'Ximenwai' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0628' AS STATION_CODE, '06' AS LINE_CODE, '北门外' AS STATION_NAME, 'Beimenwai' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0629' AS STATION_CODE, '06' AS LINE_CODE, '王家港' AS STATION_NAME, 'Wangjiagang' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0630' AS STATION_CODE, '06' AS LINE_CODE, '九顶山' AS STATION_NAME, 'Jiudingshan' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0631' AS STATION_CODE, '06' AS LINE_CODE, '钱塘江路(青职学院)' AS STATION_NAME, 'Qiantangjiang Rd (Qingdao Technical College)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0632' AS STATION_CODE, '06' AS LINE_CODE, '扒山(滨海学院)' AS STATION_NAME, 'Pashan (Qingdao Binhai University)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0633' AS STATION_CODE, '06' AS LINE_CODE, '青大附院西海岸院区' AS STATION_NAME, 'WestCoastCampus oftheAffiliatedHospital ofQingdaoUniversity' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0634' AS STATION_CODE, '06' AS LINE_CODE, '港头' AS STATION_NAME, 'Gangtou' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0635' AS STATION_CODE, '06' AS LINE_CODE, '薛家泊子' AS STATION_NAME, 'Xuejiapozi' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0636' AS STATION_CODE, '06' AS LINE_CODE, '马家楼' AS STATION_NAME, 'Majialou' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0637' AS STATION_CODE, '06' AS LINE_CODE, '抓马山' AS STATION_NAME, 'Zhuamashan' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0638' AS STATION_CODE, '06' AS LINE_CODE, '青岛九中(幸福小镇)' AS STATION_NAME, 'Qingdao No.9 High School (Xingfuxiaozhen)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0639' AS STATION_CODE, '06' AS LINE_CODE, '河洛埠(中德生态园)' AS STATION_NAME, 'Heluobu (Sino-German Ecopark)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0640' AS STATION_CODE, '06' AS LINE_CODE, '山王河(福莱社区)' AS STATION_NAME, 'Shanwanghe (Fulai Community)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0641' AS STATION_CODE, '06' AS LINE_CODE, '横云山路' AS STATION_NAME, 'Hengyunshan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0828' AS STATION_CODE, '08' AS LINE_CODE, '青岛北站' AS STATION_NAME, 'Qingdao North Railway Station' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0829' AS STATION_CODE, '08' AS LINE_CODE, '大洋' AS STATION_NAME, 'Dayang' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0830' AS STATION_CODE, '08' AS LINE_CODE, '红岛科技馆(方特)' AS STATION_NAME, 'Hongdao Science and Technology Museum (Fangte)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0831' AS STATION_CODE, '08' AS LINE_CODE, '观涛' AS STATION_NAME, 'Guantao' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0832' AS STATION_CODE, '08' AS LINE_CODE, '健身中心(红岛会展)' AS STATION_NAME, 'Fitness Center' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0833' AS STATION_CODE, '08' AS LINE_CODE, '健康中心' AS STATION_NAME, 'Health Center' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0834' AS STATION_CODE, '08' AS LINE_CODE, '红岛火车站' AS STATION_NAME, 'Hongdao Railway Station' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0835' AS STATION_CODE, '08' AS LINE_CODE, '大涧' AS STATION_NAME, 'Dajian' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0836' AS STATION_CODE, '08' AS LINE_CODE, '胶东' AS STATION_NAME, 'Jiaodong' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0837' AS STATION_CODE, '08' AS LINE_CODE, '胶东机场' AS STATION_NAME, 'Jiaodong International Airport' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '0838' AS STATION_CODE, '08' AS LINE_CODE, '胶州北站' AS STATION_NAME, 'Jiaozhou North Railway Station' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1121' AS STATION_CODE, '11' AS LINE_CODE, '苗岭路' AS STATION_NAME, 'Miaoling Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1122' AS STATION_CODE, '11' AS LINE_CODE, '会展中心' AS STATION_NAME, 'Convention Center' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1123' AS STATION_CODE, '11' AS LINE_CODE, '青岛二中' AS STATION_NAME, 'Qingdao No.2 Middle School' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1124' AS STATION_CODE, '11' AS LINE_CODE, '青岛科大' AS STATION_NAME, 'Qingdao University of Science Technology' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1125' AS STATION_CODE, '11' AS LINE_CODE, '张村' AS STATION_NAME, 'Zhangcun' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1126' AS STATION_CODE, '11' AS LINE_CODE, '枯桃' AS STATION_NAME, 'Kutao' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1127' AS STATION_CODE, '11' AS LINE_CODE, '海洋大学' AS STATION_NAME, 'Ocean University of China' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1128' AS STATION_CODE, '11' AS LINE_CODE, '世博园' AS STATION_NAME, 'International Horticultural Expo Garden' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1129' AS STATION_CODE, '11' AS LINE_CODE, '北宅' AS STATION_NAME, 'Beizhai' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1130' AS STATION_CODE, '11' AS LINE_CODE, '北九水' AS STATION_NAME, 'Beijiushui' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1131' AS STATION_CODE, '11' AS LINE_CODE, '庙石' AS STATION_NAME, 'Miaoshi' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1132' AS STATION_CODE, '11' AS LINE_CODE, '浦里' AS STATION_NAME, 'Puli' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1133' AS STATION_CODE, '11' AS LINE_CODE, '鳌山卫' AS STATION_NAME, 'Aoshanwei' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1134' AS STATION_CODE, '11' AS LINE_CODE, '山东大学' AS STATION_NAME, 'Shandong University' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1135' AS STATION_CODE, '11' AS LINE_CODE, '蓝色硅谷' AS STATION_NAME, 'Oceantec Valley' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1136' AS STATION_CODE, '11' AS LINE_CODE, '水泊' AS STATION_NAME, 'Shuipo' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1137' AS STATION_CODE, '11' AS LINE_CODE, '博览中心' AS STATION_NAME, 'Expo Center' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1138' AS STATION_CODE, '11' AS LINE_CODE, '温泉东' AS STATION_NAME, 'Wenquan East' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1139' AS STATION_CODE, '11' AS LINE_CODE, '皋虞' AS STATION_NAME, 'Gaoyu' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1140' AS STATION_CODE, '11' AS LINE_CODE, '臧村' AS STATION_NAME, 'Zangcun' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1141' AS STATION_CODE, '11' AS LINE_CODE, '钱谷山' AS STATION_NAME, 'Qiangu Mountain' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1142' AS STATION_CODE, '11' AS LINE_CODE, '鳌山湾' AS STATION_NAME, 'Aoshan Bay' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1321' AS STATION_CODE, '13' AS LINE_CODE, '嘉陵江西路' AS STATION_NAME, 'Jialingjiang West Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1322' AS STATION_CODE, '13' AS LINE_CODE, '香江路' AS STATION_NAME, 'Xiangjiang Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1323' AS STATION_CODE, '13' AS LINE_CODE, '井冈山路' AS STATION_NAME, 'Jinggangshan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1324' AS STATION_CODE, '13' AS LINE_CODE, '积米崖' AS STATION_NAME, 'Jimiya' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1325' AS STATION_CODE, '13' AS LINE_CODE, '灵山卫' AS STATION_NAME, 'Lingshanwei' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1326' AS STATION_CODE, '13' AS LINE_CODE, '学院路' AS STATION_NAME, 'Xueyuan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1327' AS STATION_CODE, '13' AS LINE_CODE, '朝阳山' AS STATION_NAME, 'Chaoyangshan' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1328' AS STATION_CODE, '13' AS LINE_CODE, '辛屯' AS STATION_NAME, 'Xintun' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1329' AS STATION_CODE, '13' AS LINE_CODE, '两河' AS STATION_NAME, 'Lianghe' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1330' AS STATION_CODE, '13' AS LINE_CODE, '隐珠' AS STATION_NAME, 'Yinzhu' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1331' AS STATION_CODE, '13' AS LINE_CODE, '凤凰山路' AS STATION_NAME, 'Fenghuangshan Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1332' AS STATION_CODE, '13' AS LINE_CODE, '双珠路' AS STATION_NAME, 'Shuangzhu Rd' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1333' AS STATION_CODE, '13' AS LINE_CODE, '世纪大道' AS STATION_NAME, 'Shiji Ave' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1334' AS STATION_CODE, '13' AS LINE_CODE, '盛海路(世博城)' AS STATION_NAME, 'Shenghai Rd (World Expo City)' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1335' AS STATION_CODE, '13' AS LINE_CODE, '大珠山' AS STATION_NAME, 'Dazhu Mountain' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1336' AS STATION_CODE, '13' AS LINE_CODE, '张家楼' AS STATION_NAME, 'Zhangjialou' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1337' AS STATION_CODE, '13' AS LINE_CODE, '古镇口' AS STATION_NAME, 'Guzhenkou' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1338' AS STATION_CODE, '13' AS LINE_CODE, '龙湾' AS STATION_NAME, 'Longwan Bay' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1339' AS STATION_CODE, '13' AS LINE_CODE, '琅琊' AS STATION_NAME, 'Langya' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1340' AS STATION_CODE, '13' AS LINE_CODE, '贡口湾' AS STATION_NAME, 'Gongkou Bay' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1341' AS STATION_CODE, '13' AS LINE_CODE, '董家口港' AS STATION_NAME, 'Dongjiakou Port' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1342' AS STATION_CODE, '13' AS LINE_CODE, '泊里' AS STATION_NAME, 'Poli' AS STATION_EN_NAME FROM DUAL
    UNION ALL SELECT '1343' AS STATION_CODE, '13' AS LINE_CODE, '董家口火车站' AS STATION_NAME, 'Dongjiakou Railway Station' AS STATION_EN_NAME FROM DUAL
) S
ON (T.STATION_CODE = S.STATION_CODE)
WHEN MATCHED THEN UPDATE SET
    T.LINE_CODE = S.LINE_CODE,
    T.STATION_NAME = S.STATION_NAME,
    T.STATION_EN_NAME = S.STATION_EN_NAME
WHEN NOT MATCHED THEN INSERT (
    STATION_CODE,
    LINE_CODE,
    STATION_NAME,
    STATION_EN_NAME
) VALUES (
    S.STATION_CODE,
    S.LINE_CODE,
    S.STATION_NAME,
    S.STATION_EN_NAME
);

COMMIT;
