-- QRCODE_SUPPLEMENT_REQUEST：IF5A-03 补站请求台账

CREATE TABLE QRCODE_SUPPLEMENT_REQUEST (
    CARD_ID              VARCHAR2(32)  NOT NULL,
    TXN_SEQ              VARCHAR2(32)  NOT NULL,
    ADVICE_OPT           VARCHAR2(8)   NOT NULL,
    CODE_STATUS_SNAPSHOT VARCHAR2(8),
    HANDLE_STATION_CODE  VARCHAR2(16),
    HANDLE_DATE_TIME     VARCHAR2(20),
    TRX_AMOUNT           VARCHAR2(16),
    HANDLE_STATUS        VARCHAR2(16)  NOT NULL,
    FAIL_REASON          VARCHAR2(256),
    RETRY_COUNT          NUMBER(6)     DEFAULT 0 NOT NULL,
    CREATE_TIME          DATE          DEFAULT SYSDATE NOT NULL,
    UPDATE_TIME          DATE          DEFAULT SYSDATE NOT NULL
);

CREATE UNIQUE INDEX UK_QSR_CARD_SEQ_ADVICE
    ON QRCODE_SUPPLEMENT_REQUEST (CARD_ID, TXN_SEQ, ADVICE_OPT);

CREATE INDEX IDX_QSR_STATUS_CREATE
    ON QRCODE_SUPPLEMENT_REQUEST (HANDLE_STATUS, CREATE_TIME);

COMMENT ON TABLE QRCODE_SUPPLEMENT_REQUEST IS 'IF5A-03 补站请求台账：幂等声明 + 闸机结果证据';
COMMENT ON COLUMN QRCODE_SUPPLEMENT_REQUEST.TXN_SEQ IS '声明时的 QRCODE_STATUS.TXN_SEQ，空值兜为 0';
COMMENT ON COLUMN QRCODE_SUPPLEMENT_REQUEST.HANDLE_STATUS IS 'PENDING/SUCCESS/REJECTED/UNKNOWN';
COMMENT ON COLUMN QRCODE_SUPPLEMENT_REQUEST.RETRY_COUNT IS 'REJECTED 后被重新声明的次数';
