-- QRCODE_SUPPLEMENT_REQUEST：IF5A-03 补站请求台账
--
-- 来源：2026-09-14 CardDataHandler 逐行审查的 L001（幂等是纯 TOCTOU）与 L002（闸机结果未知零证据）。
--
-- 两个不变量，改本脚本前 MUST 先读：
--   1. CARD_ID / TXN_SEQ / ADVICE_OPT 三列都 NOT NULL。Oracle 唯一索引对 NULL 不去重，
--      任何一列允许 NULL 都会让 UK_QSR_CARD_SEQ_ADVICE 的并发防护静默失效。
--      QRCODE_STATUS.TXN_SEQ 本身可为空，因此写入前由 SupplementRequestLedger 兜成 '0'。
--   2. 本表 NEVER 参与乘车码状态机推进。QRCODE_STATUS / QRCODE_TXN_DETAIL 的唯一写入方
--      仍是 gate.GateTicketWriter（fep-dev-server 回调 /ci/agm/notiVerifyResult 那个独立请求）。
--
-- HANDLE_STATUS 取值：PENDING / SUCCESS / REJECTED / UNKNOWN
--   REJECTED 可由 BOM 重新发起（reclaimRejected 的 CAS 条件）；
--   UNKNOWN NEVER 允许直接重试，MUST 先查票卡状态。

--   3. 幂等的载体是唯一索引 UK_QSR_CARD_SEQ_ADVICE，不再另建同列主键。
--      Oracle 对「与已有索引列表完全相同」的第二个索引会报 ORA-01408，两者只能留一个；
--      留唯一索引是因为代码与文档都按这个名字引用它（SupplementRequestMapper 的类注释）。

CREATE TABLE QRCODE_SUPPLEMENT_REQUEST (
    CARD_ID              VARCHAR2(32)  NOT NULL,
    TXN_SEQ              VARCHAR2(32)  NOT NULL,
    ADVICE_OPT           VARCHAR2(8)   NOT NULL,
    CODE_STATUS_SNAPSHOT VARCHAR2(8),
    HANDLE_STATION_CODE  VARCHAR2(16),
    HANDLE_DATE_TIME     VARCHAR2(20),
    TRX_AMOUNT           VARCHAR2(16),
    HANDLE_STATUS        VARCHAR2(16)  NOT NULL,
    FAIL_REASON          VARCHAR2(256),
    RETRY_COUNT          NUMBER(6)     DEFAULT 0 NOT NULL,
    CREATE_TIME          DATE          DEFAULT SYSDATE NOT NULL,
    UPDATE_TIME          DATE          DEFAULT SYSDATE NOT NULL
);

CREATE UNIQUE INDEX UK_QSR_CARD_SEQ_ADVICE
    ON QRCODE_SUPPLEMENT_REQUEST (CARD_ID, TXN_SEQ, ADVICE_OPT);

CREATE INDEX IDX_QSR_STATUS_CREATE
    ON QRCODE_SUPPLEMENT_REQUEST (HANDLE_STATUS, CREATE_TIME);

COMMENT ON TABLE QRCODE_SUPPLEMENT_REQUEST IS 'IF5A-03 补站请求台账：幂等声明 + 闸机结果证据';
COMMENT ON COLUMN QRCODE_SUPPLEMENT_REQUEST.TXN_SEQ IS '声明时的 QRCODE_STATUS.TXN_SEQ，空值兜为 0';
COMMENT ON COLUMN QRCODE_SUPPLEMENT_REQUEST.HANDLE_STATUS IS 'PENDING/SUCCESS/REJECTED/UNKNOWN';
COMMENT ON COLUMN QRCODE_SUPPLEMENT_REQUEST.RETRY_COUNT IS 'REJECTED 后被重新声明的次数';
